// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See VTestTop_L2L3L2.h for the primary calling header

#ifndef VERILATED_VTESTTOP_L2L3L2_MSHR_32_H_
#define VERILATED_VTESTTOP_L2L3L2_MSHR_32_H_  // guard

#include "verilated.h"


class VTestTop_L2L3L2__Syms;

class alignas(VL_CACHE_LINE_BYTES) VTestTop_L2L3L2_MSHR_32 final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clock,0,0);
        VL_IN8(reset,0,0);
        VL_IN8(io_id,3,0);
        VL_IN8(io_enable,0,0);
        VL_IN8(io_alloc_valid,0,0);
        VL_IN8(io_alloc_bits_channel,2,0);
        VL_IN8(io_alloc_bits_opcode,2,0);
        VL_IN8(io_alloc_bits_param,2,0);
        VL_IN8(io_alloc_bits_size,0,0);
        VL_IN8(io_alloc_bits_set,6,0);
        VL_IN8(io_alloc_bits_tag,7,0);
        VL_IN8(io_alloc_bits_off,0,0);
        VL_IN8(io_alloc_bits_mask,0,0);
        VL_IN8(io_alloc_bits_bufIdx,2,0);
        VL_IN8(io_alloc_bits_preferCache,0,0);
        VL_IN8(io_alloc_bits_dirty,0,0);
        VL_IN8(io_alloc_bits_fromProbeHelper,0,0);
        VL_IN8(io_alloc_bits_fromCmoHelper,0,0);
        VL_IN8(io_alloc_bits_needProbeAckData,0,0);
        VL_OUT8(io_status_valid,0,0);
        VL_OUT8(io_status_bits_set,6,0);
        VL_OUT8(io_status_bits_tag,7,0);
        VL_OUT8(io_status_bits_way,1,0);
        VL_OUT8(io_status_bits_way_reg,1,0);
        VL_OUT8(io_status_bits_nestB,0,0);
        VL_OUT8(io_status_bits_nestC,0,0);
        VL_OUT8(io_status_bits_will_grant_data,0,0);
        VL_OUT8(io_status_bits_will_save_data,0,0);
        VL_OUT8(io_status_bits_will_free,0,0);
        VL_IN8(io_resps_sink_c_valid,0,0);
        VL_IN8(io_resps_sink_c_bits_hasData,0,0);
        VL_IN8(io_resps_sink_c_bits_param,2,0);
        VL_IN8(io_resps_sink_c_bits_last,0,0);
        VL_IN8(io_resps_sink_c_bits_bufIdx,2,0);
        VL_IN8(io_resps_sink_d_valid,0,0);
        VL_IN8(io_resps_sink_d_bits_opcode,2,0);
        VL_IN8(io_resps_sink_d_bits_param,2,0);
        VL_IN8(io_resps_sink_d_bits_sink,2,0);
        VL_IN8(io_resps_sink_d_bits_last,0,0);
        VL_IN8(io_resps_sink_d_bits_denied,0,0);
        VL_IN8(io_resps_sink_d_bits_dirty,0,0);
        VL_IN8(io_resps_sink_d_bits_bufIdx,2,0);
        VL_IN8(io_resps_sink_e_valid,0,0);
        VL_IN8(io_resps_source_d_valid,0,0);
        VL_IN8(io_nestedwb_set,6,0);
        VL_IN8(io_nestedwb_tag,7,0);
        VL_IN8(io_nestedwb_b_toN,0,0);
        VL_IN8(io_nestedwb_b_toB,0,0);
        VL_IN8(io_nestedwb_b_clr_dirty,0,0);
        VL_IN8(io_nestedwb_b_set_dirty,0,0);
        VL_IN8(io_nestedwb_c_set_dirty,0,0);
        VL_IN8(io_nestedwb_c_set_hit,0,0);
        VL_IN8(io_nestedwb_clients_0_isToN,0,0);
        VL_IN8(io_nestedwb_clients_1_isToN,0,0);
        VL_IN8(io_tasks_sink_a_ready,0,0);
        VL_OUT8(__PVT__io_tasks_sink_a_valid,0,0);
        VL_OUT8(io_tasks_sink_a_bits_set,6,0);
        VL_OUT8(io_tasks_sink_a_bits_tag,7,0);
        VL_OUT8(io_tasks_sink_a_bits_size,0,0);
        VL_OUT8(io_tasks_sink_a_bits_off,0,0);
        VL_IN8(io_tasks_source_b_ready,0,0);
        VL_OUT8(io_tasks_source_b_valid,0,0);
        VL_OUT8(io_tasks_source_b_bits_set,6,0);
        VL_OUT8(io_tasks_source_b_bits_tag,7,0);
    };
    struct {
        VL_OUT8(io_tasks_source_b_bits_param,2,0);
        VL_OUT8(io_tasks_source_b_bits_clients,1,0);
        VL_OUT8(io_tasks_source_b_bits_needData,0,0);
        VL_IN8(io_tasks_sink_c_ready,0,0);
        VL_OUT8(io_tasks_sink_c_valid,0,0);
        VL_OUT8(io_tasks_sink_c_bits_set,6,0);
        VL_OUT8(io_tasks_sink_c_bits_tag,7,0);
        VL_OUT8(io_tasks_sink_c_bits_size,0,0);
        VL_OUT8(io_tasks_sink_c_bits_way,1,0);
        VL_OUT8(io_tasks_sink_c_bits_off,0,0);
        VL_OUT8(io_tasks_sink_c_bits_bufIdx,2,0);
        VL_OUT8(io_tasks_sink_c_bits_opcode,2,0);
        VL_OUT8(io_tasks_sink_c_bits_param,2,0);
        VL_OUT8(io_tasks_sink_c_bits_source,3,0);
        VL_OUT8(io_tasks_sink_c_bits_save,0,0);
        VL_OUT8(io_tasks_sink_c_bits_drop,0,0);
        VL_OUT8(io_tasks_sink_c_bits_release,0,0);
        VL_OUT8(io_tasks_sink_c_bits_dirty,0,0);
        VL_IN8(io_tasks_source_d_ready,0,0);
        VL_OUT8(io_tasks_source_d_valid,0,0);
        VL_OUT8(io_tasks_source_d_bits_set,6,0);
        VL_OUT8(io_tasks_source_d_bits_tag,7,0);
        VL_OUT8(io_tasks_source_d_bits_channel,2,0);
        VL_OUT8(io_tasks_source_d_bits_opcode,2,0);
        VL_OUT8(io_tasks_source_d_bits_param,2,0);
        VL_OUT8(io_tasks_source_d_bits_size,0,0);
        VL_OUT8(io_tasks_source_d_bits_way,1,0);
        VL_OUT8(io_tasks_source_d_bits_off,0,0);
        VL_OUT8(io_tasks_source_d_bits_useBypass,0,0);
        VL_OUT8(io_tasks_source_d_bits_bufIdx,2,0);
        VL_OUT8(io_tasks_source_d_bits_denied,0,0);
        VL_OUT8(io_tasks_source_d_bits_sinkId,3,0);
        VL_OUT8(io_tasks_source_d_bits_bypassPut,0,0);
        VL_OUT8(io_tasks_source_d_bits_dirty,0,0);
        VL_IN8(io_tasks_source_a_ready,0,0);
        VL_OUT8(io_tasks_source_a_valid,0,0);
        VL_OUT8(io_tasks_source_a_bits_tag,7,0);
        VL_OUT8(io_tasks_source_a_bits_set,6,0);
        VL_OUT8(io_tasks_source_a_bits_off,0,0);
        VL_OUT8(io_tasks_source_a_bits_mask,0,0);
        VL_OUT8(io_tasks_source_a_bits_opcode,2,0);
        VL_OUT8(io_tasks_source_a_bits_param,2,0);
        VL_OUT8(io_tasks_source_a_bits_source,3,0);
        VL_OUT8(io_tasks_source_a_bits_bufIdx,2,0);
        VL_OUT8(io_tasks_source_a_bits_size,0,0);
        VL_OUT8(io_tasks_source_a_bits_needData,0,0);
        VL_OUT8(io_tasks_source_a_bits_putData,0,0);
        VL_IN8(io_tasks_source_c_ready,0,0);
        VL_OUT8(io_tasks_source_c_valid,0,0);
        VL_OUT8(io_tasks_source_c_bits_opcode,2,0);
        VL_OUT8(io_tasks_source_c_bits_tag,7,0);
        VL_OUT8(io_tasks_source_c_bits_set,6,0);
        VL_OUT8(io_tasks_source_c_bits_param,2,0);
        VL_OUT8(io_tasks_source_c_bits_source,3,0);
        VL_OUT8(io_tasks_source_c_bits_way,1,0);
        VL_OUT8(io_tasks_source_c_bits_dirty,0,0);
        VL_IN8(io_tasks_source_e_ready,0,0);
        VL_OUT8(io_tasks_source_e_valid,0,0);
        VL_OUT8(io_tasks_source_e_bits_sink,2,0);
        VL_IN8(io_tasks_dir_write_ready,0,0);
        VL_OUT8(io_tasks_dir_write_valid,0,0);
        VL_OUT8(io_tasks_dir_write_bits_set,6,0);
        VL_OUT8(io_tasks_dir_write_bits_way,1,0);
        VL_OUT8(io_tasks_dir_write_bits_data_dirty,0,0);
    };
    struct {
        VL_OUT8(io_tasks_dir_write_bits_data_state,1,0);
        VL_OUT8(io_tasks_dir_write_bits_data_clientStates_0,1,0);
        VL_OUT8(io_tasks_dir_write_bits_data_clientStates_1,1,0);
        VL_IN8(io_tasks_tag_write_ready,0,0);
        VL_OUT8(io_tasks_tag_write_valid,0,0);
        VL_OUT8(io_tasks_tag_write_bits_set,6,0);
        VL_OUT8(io_tasks_tag_write_bits_way,1,0);
        VL_OUT8(io_tasks_tag_write_bits_tag,7,0);
        VL_IN8(io_tasks_client_dir_write_ready,0,0);
        VL_OUT8(io_tasks_client_dir_write_valid,0,0);
        VL_OUT8(io_tasks_client_dir_write_bits_set,6,0);
        VL_OUT8(io_tasks_client_dir_write_bits_way,2,0);
        VL_OUT8(io_tasks_client_dir_write_bits_data_0_state,1,0);
        VL_OUT8(io_tasks_client_dir_write_bits_data_1_state,1,0);
        VL_IN8(io_tasks_client_tag_write_ready,0,0);
        VL_OUT8(io_tasks_client_tag_write_valid,0,0);
        VL_OUT8(io_tasks_client_tag_write_bits_set,6,0);
        VL_OUT8(io_tasks_client_tag_write_bits_way,2,0);
        VL_OUT8(io_tasks_client_tag_write_bits_tag,7,0);
        VL_IN8(io_dirResult_valid,0,0);
        VL_IN8(io_dirResult_bits_self_dirty,0,0);
        VL_IN8(io_dirResult_bits_self_state,1,0);
        VL_IN8(io_dirResult_bits_self_clientStates_0,1,0);
        VL_IN8(io_dirResult_bits_self_clientStates_1,1,0);
        VL_IN8(io_dirResult_bits_self_hit,0,0);
        VL_IN8(io_dirResult_bits_self_way,1,0);
        VL_IN8(io_dirResult_bits_self_tag,7,0);
        VL_IN8(io_dirResult_bits_clients_states_0_state,1,0);
        VL_IN8(io_dirResult_bits_clients_states_0_hit,0,0);
        VL_IN8(io_dirResult_bits_clients_states_1_state,1,0);
        VL_IN8(io_dirResult_bits_clients_states_1_hit,0,0);
        VL_IN8(io_dirResult_bits_clients_tag,7,0);
        VL_IN8(io_dirResult_bits_clients_way,2,0);
        VL_IN8(io_c_status_set,6,0);
        VL_IN8(io_c_status_tag,7,0);
        VL_IN8(io_c_status_way,1,0);
        VL_IN8(io_c_status_nestedReleaseData,0,0);
        VL_OUT8(io_c_status_releaseThrough,0,0);
        VL_IN8(io_b_status_set,6,0);
        VL_IN8(io_b_status_tag,7,0);
        VL_IN8(io_b_status_way,1,0);
        VL_IN8(io_b_status_nestedProbeAckData,0,0);
        VL_IN8(io_b_status_probeHelperFinish,0,0);
        VL_OUT8(io_b_status_probeAckDataThrough,0,0);
        VL_IN8(io_releaseThrough,0,0);
        VL_IN8(io_probeAckDataThrough,0,0);
        VL_OUT8(io_is_nestedReleaseData,0,0);
        VL_OUT8(io_is_nestedProbeAckData,0,0);
        VL_OUT8(io_probeHelperFinish,0,0);
        CData/*2:0*/ __PVT__req_channel;
        CData/*2:0*/ __PVT__req_opcode;
        CData/*2:0*/ __PVT__req_param;
        CData/*0:0*/ __PVT__req_size;
        CData/*6:0*/ __PVT__req_set;
        CData/*7:0*/ __PVT__req_tag;
        CData/*0:0*/ __PVT__req_off;
        CData/*2:0*/ __PVT__req_bufIdx;
        CData/*0:0*/ __PVT__req_preferCache;
        CData/*0:0*/ __PVT__req_dirty;
        CData/*0:0*/ __PVT__req_fromProbeHelper;
        CData/*0:0*/ __PVT__req_fromCmoHelper;
        CData/*0:0*/ __PVT__req_needProbeAckData;
        CData/*0:0*/ __PVT__req_valid;
        CData/*1:0*/ __PVT__iam;
    };
    struct {
        CData/*0:0*/ __PVT__meta_reg_self_dirty;
        CData/*1:0*/ __PVT__meta_reg_self_state;
        CData/*1:0*/ __PVT__meta_reg_self_clientStates_0;
        CData/*1:0*/ __PVT__meta_reg_self_clientStates_1;
        CData/*0:0*/ __PVT__meta_reg_self_hit;
        CData/*1:0*/ __PVT__meta_reg_self_way;
        CData/*7:0*/ __PVT__meta_reg_self_tag;
        CData/*1:0*/ __PVT__meta_reg_clients_states_0_state;
        CData/*0:0*/ __PVT__meta_reg_clients_states_0_hit;
        CData/*1:0*/ __PVT__meta_reg_clients_states_1_state;
        CData/*0:0*/ __PVT__meta_reg_clients_states_1_hit;
        CData/*7:0*/ __PVT__meta_reg_clients_tag;
        CData/*2:0*/ __PVT__meta_reg_clients_way;
        CData/*0:0*/ __PVT__meta_valid;
        CData/*0:0*/ __PVT__REG;
        CData/*7:0*/ __PVT___T_5;
        CData/*3:0*/ __PVT___T_7;
        CData/*0:0*/ __PVT___GEN_0;
        CData/*0:0*/ __PVT___GEN_9;
        CData/*1:0*/ __PVT___GEN_10;
        CData/*0:0*/ __PVT___GEN_11;
        CData/*1:0*/ __PVT___GEN_12;
        CData/*7:0*/ __PVT___GEN_14;
        CData/*0:0*/ __PVT___GEN_16;
        CData/*1:0*/ __PVT___GEN_17;
        CData/*1:0*/ __PVT___GEN_18;
        CData/*1:0*/ __PVT___GEN_19;
        CData/*0:0*/ __PVT___GEN_20;
        CData/*0:0*/ __PVT__req_acquire;
        CData/*0:0*/ __PVT__req_needT;
        CData/*0:0*/ __PVT__promoteT_safe;
        CData/*0:0*/ __PVT__gotT;
        CData/*0:0*/ __PVT__gotDirty;
        CData/*0:0*/ __PVT__a_do_release;
        CData/*0:0*/ __PVT__a_do_probe;
        CData/*0:0*/ __PVT__meta_no_clients;
        CData/*0:0*/ __PVT__req_promoteT;
        CData/*0:0*/ __PVT__probe_dirty;
        CData/*1:0*/ __PVT__probes_done;
        CData/*0:0*/ __PVT___client_shrink_perm_T_4;
        CData/*1:0*/ __PVT___GEN_23;
        CData/*0:0*/ __PVT___client_shrink_perm_T_10;
        CData/*0:0*/ __PVT___clients_have_T_T_1;
        CData/*0:0*/ __PVT___clients_have_T_T_3;
        CData/*0:0*/ __PVT__clients_have_T;
        CData/*0:0*/ __PVT___GEN_27;
        CData/*1:0*/ __PVT___highest_perm_T_2;
        CData/*1:0*/ __PVT___highest_perm_T_3;
        CData/*1:0*/ __PVT___highest_perm_T_4;
        CData/*1:0*/ __PVT___highest_perm_T_6;
        CData/*1:0*/ __PVT__highest_perm;
        CData/*1:0*/ __PVT__highest_perm_reg_reg;
        CData/*0:0*/ __PVT__w_probeacklast;
        CData/*0:0*/ __PVT__w_grantlast;
        CData/*0:0*/ __PVT__w_releaseack;
        CData/*0:0*/ __PVT__w_grantack;
        CData/*0:0*/ __PVT__w_putwritten;
        CData/*0:0*/ __PVT__no_wait;
        CData/*0:0*/ __PVT__s_probeack;
        CData/*0:0*/ __PVT__s_execute;
        CData/*0:0*/ __PVT__s_grantack;
        CData/*0:0*/ __PVT__no_schedule_REG;
        CData/*0:0*/ __PVT__s_writerelease;
        CData/*0:0*/ __PVT__s_writeprobe;
    };
    struct {
        CData/*0:0*/ __PVT__s_transferput;
        CData/*0:0*/ __PVT__no_schedule;
        CData/*1:0*/ __PVT__highest_perm_except_me;
        CData/*0:0*/ __PVT__inv_self_dir;
        CData/*2:0*/ __PVT__client_probeack_param_vec_reg_0;
        CData/*2:0*/ __PVT__client_probeack_param_vec_reg_1;
        CData/*0:0*/ __PVT__replace_need_release;
        CData/*0:0*/ __PVT__prefetch_miss_need_probe_vec_0;
        CData/*0:0*/ __PVT__prefetch_miss_need_probe_vec_1;
        CData/*0:0*/ __PVT__prefetch_miss_need_probe;
        CData/*0:0*/ __PVT__prefetch_need_data;
        CData/*0:0*/ __PVT___transmit_from_other_client_T_2;
        CData/*0:0*/ __PVT___transmit_from_other_client_T_12;
        CData/*0:0*/ __PVT__transmit_from_other_client_reg;
        CData/*0:0*/ __PVT__transmit_from_other_client;
        CData/*0:0*/ __PVT__releaseThrough;
        CData/*0:0*/ __PVT__releaseDrop;
        CData/*0:0*/ __PVT__releaseSave;
        CData/*0:0*/ __PVT__probeAckDataThrough;
        CData/*0:0*/ __PVT__probeAckDataDrop;
        CData/*0:0*/ __PVT__probeAckDataSave;
        CData/*0:0*/ __PVT__someClientHasProbeAckData;
        CData/*0:0*/ __PVT___new_self_meta_dirty_T;
        CData/*0:0*/ __PVT___new_self_meta_dirty_T_8;
        CData/*0:0*/ __PVT___new_self_meta_dirty_T_9;
        CData/*0:0*/ __PVT__sink_c_resp_valid;
        CData/*0:0*/ __PVT__sinkc_resp_last;
        CData/*2:0*/ __PVT__client_probeack_param_vec_0;
        CData/*1:0*/ __PVT___new_clients_meta_0_state_T_24;
        CData/*2:0*/ __PVT__client_probeack_param_vec_1;
        CData/*1:0*/ __PVT___new_clients_meta_1_state_T_24;
        CData/*0:0*/ __PVT___new_self_meta_dirty_T_13;
        CData/*0:0*/ __PVT___new_self_meta_dirty_T_15;
        CData/*1:0*/ __PVT___new_self_meta_state_T_34;
        CData/*1:0*/ __PVT___new_self_meta_clientStates_0_T_27;
        CData/*0:0*/ __PVT___new_self_meta_clientStates_0_T_33;
        CData/*0:0*/ __PVT___new_self_meta_clientStates_0_T_36;
        CData/*0:0*/ __PVT___new_self_meta_clientStates_0_T_37;
        CData/*1:0*/ __PVT___new_self_meta_clientStates_0_T_38;
        CData/*1:0*/ __PVT___new_self_meta_clientStates_0_T_45;
        CData/*0:0*/ __PVT___new_self_meta_clientStates_1_T_37;
        CData/*1:0*/ __PVT___new_self_meta_clientStates_1_T_38;
        CData/*1:0*/ __PVT___new_self_meta_clientStates_1_T_45;
        CData/*1:0*/ __PVT___new_clients_meta_0_state_T_36;
        CData/*1:0*/ __PVT___new_clients_meta_1_state_T_36;
        CData/*1:0*/ __PVT__new_self_meta_clientStates_0;
        CData/*1:0*/ __PVT__new_self_meta_clientStates_1;
        CData/*2:0*/ __PVT__sink;
        CData/*0:0*/ __PVT__bad_grant;
        CData/*0:0*/ __PVT__REG_1;
        CData/*0:0*/ __PVT___change_self_meta_T_2;
        CData/*0:0*/ __PVT__change_self_meta;
        CData/*0:0*/ __PVT__change_clients_meta_0;
        CData/*0:0*/ __PVT__change_clients_meta_1;
        CData/*0:0*/ __PVT__nested_c_hit_reg;
        CData/*0:0*/ __PVT__nested_c_hit;
        CData/*0:0*/ __PVT__s_acquire;
        CData/*0:0*/ __PVT__s_probe;
        CData/*0:0*/ __PVT__s_release;
        CData/*0:0*/ __PVT__s_wbselfdir;
        CData/*0:0*/ __PVT__s_wbselftag;
        CData/*0:0*/ __PVT__s_wbclientsdir;
        CData/*0:0*/ __PVT__s_wbclientstag;
        CData/*0:0*/ __PVT__w_probeackfirst;
    };
    struct {
        CData/*0:0*/ __PVT__w_probeack;
        CData/*0:0*/ __PVT__w_grantfirst;
        CData/*0:0*/ __PVT__w_grant;
        CData/*0:0*/ __PVT__acquire_flag;
        CData/*0:0*/ __PVT___GEN_91;
        CData/*0:0*/ __PVT__bypassPut;
        CData/*0:0*/ __PVT__bypassPut_latch_reg;
        CData/*0:0*/ __PVT__preferCache;
        CData/*0:0*/ __PVT__bypassGet;
        CData/*0:0*/ __PVT___GEN_100;
        CData/*0:0*/ __PVT___GEN_102;
        CData/*0:0*/ __PVT___T_60;
        CData/*0:0*/ __PVT___T_219;
        CData/*0:0*/ __PVT___GEN_109;
        CData/*0:0*/ __PVT__will_release_through;
        CData/*0:0*/ __PVT__will_probeack_through;
        CData/*0:0*/ __PVT___T_81;
        CData/*0:0*/ __PVT___GEN_124;
        CData/*0:0*/ __PVT___T_133;
        CData/*0:0*/ __PVT___T_146;
        CData/*0:0*/ __PVT___GEN_129;
        CData/*0:0*/ __PVT___T_164;
        CData/*0:0*/ __PVT___T_171;
        CData/*0:0*/ __PVT___GEN_155;
        CData/*0:0*/ __PVT___GEN_158;
        CData/*0:0*/ __PVT___T_185;
        CData/*0:0*/ __PVT___GEN_160;
        CData/*0:0*/ __PVT___GEN_183;
        CData/*0:0*/ __PVT___GEN_184;
        CData/*0:0*/ __PVT___GEN_216;
        CData/*0:0*/ __PVT___GEN_226;
        CData/*0:0*/ __PVT___GEN_236;
        CData/*0:0*/ __PVT___GEN_271;
        CData/*0:0*/ __PVT___GEN_272;
        CData/*0:0*/ __PVT___GEN_276;
        CData/*0:0*/ __PVT___GEN_277;
        CData/*0:0*/ __PVT___GEN_278;
        CData/*0:0*/ __PVT___GEN_282;
        CData/*0:0*/ __PVT___GEN_283;
        CData/*0:0*/ __PVT___GEN_286;
        CData/*0:0*/ __PVT___GEN_288;
        CData/*0:0*/ __PVT___GEN_290;
        CData/*0:0*/ __PVT__will_drop_release;
        CData/*0:0*/ __PVT___T_225;
        CData/*0:0*/ __PVT___probeAckDataSave_T_4;
        CData/*0:0*/ __PVT___GEN_305;
        CData/*0:0*/ __PVT___GEN_306;
        CData/*0:0*/ __PVT___GEN_307;
        CData/*0:0*/ __PVT__clients_meta_busy;
        CData/*0:0*/ __PVT__client_dir_conflict;
        CData/*0:0*/ __PVT__probe_helper_finish;
        CData/*0:0*/ __PVT__client_set_match;
        CData/*0:0*/ __PVT___GEN_318;
        CData/*0:0*/ __PVT__REG_2;
        CData/*0:0*/ __PVT__can_start;
        CData/*0:0*/ __PVT___probe_clients_T_3;
        CData/*1:0*/ __PVT__probe_clients;
        CData/*2:0*/ __PVT___GEN_330;
        CData/*2:0*/ __PVT__io_tasks_sink_c_bits_bufIdx_r;
        CData/*0:0*/ __PVT___GEN_333;
        CData/*0:0*/ __PVT___GEN_334;
        CData/*0:0*/ __PVT___T_249;
        CData/*0:0*/ __PVT___GEN_335;
        CData/*0:0*/ __PVT___T_254;
    };
    struct {
        CData/*0:0*/ __PVT___GEN_336;
        CData/*0:0*/ __PVT___GEN_337;
        CData/*0:0*/ __PVT___GEN_338;
        CData/*0:0*/ __PVT___GEN_339;
        CData/*0:0*/ __PVT___GEN_340;
        CData/*0:0*/ __PVT___GEN_341;
        CData/*0:0*/ __PVT___GEN_342;
        CData/*0:0*/ __PVT___GEN_343;
        CData/*0:0*/ __PVT___T_261;
        CData/*0:0*/ __PVT___GEN_346;
        CData/*1:0*/ __PVT___probeack_last_T;
        CData/*0:0*/ __PVT__probeack_last;
        CData/*0:0*/ __PVT___GEN_356;
        CData/*0:0*/ __PVT___T_271;
        CData/*0:0*/ __PVT___GEN_365;
        CData/*0:0*/ __PVT___T_294;
        CData/*0:0*/ __PVT___T_311;
        CData/*0:0*/ __PVT___GEN_380;
        CData/*0:0*/ __PVT___GEN_381;
        CData/*0:0*/ __PVT___GEN_382;
        CData/*0:0*/ __PVT___GEN_386;
        CData/*0:0*/ __PVT___GEN_387;
        CData/*0:0*/ __PVT___GEN_388;
        CData/*0:0*/ __PVT___GEN_405;
        CData/*0:0*/ __PVT___GEN_412;
        CData/*0:0*/ __PVT___GEN_413;
        CData/*0:0*/ __PVT__REG_3;
        CData/*1:0*/ __PVT__clientBitOH;
        CData/*0:0*/ __PVT___GEN_423;
        CData/*0:0*/ __PVT__preferCache_latch;
        CData/*0:0*/ __PVT__transmit_from_other_client_latch;
        CData/*0:0*/ __PVT___io_status_bits_nestB_T_6;
        CData/*0:0*/ __PVT__nest_c_tag_match;
        CData/*0:0*/ __PVT__nest_c_way_match;
        CData/*0:0*/ __PVT___a_c_through_T_3;
        CData/*0:0*/ __PVT__a_c_through_reg;
        CData/*0:0*/ __PVT___GEN_471;
        CData/*0:0*/ __PVT___GEN_472;
        CData/*0:0*/ __VdfgRegularize_h42e69e07_2_17;
        CData/*0:0*/ __VdfgRegularize_h42e69e07_2_19;
        CData/*0:0*/ __VdfgRegularize_h42e69e07_2_21;
        CData/*0:0*/ __VdfgRegularize_h42e69e07_2_22;
        CData/*0:0*/ __VdfgRegularize_h42e69e07_2_23;
        CData/*0:0*/ __VdfgRegularize_h42e69e07_2_26;
        CData/*0:0*/ __VdfgRegularize_h42e69e07_2_27;
        CData/*0:0*/ __VdfgRegularize_h42e69e07_2_30;
        CData/*0:0*/ __VdfgRegularize_h42e69e07_2_31;
        CData/*0:0*/ __VdfgRegularize_h42e69e07_2_33;
        CData/*0:0*/ __VdfgRegularize_h42e69e07_2_36;
        CData/*0:0*/ __VdfgRegularize_h42e69e07_2_38;
        VL_IN16(io_alloc_bits_source,8,0);
        VL_IN16(io_resps_sink_c_bits_source,8,0);
        VL_OUT16(io_tasks_sink_a_bits_sourceId,8,0);
        VL_OUT16(__PVT__io_tasks_sink_c_bits_sourceId,8,0);
        VL_OUT16(io_tasks_source_d_bits_sourceId,8,0);
        VL_IN16(io_dirResult_bits_idOH,15,0);
        SData/*8:0*/ __PVT__req_source;
    };

    // INTERNAL VARIABLES
    VTestTop_L2L3L2__Syms* const vlSymsp;

    // CONSTRUCTORS
    VTestTop_L2L3L2_MSHR_32(VTestTop_L2L3L2__Syms* symsp, const char* v__name);
    ~VTestTop_L2L3L2_MSHR_32();
    VL_UNCOPYABLE(VTestTop_L2L3L2_MSHR_32);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
