// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See VTestTop_L2L3L2.h for the primary calling header

#ifndef VERILATED_VTESTTOP_L2L3L2_MSHRCTL_H_
#define VERILATED_VTESTTOP_L2L3L2_MSHRCTL_H_  // guard

#include "verilated.h"
class VTestTop_L2L3L2_MSHR;


class VTestTop_L2L3L2__Syms;

class alignas(VL_CACHE_LINE_BYTES) VTestTop_L2L3L2_MSHRCtl final : public VerilatedModule {
  public:
    // CELLS
    VTestTop_L2L3L2_MSHR* __PVT__mshrs_0;
    VTestTop_L2L3L2_MSHR* __PVT__mshrs_1;
    VTestTop_L2L3L2_MSHR* __PVT__mshrs_2;
    VTestTop_L2L3L2_MSHR* __PVT__mshrs_3;
    VTestTop_L2L3L2_MSHR* __PVT__mshrs_4;
    VTestTop_L2L3L2_MSHR* __PVT__mshrs_5;
    VTestTop_L2L3L2_MSHR* __PVT__mshrs_6;
    VTestTop_L2L3L2_MSHR* __PVT__mshrs_7;
    VTestTop_L2L3L2_MSHR* __PVT__mshrs_8;
    VTestTop_L2L3L2_MSHR* __PVT__mshrs_9;
    VTestTop_L2L3L2_MSHR* __PVT__mshrs_10;
    VTestTop_L2L3L2_MSHR* __PVT__mshrs_11;
    VTestTop_L2L3L2_MSHR* __PVT__mshrs_12;
    VTestTop_L2L3L2_MSHR* __PVT__mshrs_13;
    VTestTop_L2L3L2_MSHR* __PVT__mshrs_14;
    VTestTop_L2L3L2_MSHR* __PVT__mshrs_15;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clock,0,0);
        VL_IN8(reset,0,0);
        VL_OUT8(io_toReqArb_blockA_s1,0,0);
        VL_OUT8(io_toReqArb_blockB_s1,0,0);
        VL_IN8(io_fromMainPipe_mshr_alloc_s3_valid,0,0);
        VL_IN8(io_fromMainPipe_mshr_alloc_s3_bits_dirResult_hit,0,0);
        VL_IN8(io_fromMainPipe_mshr_alloc_s3_bits_dirResult_tag,7,0);
        VL_IN8(io_fromMainPipe_mshr_alloc_s3_bits_dirResult_set,6,0);
        VL_IN8(io_fromMainPipe_mshr_alloc_s3_bits_dirResult_way,1,0);
        VL_IN8(io_fromMainPipe_mshr_alloc_s3_bits_dirResult_meta_dirty,0,0);
        VL_IN8(io_fromMainPipe_mshr_alloc_s3_bits_dirResult_meta_state,1,0);
        VL_IN8(io_fromMainPipe_mshr_alloc_s3_bits_dirResult_meta_clients,0,0);
        VL_IN8(io_fromMainPipe_mshr_alloc_s3_bits_dirResult_meta_alias,1,0);
        VL_IN8(io_fromMainPipe_mshr_alloc_s3_bits_dirResult_meta_accessed,0,0);
        VL_IN8(io_fromMainPipe_mshr_alloc_s3_bits_state_s_acquire,0,0);
        VL_IN8(io_fromMainPipe_mshr_alloc_s3_bits_state_s_rprobe,0,0);
        VL_IN8(io_fromMainPipe_mshr_alloc_s3_bits_state_s_pprobe,0,0);
        VL_IN8(io_fromMainPipe_mshr_alloc_s3_bits_state_s_probeack,0,0);
        VL_IN8(io_fromMainPipe_mshr_alloc_s3_bits_state_s_refill,0,0);
        VL_IN8(io_fromMainPipe_mshr_alloc_s3_bits_state_w_rprobeackfirst,0,0);
        VL_IN8(io_fromMainPipe_mshr_alloc_s3_bits_state_w_rprobeacklast,0,0);
        VL_IN8(io_fromMainPipe_mshr_alloc_s3_bits_state_w_pprobeackfirst,0,0);
        VL_IN8(io_fromMainPipe_mshr_alloc_s3_bits_state_w_pprobeacklast,0,0);
        VL_IN8(io_fromMainPipe_mshr_alloc_s3_bits_state_w_pprobeack,0,0);
        VL_IN8(io_fromMainPipe_mshr_alloc_s3_bits_state_w_grantfirst,0,0);
        VL_IN8(io_fromMainPipe_mshr_alloc_s3_bits_state_w_grantlast,0,0);
        VL_IN8(io_fromMainPipe_mshr_alloc_s3_bits_state_w_grant,0,0);
        VL_IN8(io_fromMainPipe_mshr_alloc_s3_bits_state_w_grantack,0,0);
        VL_IN8(io_fromMainPipe_mshr_alloc_s3_bits_state_w_replResp,0,0);
        VL_IN8(io_fromMainPipe_mshr_alloc_s3_bits_task_channel,2,0);
        VL_IN8(io_fromMainPipe_mshr_alloc_s3_bits_task_set,6,0);
        VL_IN8(io_fromMainPipe_mshr_alloc_s3_bits_task_tag,7,0);
        VL_IN8(io_fromMainPipe_mshr_alloc_s3_bits_task_off,0,0);
        VL_IN8(io_fromMainPipe_mshr_alloc_s3_bits_task_alias,1,0);
        VL_IN8(io_fromMainPipe_mshr_alloc_s3_bits_task_opcode,2,0);
        VL_IN8(io_fromMainPipe_mshr_alloc_s3_bits_task_param,2,0);
        VL_IN8(io_fromMainPipe_mshr_alloc_s3_bits_task_size,0,0);
        VL_IN8(io_fromMainPipe_mshr_alloc_s3_bits_task_sourceId,4,0);
        VL_IN8(io_fromMainPipe_mshr_alloc_s3_bits_task_needProbeAckData,0,0);
        VL_IN8(io_fromMainPipe_mshr_alloc_s3_bits_task_aliasTask,0,0);
        VL_IN8(io_fromMainPipe_mshr_alloc_s3_bits_task_reqSource,3,0);
        VL_OUT8(io_toMainPipe_mshr_alloc_ptr,7,0);
        VL_IN8(io_mshrTask_ready,0,0);
        VL_OUT8(io_mshrTask_valid,0,0);
        VL_OUT8(io_mshrTask_bits_channel,2,0);
        VL_OUT8(io_mshrTask_bits_set,6,0);
        VL_OUT8(io_mshrTask_bits_tag,7,0);
        VL_OUT8(io_mshrTask_bits_off,0,0);
        VL_OUT8(io_mshrTask_bits_alias,1,0);
        VL_OUT8(io_mshrTask_bits_opcode,2,0);
        VL_OUT8(io_mshrTask_bits_param,2,0);
        VL_OUT8(io_mshrTask_bits_size,0,0);
        VL_OUT8(io_mshrTask_bits_sourceId,4,0);
        VL_OUT8(io_mshrTask_bits_mshrTask,0,0);
        VL_OUT8(io_mshrTask_bits_mshrId,7,0);
        VL_OUT8(io_mshrTask_bits_aliasTask,0,0);
        VL_OUT8(io_mshrTask_bits_useProbeData,0,0);
        VL_OUT8(io_mshrTask_bits_dirty,0,0);
        VL_OUT8(io_mshrTask_bits_way,1,0);
        VL_OUT8(io_mshrTask_bits_meta_dirty,0,0);
        VL_OUT8(io_mshrTask_bits_meta_state,1,0);
        VL_OUT8(io_mshrTask_bits_meta_clients,0,0);
        VL_OUT8(io_mshrTask_bits_meta_alias,1,0);
        VL_OUT8(io_mshrTask_bits_meta_accessed,0,0);
    };
    struct {
        VL_OUT8(io_mshrTask_bits_metaWen,0,0);
        VL_OUT8(io_mshrTask_bits_tagWen,0,0);
        VL_OUT8(io_mshrTask_bits_dsWen,0,0);
        VL_OUT8(io_mshrTask_bits_wayMask,3,0);
        VL_OUT8(io_mshrTask_bits_replTask,0,0);
        VL_OUT8(io_mshrTask_bits_reqSource,3,0);
        VL_IN8(io_sourceA_ready,0,0);
        VL_OUT8(io_sourceA_valid,0,0);
        VL_OUT8(io_sourceA_bits_opcode,2,0);
        VL_OUT8(io_sourceA_bits_param,2,0);
        VL_OUT8(io_sourceA_bits_size,0,0);
        VL_OUT8(io_sourceA_bits_source,7,0);
        VL_OUT8(io_sourceA_bits_echo_blockisdirty,0,0);
        VL_OUT8(io_sourceA_bits_mask,0,0);
        VL_OUT8(io_sourceA_bits_data,7,0);
        VL_OUT8(io_sourceA_bits_corrupt,0,0);
        VL_IN8(io_sourceB_ready,0,0);
        VL_OUT8(io_sourceB_valid,0,0);
        VL_OUT8(io_sourceB_bits_opcode,2,0);
        VL_OUT8(io_sourceB_bits_param,1,0);
        VL_OUT8(io_sourceB_bits_data,7,0);
        VL_IN8(io_grantStatus_0_valid,0,0);
        VL_IN8(io_grantStatus_0_set,6,0);
        VL_IN8(io_grantStatus_0_tag,7,0);
        VL_IN8(io_grantStatus_1_valid,0,0);
        VL_IN8(io_grantStatus_1_set,6,0);
        VL_IN8(io_grantStatus_1_tag,7,0);
        VL_IN8(io_grantStatus_2_valid,0,0);
        VL_IN8(io_grantStatus_2_set,6,0);
        VL_IN8(io_grantStatus_2_tag,7,0);
        VL_IN8(io_grantStatus_3_valid,0,0);
        VL_IN8(io_grantStatus_3_set,6,0);
        VL_IN8(io_grantStatus_3_tag,7,0);
        VL_IN8(io_grantStatus_4_valid,0,0);
        VL_IN8(io_grantStatus_4_set,6,0);
        VL_IN8(io_grantStatus_4_tag,7,0);
        VL_IN8(io_grantStatus_5_valid,0,0);
        VL_IN8(io_grantStatus_5_set,6,0);
        VL_IN8(io_grantStatus_5_tag,7,0);
        VL_IN8(io_grantStatus_6_valid,0,0);
        VL_IN8(io_grantStatus_6_set,6,0);
        VL_IN8(io_grantStatus_6_tag,7,0);
        VL_IN8(io_grantStatus_7_valid,0,0);
        VL_IN8(io_grantStatus_7_set,6,0);
        VL_IN8(io_grantStatus_7_tag,7,0);
        VL_IN8(io_grantStatus_8_valid,0,0);
        VL_IN8(io_grantStatus_8_set,6,0);
        VL_IN8(io_grantStatus_8_tag,7,0);
        VL_IN8(io_grantStatus_9_valid,0,0);
        VL_IN8(io_grantStatus_9_set,6,0);
        VL_IN8(io_grantStatus_9_tag,7,0);
        VL_IN8(io_grantStatus_10_valid,0,0);
        VL_IN8(io_grantStatus_10_set,6,0);
        VL_IN8(io_grantStatus_10_tag,7,0);
        VL_IN8(io_grantStatus_11_valid,0,0);
        VL_IN8(io_grantStatus_11_set,6,0);
        VL_IN8(io_grantStatus_11_tag,7,0);
        VL_IN8(io_grantStatus_12_valid,0,0);
        VL_IN8(io_grantStatus_12_set,6,0);
        VL_IN8(io_grantStatus_12_tag,7,0);
        VL_IN8(io_grantStatus_13_valid,0,0);
        VL_IN8(io_grantStatus_13_set,6,0);
        VL_IN8(io_grantStatus_13_tag,7,0);
        VL_IN8(io_grantStatus_14_valid,0,0);
    };
    struct {
        VL_IN8(io_grantStatus_14_set,6,0);
        VL_IN8(io_grantStatus_14_tag,7,0);
        VL_IN8(io_grantStatus_15_valid,0,0);
        VL_IN8(io_grantStatus_15_set,6,0);
        VL_IN8(io_grantStatus_15_tag,7,0);
        VL_IN8(io_resps_sinkC_valid,0,0);
        VL_IN8(io_resps_sinkC_set,6,0);
        VL_IN8(io_resps_sinkC_tag,7,0);
        VL_IN8(io_resps_sinkC_respInfo_opcode,2,0);
        VL_IN8(io_resps_sinkC_respInfo_param,2,0);
        VL_IN8(io_resps_sinkC_respInfo_last,0,0);
        VL_IN8(io_resps_sinkD_valid,0,0);
        VL_IN8(io_resps_sinkD_mshrId,7,0);
        VL_IN8(io_resps_sinkD_respInfo_opcode,2,0);
        VL_IN8(io_resps_sinkD_respInfo_param,2,0);
        VL_IN8(io_resps_sinkD_respInfo_last,0,0);
        VL_IN8(io_resps_sinkD_respInfo_dirty,0,0);
        VL_IN8(io_resps_sinkE_valid,0,0);
        VL_IN8(io_resps_sinkE_mshrId,7,0);
        VL_OUT8(io_releaseBufWriteId,7,0);
        VL_IN8(io_nestedwb_set,6,0);
        VL_IN8(io_nestedwb_tag,7,0);
        VL_IN8(io_nestedwb_c_set_dirty,0,0);
        VL_OUT8(io_nestedwbDataId_valid,0,0);
        VL_OUT8(io_nestedwbDataId_bits,7,0);
        VL_IN8(io_pipeStatusVec_0_valid,0,0);
        VL_IN8(io_pipeStatusVec_1_valid,0,0);
        VL_OUT8(io_msInfo_0_valid,0,0);
        VL_OUT8(io_msInfo_0_bits_set,6,0);
        VL_OUT8(io_msInfo_0_bits_way,1,0);
        VL_OUT8(io_msInfo_0_bits_reqTag,7,0);
        VL_OUT8(io_msInfo_0_bits_willFree,0,0);
        VL_OUT8(io_msInfo_0_bits_needRelease,0,0);
        VL_OUT8(io_msInfo_0_bits_releaseNotSent,0,0);
        VL_OUT8(io_msInfo_0_bits_metaTag,7,0);
        VL_OUT8(io_msInfo_0_bits_dirHit,0,0);
        VL_OUT8(io_msInfo_0_bits_nestB,0,0);
        VL_OUT8(io_msInfo_0_bits_mergeB,0,0);
        VL_OUT8(io_msInfo_0_bits_isAcqOrPrefetch,0,0);
        VL_OUT8(io_msInfo_0_bits_isPrefetch,0,0);
        VL_OUT8(io_msInfo_1_valid,0,0);
        VL_OUT8(io_msInfo_1_bits_set,6,0);
        VL_OUT8(io_msInfo_1_bits_way,1,0);
        VL_OUT8(io_msInfo_1_bits_reqTag,7,0);
        VL_OUT8(io_msInfo_1_bits_willFree,0,0);
        VL_OUT8(io_msInfo_1_bits_needRelease,0,0);
        VL_OUT8(io_msInfo_1_bits_releaseNotSent,0,0);
        VL_OUT8(io_msInfo_1_bits_metaTag,7,0);
        VL_OUT8(io_msInfo_1_bits_dirHit,0,0);
        VL_OUT8(io_msInfo_1_bits_nestB,0,0);
        VL_OUT8(io_msInfo_1_bits_mergeB,0,0);
        VL_OUT8(io_msInfo_1_bits_isAcqOrPrefetch,0,0);
        VL_OUT8(io_msInfo_1_bits_isPrefetch,0,0);
        VL_OUT8(io_msInfo_2_valid,0,0);
        VL_OUT8(io_msInfo_2_bits_set,6,0);
        VL_OUT8(io_msInfo_2_bits_way,1,0);
        VL_OUT8(io_msInfo_2_bits_reqTag,7,0);
        VL_OUT8(io_msInfo_2_bits_willFree,0,0);
        VL_OUT8(io_msInfo_2_bits_needRelease,0,0);
        VL_OUT8(io_msInfo_2_bits_releaseNotSent,0,0);
        VL_OUT8(io_msInfo_2_bits_metaTag,7,0);
        VL_OUT8(io_msInfo_2_bits_dirHit,0,0);
        VL_OUT8(io_msInfo_2_bits_nestB,0,0);
        VL_OUT8(io_msInfo_2_bits_mergeB,0,0);
    };
    struct {
        VL_OUT8(io_msInfo_2_bits_isAcqOrPrefetch,0,0);
        VL_OUT8(io_msInfo_2_bits_isPrefetch,0,0);
        VL_OUT8(io_msInfo_3_valid,0,0);
        VL_OUT8(io_msInfo_3_bits_set,6,0);
        VL_OUT8(io_msInfo_3_bits_way,1,0);
        VL_OUT8(io_msInfo_3_bits_reqTag,7,0);
        VL_OUT8(io_msInfo_3_bits_willFree,0,0);
        VL_OUT8(io_msInfo_3_bits_needRelease,0,0);
        VL_OUT8(io_msInfo_3_bits_releaseNotSent,0,0);
        VL_OUT8(io_msInfo_3_bits_metaTag,7,0);
        VL_OUT8(io_msInfo_3_bits_dirHit,0,0);
        VL_OUT8(io_msInfo_3_bits_nestB,0,0);
        VL_OUT8(io_msInfo_3_bits_mergeB,0,0);
        VL_OUT8(io_msInfo_3_bits_isAcqOrPrefetch,0,0);
        VL_OUT8(io_msInfo_3_bits_isPrefetch,0,0);
        VL_OUT8(io_msInfo_4_valid,0,0);
        VL_OUT8(io_msInfo_4_bits_set,6,0);
        VL_OUT8(io_msInfo_4_bits_way,1,0);
        VL_OUT8(io_msInfo_4_bits_reqTag,7,0);
        VL_OUT8(io_msInfo_4_bits_willFree,0,0);
        VL_OUT8(io_msInfo_4_bits_needRelease,0,0);
        VL_OUT8(io_msInfo_4_bits_releaseNotSent,0,0);
        VL_OUT8(io_msInfo_4_bits_metaTag,7,0);
        VL_OUT8(io_msInfo_4_bits_dirHit,0,0);
        VL_OUT8(io_msInfo_4_bits_nestB,0,0);
        VL_OUT8(io_msInfo_4_bits_mergeB,0,0);
        VL_OUT8(io_msInfo_4_bits_isAcqOrPrefetch,0,0);
        VL_OUT8(io_msInfo_4_bits_isPrefetch,0,0);
        VL_OUT8(io_msInfo_5_valid,0,0);
        VL_OUT8(io_msInfo_5_bits_set,6,0);
        VL_OUT8(io_msInfo_5_bits_way,1,0);
        VL_OUT8(io_msInfo_5_bits_reqTag,7,0);
        VL_OUT8(io_msInfo_5_bits_willFree,0,0);
        VL_OUT8(io_msInfo_5_bits_needRelease,0,0);
        VL_OUT8(io_msInfo_5_bits_releaseNotSent,0,0);
        VL_OUT8(io_msInfo_5_bits_metaTag,7,0);
        VL_OUT8(io_msInfo_5_bits_dirHit,0,0);
        VL_OUT8(io_msInfo_5_bits_nestB,0,0);
        VL_OUT8(io_msInfo_5_bits_mergeB,0,0);
        VL_OUT8(io_msInfo_5_bits_isAcqOrPrefetch,0,0);
        VL_OUT8(io_msInfo_5_bits_isPrefetch,0,0);
        VL_OUT8(io_msInfo_6_valid,0,0);
        VL_OUT8(io_msInfo_6_bits_set,6,0);
        VL_OUT8(io_msInfo_6_bits_way,1,0);
        VL_OUT8(io_msInfo_6_bits_reqTag,7,0);
        VL_OUT8(io_msInfo_6_bits_willFree,0,0);
        VL_OUT8(io_msInfo_6_bits_needRelease,0,0);
        VL_OUT8(io_msInfo_6_bits_releaseNotSent,0,0);
        VL_OUT8(io_msInfo_6_bits_metaTag,7,0);
        VL_OUT8(io_msInfo_6_bits_dirHit,0,0);
        VL_OUT8(io_msInfo_6_bits_nestB,0,0);
        VL_OUT8(io_msInfo_6_bits_mergeB,0,0);
        VL_OUT8(io_msInfo_6_bits_isAcqOrPrefetch,0,0);
        VL_OUT8(io_msInfo_6_bits_isPrefetch,0,0);
        VL_OUT8(io_msInfo_7_valid,0,0);
        VL_OUT8(io_msInfo_7_bits_set,6,0);
        VL_OUT8(io_msInfo_7_bits_way,1,0);
        VL_OUT8(io_msInfo_7_bits_reqTag,7,0);
        VL_OUT8(io_msInfo_7_bits_willFree,0,0);
        VL_OUT8(io_msInfo_7_bits_needRelease,0,0);
        VL_OUT8(io_msInfo_7_bits_releaseNotSent,0,0);
        VL_OUT8(io_msInfo_7_bits_metaTag,7,0);
        VL_OUT8(io_msInfo_7_bits_dirHit,0,0);
        VL_OUT8(io_msInfo_7_bits_nestB,0,0);
    };
    struct {
        VL_OUT8(io_msInfo_7_bits_mergeB,0,0);
        VL_OUT8(io_msInfo_7_bits_isAcqOrPrefetch,0,0);
        VL_OUT8(io_msInfo_7_bits_isPrefetch,0,0);
        VL_OUT8(io_msInfo_8_valid,0,0);
        VL_OUT8(io_msInfo_8_bits_set,6,0);
        VL_OUT8(io_msInfo_8_bits_way,1,0);
        VL_OUT8(io_msInfo_8_bits_reqTag,7,0);
        VL_OUT8(io_msInfo_8_bits_willFree,0,0);
        VL_OUT8(io_msInfo_8_bits_needRelease,0,0);
        VL_OUT8(io_msInfo_8_bits_releaseNotSent,0,0);
        VL_OUT8(io_msInfo_8_bits_metaTag,7,0);
        VL_OUT8(io_msInfo_8_bits_dirHit,0,0);
        VL_OUT8(io_msInfo_8_bits_nestB,0,0);
        VL_OUT8(io_msInfo_8_bits_mergeB,0,0);
        VL_OUT8(io_msInfo_8_bits_isAcqOrPrefetch,0,0);
        VL_OUT8(io_msInfo_8_bits_isPrefetch,0,0);
        VL_OUT8(io_msInfo_9_valid,0,0);
        VL_OUT8(io_msInfo_9_bits_set,6,0);
        VL_OUT8(io_msInfo_9_bits_way,1,0);
        VL_OUT8(io_msInfo_9_bits_reqTag,7,0);
        VL_OUT8(io_msInfo_9_bits_willFree,0,0);
        VL_OUT8(io_msInfo_9_bits_needRelease,0,0);
        VL_OUT8(io_msInfo_9_bits_releaseNotSent,0,0);
        VL_OUT8(io_msInfo_9_bits_metaTag,7,0);
        VL_OUT8(io_msInfo_9_bits_dirHit,0,0);
        VL_OUT8(io_msInfo_9_bits_nestB,0,0);
        VL_OUT8(io_msInfo_9_bits_mergeB,0,0);
        VL_OUT8(io_msInfo_9_bits_isAcqOrPrefetch,0,0);
        VL_OUT8(io_msInfo_9_bits_isPrefetch,0,0);
        VL_OUT8(io_msInfo_10_valid,0,0);
        VL_OUT8(io_msInfo_10_bits_set,6,0);
        VL_OUT8(io_msInfo_10_bits_way,1,0);
        VL_OUT8(io_msInfo_10_bits_reqTag,7,0);
        VL_OUT8(io_msInfo_10_bits_willFree,0,0);
        VL_OUT8(io_msInfo_10_bits_needRelease,0,0);
        VL_OUT8(io_msInfo_10_bits_releaseNotSent,0,0);
        VL_OUT8(io_msInfo_10_bits_metaTag,7,0);
        VL_OUT8(io_msInfo_10_bits_dirHit,0,0);
        VL_OUT8(io_msInfo_10_bits_nestB,0,0);
        VL_OUT8(io_msInfo_10_bits_mergeB,0,0);
        VL_OUT8(io_msInfo_10_bits_isAcqOrPrefetch,0,0);
        VL_OUT8(io_msInfo_10_bits_isPrefetch,0,0);
        VL_OUT8(io_msInfo_11_valid,0,0);
        VL_OUT8(io_msInfo_11_bits_set,6,0);
        VL_OUT8(io_msInfo_11_bits_way,1,0);
        VL_OUT8(io_msInfo_11_bits_reqTag,7,0);
        VL_OUT8(io_msInfo_11_bits_willFree,0,0);
        VL_OUT8(io_msInfo_11_bits_needRelease,0,0);
        VL_OUT8(io_msInfo_11_bits_releaseNotSent,0,0);
        VL_OUT8(io_msInfo_11_bits_metaTag,7,0);
        VL_OUT8(io_msInfo_11_bits_dirHit,0,0);
        VL_OUT8(io_msInfo_11_bits_nestB,0,0);
        VL_OUT8(io_msInfo_11_bits_mergeB,0,0);
        VL_OUT8(io_msInfo_11_bits_isAcqOrPrefetch,0,0);
        VL_OUT8(io_msInfo_11_bits_isPrefetch,0,0);
        VL_OUT8(io_msInfo_12_valid,0,0);
        VL_OUT8(io_msInfo_12_bits_set,6,0);
        VL_OUT8(io_msInfo_12_bits_way,1,0);
        VL_OUT8(io_msInfo_12_bits_reqTag,7,0);
        VL_OUT8(io_msInfo_12_bits_willFree,0,0);
        VL_OUT8(io_msInfo_12_bits_needRelease,0,0);
        VL_OUT8(io_msInfo_12_bits_releaseNotSent,0,0);
        VL_OUT8(io_msInfo_12_bits_metaTag,7,0);
        VL_OUT8(io_msInfo_12_bits_dirHit,0,0);
    };
    struct {
        VL_OUT8(io_msInfo_12_bits_nestB,0,0);
        VL_OUT8(io_msInfo_12_bits_mergeB,0,0);
        VL_OUT8(io_msInfo_12_bits_isAcqOrPrefetch,0,0);
        VL_OUT8(io_msInfo_12_bits_isPrefetch,0,0);
        VL_OUT8(io_msInfo_13_valid,0,0);
        VL_OUT8(io_msInfo_13_bits_set,6,0);
        VL_OUT8(io_msInfo_13_bits_way,1,0);
        VL_OUT8(io_msInfo_13_bits_reqTag,7,0);
        VL_OUT8(io_msInfo_13_bits_willFree,0,0);
        VL_OUT8(io_msInfo_13_bits_needRelease,0,0);
        VL_OUT8(io_msInfo_13_bits_releaseNotSent,0,0);
        VL_OUT8(io_msInfo_13_bits_metaTag,7,0);
        VL_OUT8(io_msInfo_13_bits_dirHit,0,0);
        VL_OUT8(io_msInfo_13_bits_nestB,0,0);
        VL_OUT8(io_msInfo_13_bits_mergeB,0,0);
        VL_OUT8(io_msInfo_13_bits_isAcqOrPrefetch,0,0);
        VL_OUT8(io_msInfo_13_bits_isPrefetch,0,0);
        VL_OUT8(io_msInfo_14_valid,0,0);
        VL_OUT8(io_msInfo_14_bits_set,6,0);
        VL_OUT8(io_msInfo_14_bits_way,1,0);
        VL_OUT8(io_msInfo_14_bits_reqTag,7,0);
        VL_OUT8(io_msInfo_14_bits_willFree,0,0);
        VL_OUT8(io_msInfo_14_bits_needRelease,0,0);
        VL_OUT8(io_msInfo_14_bits_releaseNotSent,0,0);
        VL_OUT8(io_msInfo_14_bits_metaTag,7,0);
        VL_OUT8(io_msInfo_14_bits_dirHit,0,0);
        VL_OUT8(io_msInfo_14_bits_nestB,0,0);
        VL_OUT8(io_msInfo_14_bits_mergeB,0,0);
        VL_OUT8(io_msInfo_14_bits_isAcqOrPrefetch,0,0);
        VL_OUT8(io_msInfo_14_bits_isPrefetch,0,0);
        VL_OUT8(io_msInfo_15_valid,0,0);
        VL_OUT8(io_msInfo_15_bits_set,6,0);
        VL_OUT8(io_msInfo_15_bits_way,1,0);
        VL_OUT8(io_msInfo_15_bits_reqTag,7,0);
        VL_OUT8(io_msInfo_15_bits_willFree,0,0);
        VL_OUT8(io_msInfo_15_bits_needRelease,0,0);
        VL_OUT8(io_msInfo_15_bits_releaseNotSent,0,0);
        VL_OUT8(io_msInfo_15_bits_metaTag,7,0);
        VL_OUT8(io_msInfo_15_bits_dirHit,0,0);
        VL_OUT8(io_msInfo_15_bits_nestB,0,0);
        VL_OUT8(io_msInfo_15_bits_mergeB,0,0);
        VL_OUT8(io_msInfo_15_bits_isAcqOrPrefetch,0,0);
        VL_OUT8(io_msInfo_15_bits_isPrefetch,0,0);
        VL_IN8(io_bMergeTask_valid,0,0);
        VL_IN8(io_bMergeTask_bits_id,7,0);
        VL_IN8(io_bMergeTask_bits_task_set,6,0);
        VL_IN8(io_bMergeTask_bits_task_tag,7,0);
        VL_IN8(io_bMergeTask_bits_task_off,0,0);
        VL_IN8(io_bMergeTask_bits_task_param,2,0);
        VL_IN8(io_bMergeTask_bits_task_needProbeAckData,0,0);
        VL_IN8(io_replResp_valid,0,0);
        VL_IN8(io_replResp_bits_tag,7,0);
        VL_IN8(io_replResp_bits_way,1,0);
        VL_IN8(io_replResp_bits_meta_dirty,0,0);
        VL_IN8(io_replResp_bits_meta_state,1,0);
        VL_IN8(io_replResp_bits_meta_clients,0,0);
        VL_IN8(io_replResp_bits_meta_alias,1,0);
        VL_IN8(io_replResp_bits_meta_accessed,0,0);
        VL_IN8(io_replResp_bits_mshrId,7,0);
        VL_IN8(io_replResp_bits_retry,0,0);
        CData/*0:0*/ __PVT__mshrs_0_io_alloc_valid;
        CData/*0:0*/ __PVT__mshrs_0_io_resps_sink_c_valid;
        CData/*0:0*/ __PVT__mshrs_0_io_resps_sink_d_valid;
        CData/*0:0*/ __PVT__mshrs_0_io_bMergeTask_valid;
    };
    struct {
        CData/*0:0*/ __PVT__mshrs_0_io_replResp_valid;
        CData/*0:0*/ __PVT__mshrs_1_io_alloc_valid;
        CData/*0:0*/ __PVT__mshrs_1_io_resps_sink_c_valid;
        CData/*0:0*/ __PVT__mshrs_1_io_resps_sink_d_valid;
        CData/*0:0*/ __PVT__mshrs_1_io_bMergeTask_valid;
        CData/*0:0*/ __PVT__mshrs_1_io_replResp_valid;
        CData/*0:0*/ __PVT__mshrs_2_io_alloc_valid;
        CData/*0:0*/ __PVT__mshrs_2_io_resps_sink_c_valid;
        CData/*0:0*/ __PVT__mshrs_2_io_resps_sink_d_valid;
        CData/*0:0*/ __PVT__mshrs_2_io_bMergeTask_valid;
        CData/*0:0*/ __PVT__mshrs_2_io_replResp_valid;
        CData/*0:0*/ __PVT__mshrs_3_io_alloc_valid;
        CData/*0:0*/ __PVT__mshrs_3_io_resps_sink_c_valid;
        CData/*0:0*/ __PVT__mshrs_3_io_resps_sink_d_valid;
        CData/*0:0*/ __PVT__mshrs_3_io_bMergeTask_valid;
        CData/*0:0*/ __PVT__mshrs_3_io_replResp_valid;
        CData/*0:0*/ __PVT__mshrs_4_io_alloc_valid;
        CData/*0:0*/ __PVT__mshrs_4_io_resps_sink_c_valid;
        CData/*0:0*/ __PVT__mshrs_4_io_resps_sink_d_valid;
        CData/*0:0*/ __PVT__mshrs_4_io_bMergeTask_valid;
        CData/*0:0*/ __PVT__mshrs_4_io_replResp_valid;
        CData/*0:0*/ __PVT__mshrs_5_io_alloc_valid;
        CData/*0:0*/ __PVT__mshrs_5_io_resps_sink_c_valid;
        CData/*0:0*/ __PVT__mshrs_5_io_resps_sink_d_valid;
        CData/*0:0*/ __PVT__mshrs_5_io_bMergeTask_valid;
        CData/*0:0*/ __PVT__mshrs_5_io_replResp_valid;
        CData/*0:0*/ __PVT__mshrs_6_io_alloc_valid;
        CData/*0:0*/ __PVT__mshrs_6_io_resps_sink_c_valid;
        CData/*0:0*/ __PVT__mshrs_6_io_resps_sink_d_valid;
        CData/*0:0*/ __PVT__mshrs_6_io_bMergeTask_valid;
        CData/*0:0*/ __PVT__mshrs_6_io_replResp_valid;
        CData/*0:0*/ __PVT__mshrs_7_io_alloc_valid;
        CData/*0:0*/ __PVT__mshrs_7_io_resps_sink_c_valid;
        CData/*0:0*/ __PVT__mshrs_7_io_resps_sink_d_valid;
        CData/*0:0*/ __PVT__mshrs_7_io_bMergeTask_valid;
        CData/*0:0*/ __PVT__mshrs_7_io_replResp_valid;
        CData/*0:0*/ __PVT__mshrs_8_io_alloc_valid;
        CData/*0:0*/ __PVT__mshrs_8_io_resps_sink_c_valid;
        CData/*0:0*/ __PVT__mshrs_8_io_resps_sink_d_valid;
        CData/*0:0*/ __PVT__mshrs_8_io_bMergeTask_valid;
        CData/*0:0*/ __PVT__mshrs_8_io_replResp_valid;
        CData/*0:0*/ __PVT__mshrs_9_io_alloc_valid;
        CData/*0:0*/ __PVT__mshrs_9_io_resps_sink_c_valid;
        CData/*0:0*/ __PVT__mshrs_9_io_resps_sink_d_valid;
        CData/*0:0*/ __PVT__mshrs_9_io_bMergeTask_valid;
        CData/*0:0*/ __PVT__mshrs_9_io_replResp_valid;
        CData/*0:0*/ __PVT__mshrs_10_io_alloc_valid;
        CData/*0:0*/ __PVT__mshrs_10_io_resps_sink_c_valid;
        CData/*0:0*/ __PVT__mshrs_10_io_resps_sink_d_valid;
        CData/*0:0*/ __PVT__mshrs_10_io_bMergeTask_valid;
        CData/*0:0*/ __PVT__mshrs_10_io_replResp_valid;
        CData/*0:0*/ __PVT__mshrs_11_io_alloc_valid;
        CData/*0:0*/ __PVT__mshrs_11_io_resps_sink_c_valid;
        CData/*0:0*/ __PVT__mshrs_11_io_resps_sink_d_valid;
        CData/*0:0*/ __PVT__mshrs_11_io_bMergeTask_valid;
        CData/*0:0*/ __PVT__mshrs_11_io_replResp_valid;
        CData/*0:0*/ __PVT__mshrs_12_io_alloc_valid;
        CData/*0:0*/ __PVT__mshrs_12_io_resps_sink_c_valid;
        CData/*0:0*/ __PVT__mshrs_12_io_resps_sink_d_valid;
        CData/*0:0*/ __PVT__mshrs_12_io_bMergeTask_valid;
        CData/*0:0*/ __PVT__mshrs_12_io_replResp_valid;
        CData/*0:0*/ __PVT__mshrs_13_io_alloc_valid;
        CData/*0:0*/ __PVT__mshrs_13_io_resps_sink_c_valid;
        CData/*0:0*/ __PVT__mshrs_13_io_resps_sink_d_valid;
    };
    struct {
        CData/*0:0*/ __PVT__mshrs_13_io_bMergeTask_valid;
        CData/*0:0*/ __PVT__mshrs_13_io_replResp_valid;
        CData/*0:0*/ __PVT__mshrs_14_io_alloc_valid;
        CData/*0:0*/ __PVT__mshrs_14_io_resps_sink_c_valid;
        CData/*0:0*/ __PVT__mshrs_14_io_resps_sink_d_valid;
        CData/*0:0*/ __PVT__mshrs_14_io_bMergeTask_valid;
        CData/*0:0*/ __PVT__mshrs_14_io_replResp_valid;
        CData/*0:0*/ __PVT__mshrs_15_io_alloc_valid;
        CData/*0:0*/ __PVT__mshrs_15_io_resps_sink_c_valid;
        CData/*0:0*/ __PVT__mshrs_15_io_resps_sink_d_valid;
        CData/*0:0*/ __PVT__mshrs_15_io_bMergeTask_valid;
        CData/*0:0*/ __PVT__mshrs_15_io_replResp_valid;
        CData/*7:0*/ __PVT__source_a_arb_io_out_bits_tag;
        CData/*6:0*/ __PVT__source_a_arb_io_out_bits_set;
        CData/*1:0*/ __PVT__source_a_arb_io_out_bits_param;
        CData/*0:0*/ __PVT__sourceB_io_task_ready;
        CData/*7:0*/ __PVT__source_b_arb_io_out_bits_tag;
        CData/*6:0*/ __PVT__source_b_arb_io_out_bits_set;
        CData/*2:0*/ __PVT__source_b_arb_io_out_bits_opcode;
        CData/*1:0*/ __PVT__source_b_arb_io_out_bits_param;
        CData/*1:0*/ __PVT__source_b_arb_io_out_bits_alias;
        CData/*0:0*/ __PVT__mshr_task_arb_io_in_0_ready;
        CData/*0:0*/ __PVT__mshr_task_arb_io_in_1_ready;
        CData/*0:0*/ __PVT__mshr_task_arb_io_in_2_ready;
        CData/*0:0*/ __PVT__mshr_task_arb_io_in_3_ready;
        CData/*0:0*/ __PVT__mshr_task_arb_io_in_4_ready;
        CData/*0:0*/ __PVT__mshr_task_arb_io_in_5_ready;
        CData/*0:0*/ __PVT__mshr_task_arb_io_in_6_ready;
        CData/*0:0*/ __PVT__mshr_task_arb_io_in_7_ready;
        CData/*0:0*/ __PVT__mshr_task_arb_io_in_8_ready;
        CData/*0:0*/ __PVT__mshr_task_arb_io_in_9_ready;
        CData/*0:0*/ __PVT__mshr_task_arb_io_in_10_ready;
        CData/*0:0*/ __PVT__mshr_task_arb_io_in_11_ready;
        CData/*0:0*/ __PVT__mshr_task_arb_io_in_12_ready;
        CData/*0:0*/ __PVT__mshr_task_arb_io_in_13_ready;
        CData/*0:0*/ __PVT__mshr_task_arb_io_in_14_ready;
        CData/*0:0*/ __PVT__mshr_task_arb_io_in_15_ready;
        CData/*4:0*/ __PVT___mshrFull_T_1;
        CData/*7:0*/ __PVT___io_toMainPipe_mshr_alloc_ptr_T_1;
        CData/*3:0*/ __PVT___io_toMainPipe_mshr_alloc_ptr_T_3;
        CData/*0:0*/ __PVT__resp_sinkC_match_vec_0;
        CData/*0:0*/ __PVT__resp_sinkC_match_vec_1;
        CData/*0:0*/ __PVT__resp_sinkC_match_vec_2;
        CData/*0:0*/ __PVT__resp_sinkC_match_vec_3;
        CData/*0:0*/ __PVT__resp_sinkC_match_vec_4;
        CData/*0:0*/ __PVT__resp_sinkC_match_vec_5;
        CData/*0:0*/ __PVT__resp_sinkC_match_vec_6;
        CData/*0:0*/ __PVT__resp_sinkC_match_vec_7;
        CData/*0:0*/ __PVT__resp_sinkC_match_vec_8;
        CData/*0:0*/ __PVT__resp_sinkC_match_vec_9;
        CData/*0:0*/ __PVT__resp_sinkC_match_vec_10;
        CData/*0:0*/ __PVT__resp_sinkC_match_vec_11;
        CData/*0:0*/ __PVT__resp_sinkC_match_vec_12;
        CData/*0:0*/ __PVT__resp_sinkC_match_vec_13;
        CData/*0:0*/ __PVT__resp_sinkC_match_vec_14;
        CData/*0:0*/ __PVT__REG;
        CData/*0:0*/ mshrSelector__DOT____VdfgRegularize_h50056278_0_0;
        CData/*0:0*/ mshrSelector__DOT____VdfgRegularize_h50056278_0_1;
        CData/*0:0*/ mshrSelector__DOT____VdfgRegularize_h50056278_0_2;
        CData/*0:0*/ mshrSelector__DOT____VdfgRegularize_h50056278_0_3;
        CData/*0:0*/ __PVT__source_a_arb__DOT___pendingMask_T_2;
        CData/*0:0*/ __PVT__sourceB__DOT__issueArb_io_in_0_valid;
        CData/*0:0*/ __PVT__sourceB__DOT__issueArb_io_in_1_valid;
        CData/*0:0*/ __PVT__sourceB__DOT__issueArb_io_in_2_valid;
    };
    struct {
        CData/*0:0*/ __PVT__sourceB__DOT__issueArb_io_in_3_valid;
        CData/*0:0*/ __PVT__sourceB__DOT__probes_0_valid;
        CData/*0:0*/ __PVT__sourceB__DOT__probes_0_rdy;
        CData/*4:0*/ __PVT__sourceB__DOT__probes_0_waitG;
        CData/*7:0*/ __PVT__sourceB__DOT__probes_0_task_tag;
        CData/*6:0*/ __PVT__sourceB__DOT__probes_0_task_set;
        CData/*2:0*/ __PVT__sourceB__DOT__probes_0_task_opcode;
        CData/*1:0*/ __PVT__sourceB__DOT__probes_0_task_param;
        CData/*1:0*/ __PVT__sourceB__DOT__probes_0_task_alias;
        CData/*0:0*/ __PVT__sourceB__DOT__probes_1_valid;
        CData/*0:0*/ __PVT__sourceB__DOT__probes_1_rdy;
        CData/*4:0*/ __PVT__sourceB__DOT__probes_1_waitG;
        CData/*7:0*/ __PVT__sourceB__DOT__probes_1_task_tag;
        CData/*6:0*/ __PVT__sourceB__DOT__probes_1_task_set;
        CData/*2:0*/ __PVT__sourceB__DOT__probes_1_task_opcode;
        CData/*1:0*/ __PVT__sourceB__DOT__probes_1_task_param;
        CData/*1:0*/ __PVT__sourceB__DOT__probes_1_task_alias;
        CData/*0:0*/ __PVT__sourceB__DOT__probes_2_valid;
        CData/*0:0*/ __PVT__sourceB__DOT__probes_2_rdy;
        CData/*4:0*/ __PVT__sourceB__DOT__probes_2_waitG;
        CData/*7:0*/ __PVT__sourceB__DOT__probes_2_task_tag;
        CData/*6:0*/ __PVT__sourceB__DOT__probes_2_task_set;
        CData/*2:0*/ __PVT__sourceB__DOT__probes_2_task_opcode;
        CData/*1:0*/ __PVT__sourceB__DOT__probes_2_task_param;
        CData/*1:0*/ __PVT__sourceB__DOT__probes_2_task_alias;
        CData/*0:0*/ __PVT__sourceB__DOT__probes_3_valid;
        CData/*0:0*/ __PVT__sourceB__DOT__probes_3_rdy;
        CData/*4:0*/ __PVT__sourceB__DOT__probes_3_waitG;
        CData/*7:0*/ __PVT__sourceB__DOT__probes_3_task_tag;
        CData/*6:0*/ __PVT__sourceB__DOT__probes_3_task_set;
        CData/*2:0*/ __PVT__sourceB__DOT__probes_3_task_opcode;
        CData/*1:0*/ __PVT__sourceB__DOT__probes_3_task_param;
        CData/*1:0*/ __PVT__sourceB__DOT__probes_3_task_alias;
        CData/*0:0*/ __PVT__sourceB__DOT__conflictMask_0;
        CData/*0:0*/ __PVT__sourceB__DOT__conflictMask_1;
        CData/*0:0*/ __PVT__sourceB__DOT__conflictMask_2;
        CData/*0:0*/ __PVT__sourceB__DOT__conflictMask_3;
        CData/*0:0*/ __PVT__sourceB__DOT__conflictMask_4;
        CData/*0:0*/ __PVT__sourceB__DOT__conflictMask_5;
        CData/*0:0*/ __PVT__sourceB__DOT__conflictMask_6;
        CData/*0:0*/ __PVT__sourceB__DOT__conflictMask_7;
        CData/*0:0*/ __PVT__sourceB__DOT__conflictMask_8;
        CData/*0:0*/ __PVT__sourceB__DOT__conflictMask_9;
        CData/*0:0*/ __PVT__sourceB__DOT__conflictMask_10;
        CData/*0:0*/ __PVT__sourceB__DOT__conflictMask_11;
        CData/*0:0*/ __PVT__sourceB__DOT__conflictMask_12;
        CData/*0:0*/ __PVT__sourceB__DOT__conflictMask_13;
        CData/*0:0*/ __PVT__sourceB__DOT__conflictMask_14;
        CData/*0:0*/ __PVT__sourceB__DOT__conflictMask_15;
        CData/*1:0*/ __PVT__sourceB__DOT__insertIdx;
        CData/*0:0*/ __PVT__sourceB__DOT__alloc;
        CData/*0:0*/ __PVT__sourceB__DOT___GEN_0;
        CData/*0:0*/ __PVT__sourceB__DOT___GEN_1;
        CData/*0:0*/ __PVT__sourceB__DOT___GEN_2;
        CData/*0:0*/ __PVT__sourceB__DOT___GEN_3;
        CData/*4:0*/ __PVT__sourceB__DOT___probes_insertIdx_waitG;
        CData/*0:0*/ __PVT__sourceB__DOT___GEN_92;
        CData/*0:0*/ __PVT__sourceB__DOT___GEN_109;
        CData/*0:0*/ __PVT__sourceB__DOT___GEN_126;
        CData/*0:0*/ __PVT__sourceB__DOT___GEN_143;
        CData/*3:0*/ __PVT__sourceB__DOT__issueArb__DOT__valids;
        CData/*3:0*/ __PVT__sourceB__DOT__issueArb__DOT__rrGrantMask;
        CData/*3:0*/ __PVT__sourceB__DOT__issueArb__DOT__pendingMask;
        CData/*3:0*/ __PVT__sourceB__DOT__issueArb__DOT__chosenOH;
    };
    struct {
        CData/*0:0*/ __PVT__sourceB__DOT__issueArb__DOT___pendingMask_T_2;
        CData/*0:0*/ __PVT__mshr_task_arb__DOT___pendingMask_T_2;
        VL_OUT16(io_sourceA_bits_address,15,0);
        VL_OUT16(io_sourceB_bits_address,15,0);
        SData/*15:0*/ __PVT__mshrSelector_io_out_bits;
        SData/*15:0*/ __PVT__source_a_arb__DOT__valids;
        SData/*15:0*/ __PVT__source_a_arb__DOT__rrGrantMask;
        SData/*15:0*/ __PVT__source_a_arb__DOT__pendingMask;
        SData/*15:0*/ __PVT__source_a_arb__DOT__chosenOH;
        SData/*15:0*/ __PVT__source_b_arb__DOT__valids;
        SData/*15:0*/ __PVT__source_b_arb__DOT__rrGrantMask;
        SData/*15:0*/ __PVT__source_b_arb__DOT__pendingMask;
        SData/*15:0*/ __PVT__source_b_arb__DOT__rrSelOH;
        SData/*15:0*/ __PVT__source_b_arb__DOT__chosenOH;
        SData/*15:0*/ __PVT__mshr_task_arb__DOT__valids;
        SData/*15:0*/ __PVT__mshr_task_arb__DOT__rrGrantMask;
        SData/*15:0*/ __PVT__mshr_task_arb__DOT__pendingMask;
        SData/*15:0*/ __PVT__mshr_task_arb__DOT__rrSelOH;
        SData/*15:0*/ __PVT__mshr_task_arb__DOT__chosenOH;
    };

    // INTERNAL VARIABLES
    VTestTop_L2L3L2__Syms* const vlSymsp;

    // CONSTRUCTORS
    VTestTop_L2L3L2_MSHRCtl(VTestTop_L2L3L2__Syms* symsp, const char* v__name);
    ~VTestTop_L2L3L2_MSHRCtl();
    VL_UNCOPYABLE(VTestTop_L2L3L2_MSHRCtl);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
