// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See VTestTop_L2L3L2.h for the primary calling header

#ifndef VERILATED_VTESTTOP_L2L3L2_GRANTBUFFERFIFO_H_
#define VERILATED_VTESTTOP_L2L3L2_GRANTBUFFERFIFO_H_  // guard

#include "verilated.h"


class VTestTop_L2L3L2__Syms;

class alignas(VL_CACHE_LINE_BYTES) VTestTop_L2L3L2_GrantBufferFIFO final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clock,0,0);
        VL_IN8(reset,0,0);
        VL_OUT8(io_d_task_ready,0,0);
        VL_IN8(io_d_task_valid,0,0);
        VL_IN8(io_d_task_bits_task_set,6,0);
        VL_IN8(io_d_task_bits_task_tag,7,0);
        VL_IN8(io_d_task_bits_task_opcode,2,0);
        VL_IN8(io_d_task_bits_task_param,2,0);
        VL_IN8(io_d_task_bits_task_sourceId,4,0);
        VL_IN8(io_d_task_bits_task_mshrId,7,0);
        VL_IN8(io_d_ready,0,0);
        VL_OUT8(io_d_valid,0,0);
        VL_OUT8(io_d_bits_opcode,2,0);
        VL_OUT8(io_d_bits_param,1,0);
        VL_OUT8(io_d_bits_size,0,0);
        VL_OUT8(io_d_bits_source,4,0);
        VL_OUT8(io_d_bits_sink,7,0);
        VL_OUT8(io_d_bits_data,7,0);
        VL_OUT8(__PVT__io_e_ready,0,0);
        VL_IN8(io_e_valid,0,0);
        VL_IN8(io_e_bits_sink,7,0);
        VL_OUT8(io_e_resp_valid,0,0);
        VL_OUT8(io_e_resp_mshrId,7,0);
        VL_IN8(io_fromReqArb_status_s1_tags_1,7,0);
        VL_IN8(io_fromReqArb_status_s1_sets_1,6,0);
        VL_IN8(io_pipeStatusVec_0_valid,0,0);
        VL_IN8(io_pipeStatusVec_0_bits_channel,2,0);
        VL_IN8(io_pipeStatusVec_1_valid,0,0);
        VL_IN8(io_pipeStatusVec_1_bits_channel,2,0);
        VL_IN8(io_pipeStatusVec_2_valid,0,0);
        VL_IN8(io_pipeStatusVec_2_bits_channel,2,0);
        VL_IN8(io_pipeStatusVec_3_valid,0,0);
        VL_IN8(io_pipeStatusVec_3_bits_channel,2,0);
        VL_IN8(io_pipeStatusVec_4_valid,0,0);
        VL_IN8(io_pipeStatusVec_4_bits_channel,2,0);
        VL_OUT8(io_toReqArb_blockSinkReqEntrance_blockA_s1,0,0);
        VL_OUT8(io_toReqArb_blockSinkReqEntrance_blockB_s1,0,0);
        VL_OUT8(io_toReqArb_blockSinkReqEntrance_blockC_s1,0,0);
        VL_OUT8(io_toReqArb_blockMSHRReqEntrance,0,0);
        VL_OUT8(io_grantStatus_0_valid,0,0);
        VL_OUT8(io_grantStatus_0_set,6,0);
        VL_OUT8(io_grantStatus_0_tag,7,0);
        VL_OUT8(io_grantStatus_1_valid,0,0);
        VL_OUT8(io_grantStatus_1_set,6,0);
        VL_OUT8(io_grantStatus_1_tag,7,0);
        VL_OUT8(io_grantStatus_2_valid,0,0);
        VL_OUT8(io_grantStatus_2_set,6,0);
        VL_OUT8(io_grantStatus_2_tag,7,0);
        VL_OUT8(io_grantStatus_3_valid,0,0);
        VL_OUT8(io_grantStatus_3_set,6,0);
        VL_OUT8(io_grantStatus_3_tag,7,0);
        VL_OUT8(io_grantStatus_4_valid,0,0);
        VL_OUT8(io_grantStatus_4_set,6,0);
        VL_OUT8(io_grantStatus_4_tag,7,0);
        VL_OUT8(io_grantStatus_5_valid,0,0);
        VL_OUT8(io_grantStatus_5_set,6,0);
        VL_OUT8(io_grantStatus_5_tag,7,0);
        VL_OUT8(io_grantStatus_6_valid,0,0);
        VL_OUT8(io_grantStatus_6_set,6,0);
        VL_OUT8(io_grantStatus_6_tag,7,0);
        VL_OUT8(io_grantStatus_7_valid,0,0);
        VL_OUT8(io_grantStatus_7_set,6,0);
        VL_OUT8(io_grantStatus_7_tag,7,0);
        VL_OUT8(io_grantStatus_8_valid,0,0);
    };
    struct {
        VL_OUT8(io_grantStatus_8_set,6,0);
        VL_OUT8(io_grantStatus_8_tag,7,0);
        VL_OUT8(io_grantStatus_9_valid,0,0);
        VL_OUT8(io_grantStatus_9_set,6,0);
        VL_OUT8(io_grantStatus_9_tag,7,0);
        VL_OUT8(io_grantStatus_10_valid,0,0);
        VL_OUT8(io_grantStatus_10_set,6,0);
        VL_OUT8(io_grantStatus_10_tag,7,0);
        VL_OUT8(io_grantStatus_11_valid,0,0);
        VL_OUT8(io_grantStatus_11_set,6,0);
        VL_OUT8(io_grantStatus_11_tag,7,0);
        VL_OUT8(io_grantStatus_12_valid,0,0);
        VL_OUT8(io_grantStatus_12_set,6,0);
        VL_OUT8(io_grantStatus_12_tag,7,0);
        VL_OUT8(io_grantStatus_13_valid,0,0);
        VL_OUT8(io_grantStatus_13_set,6,0);
        VL_OUT8(io_grantStatus_13_tag,7,0);
        VL_OUT8(io_grantStatus_14_valid,0,0);
        VL_OUT8(io_grantStatus_14_set,6,0);
        VL_OUT8(io_grantStatus_14_tag,7,0);
        VL_OUT8(io_grantStatus_15_valid,0,0);
        VL_OUT8(io_grantStatus_15_set,6,0);
        VL_OUT8(io_grantStatus_15_tag,7,0);
        CData/*0:0*/ __PVT__beat_valids_0_0;
        CData/*0:0*/ __PVT__beat_valids_0_1;
        CData/*0:0*/ __PVT__beat_valids_1_0;
        CData/*0:0*/ __PVT__beat_valids_1_1;
        CData/*0:0*/ __PVT__beat_valids_2_0;
        CData/*0:0*/ __PVT__beat_valids_2_1;
        CData/*0:0*/ __PVT__beat_valids_3_0;
        CData/*0:0*/ __PVT__beat_valids_3_1;
        CData/*0:0*/ __PVT__beat_valids_4_0;
        CData/*0:0*/ __PVT__beat_valids_4_1;
        CData/*0:0*/ __PVT__beat_valids_5_0;
        CData/*0:0*/ __PVT__beat_valids_5_1;
        CData/*0:0*/ __PVT__beat_valids_6_0;
        CData/*0:0*/ __PVT__beat_valids_6_1;
        CData/*0:0*/ __PVT__beat_valids_7_0;
        CData/*0:0*/ __PVT__beat_valids_7_1;
        CData/*0:0*/ __PVT__beat_valids_8_0;
        CData/*0:0*/ __PVT__beat_valids_8_1;
        CData/*0:0*/ __PVT__beat_valids_9_0;
        CData/*0:0*/ __PVT__beat_valids_9_1;
        CData/*0:0*/ __PVT__beat_valids_10_0;
        CData/*0:0*/ __PVT__beat_valids_10_1;
        CData/*0:0*/ __PVT__beat_valids_11_0;
        CData/*0:0*/ __PVT__beat_valids_11_1;
        CData/*0:0*/ __PVT__beat_valids_12_0;
        CData/*0:0*/ __PVT__beat_valids_12_1;
        CData/*0:0*/ __PVT__beat_valids_13_0;
        CData/*0:0*/ __PVT__beat_valids_13_1;
        CData/*0:0*/ __PVT__beat_valids_14_0;
        CData/*0:0*/ __PVT__beat_valids_14_1;
        CData/*0:0*/ __PVT__beat_valids_15_0;
        CData/*0:0*/ __PVT__beat_valids_15_1;
        CData/*1:0*/ __PVT___block_valids_T_30;
        CData/*2:0*/ __PVT__taskAll_0_opcode;
        CData/*2:0*/ __PVT__taskAll_0_param;
        CData/*4:0*/ __PVT__taskAll_0_sourceId;
        CData/*7:0*/ __PVT__taskAll_0_mshrId;
        CData/*2:0*/ __PVT__taskAll_1_opcode;
        CData/*2:0*/ __PVT__taskAll_1_param;
        CData/*4:0*/ __PVT__taskAll_1_sourceId;
        CData/*7:0*/ __PVT__taskAll_1_mshrId;
    };
    struct {
        CData/*2:0*/ __PVT__taskAll_2_opcode;
        CData/*2:0*/ __PVT__taskAll_2_param;
        CData/*4:0*/ __PVT__taskAll_2_sourceId;
        CData/*7:0*/ __PVT__taskAll_2_mshrId;
        CData/*2:0*/ __PVT__taskAll_3_opcode;
        CData/*2:0*/ __PVT__taskAll_3_param;
        CData/*4:0*/ __PVT__taskAll_3_sourceId;
        CData/*7:0*/ __PVT__taskAll_3_mshrId;
        CData/*2:0*/ __PVT__taskAll_4_opcode;
        CData/*2:0*/ __PVT__taskAll_4_param;
        CData/*4:0*/ __PVT__taskAll_4_sourceId;
        CData/*7:0*/ __PVT__taskAll_4_mshrId;
        CData/*2:0*/ __PVT__taskAll_5_opcode;
        CData/*2:0*/ __PVT__taskAll_5_param;
        CData/*4:0*/ __PVT__taskAll_5_sourceId;
        CData/*7:0*/ __PVT__taskAll_5_mshrId;
        CData/*2:0*/ __PVT__taskAll_6_opcode;
        CData/*2:0*/ __PVT__taskAll_6_param;
        CData/*4:0*/ __PVT__taskAll_6_sourceId;
        CData/*7:0*/ __PVT__taskAll_6_mshrId;
        CData/*2:0*/ __PVT__taskAll_7_opcode;
        CData/*2:0*/ __PVT__taskAll_7_param;
        CData/*4:0*/ __PVT__taskAll_7_sourceId;
        CData/*7:0*/ __PVT__taskAll_7_mshrId;
        CData/*2:0*/ __PVT__taskAll_8_opcode;
        CData/*2:0*/ __PVT__taskAll_8_param;
        CData/*4:0*/ __PVT__taskAll_8_sourceId;
        CData/*7:0*/ __PVT__taskAll_8_mshrId;
        CData/*2:0*/ __PVT__taskAll_9_opcode;
        CData/*2:0*/ __PVT__taskAll_9_param;
        CData/*4:0*/ __PVT__taskAll_9_sourceId;
        CData/*7:0*/ __PVT__taskAll_9_mshrId;
        CData/*2:0*/ __PVT__taskAll_10_opcode;
        CData/*2:0*/ __PVT__taskAll_10_param;
        CData/*4:0*/ __PVT__taskAll_10_sourceId;
        CData/*7:0*/ __PVT__taskAll_10_mshrId;
        CData/*2:0*/ __PVT__taskAll_11_opcode;
        CData/*2:0*/ __PVT__taskAll_11_param;
        CData/*4:0*/ __PVT__taskAll_11_sourceId;
        CData/*7:0*/ __PVT__taskAll_11_mshrId;
        CData/*2:0*/ __PVT__taskAll_12_opcode;
        CData/*2:0*/ __PVT__taskAll_12_param;
        CData/*4:0*/ __PVT__taskAll_12_sourceId;
        CData/*7:0*/ __PVT__taskAll_12_mshrId;
        CData/*2:0*/ __PVT__taskAll_13_opcode;
        CData/*2:0*/ __PVT__taskAll_13_param;
        CData/*4:0*/ __PVT__taskAll_13_sourceId;
        CData/*7:0*/ __PVT__taskAll_13_mshrId;
        CData/*2:0*/ __PVT__taskAll_14_opcode;
        CData/*2:0*/ __PVT__taskAll_14_param;
        CData/*4:0*/ __PVT__taskAll_14_sourceId;
        CData/*7:0*/ __PVT__taskAll_14_mshrId;
        CData/*2:0*/ __PVT__taskAll_15_opcode;
        CData/*2:0*/ __PVT__taskAll_15_param;
        CData/*4:0*/ __PVT__taskAll_15_sourceId;
        CData/*7:0*/ __PVT__taskAll_15_mshrId;
        CData/*0:0*/ __PVT__inflight_grant_0_valid;
        CData/*6:0*/ __PVT__inflight_grant_0_bits_set;
        CData/*7:0*/ __PVT__inflight_grant_0_bits_tag;
        CData/*7:0*/ __PVT__inflight_grant_0_bits_sink;
        CData/*0:0*/ __PVT__inflight_grant_1_valid;
        CData/*6:0*/ __PVT__inflight_grant_1_bits_set;
        CData/*7:0*/ __PVT__inflight_grant_1_bits_tag;
        CData/*7:0*/ __PVT__inflight_grant_1_bits_sink;
    };
    struct {
        CData/*0:0*/ __PVT__inflight_grant_2_valid;
        CData/*6:0*/ __PVT__inflight_grant_2_bits_set;
        CData/*7:0*/ __PVT__inflight_grant_2_bits_tag;
        CData/*7:0*/ __PVT__inflight_grant_2_bits_sink;
        CData/*0:0*/ __PVT__inflight_grant_3_valid;
        CData/*6:0*/ __PVT__inflight_grant_3_bits_set;
        CData/*7:0*/ __PVT__inflight_grant_3_bits_tag;
        CData/*7:0*/ __PVT__inflight_grant_3_bits_sink;
        CData/*0:0*/ __PVT__inflight_grant_4_valid;
        CData/*6:0*/ __PVT__inflight_grant_4_bits_set;
        CData/*7:0*/ __PVT__inflight_grant_4_bits_tag;
        CData/*7:0*/ __PVT__inflight_grant_4_bits_sink;
        CData/*0:0*/ __PVT__inflight_grant_5_valid;
        CData/*6:0*/ __PVT__inflight_grant_5_bits_set;
        CData/*7:0*/ __PVT__inflight_grant_5_bits_tag;
        CData/*7:0*/ __PVT__inflight_grant_5_bits_sink;
        CData/*0:0*/ __PVT__inflight_grant_6_valid;
        CData/*6:0*/ __PVT__inflight_grant_6_bits_set;
        CData/*7:0*/ __PVT__inflight_grant_6_bits_tag;
        CData/*7:0*/ __PVT__inflight_grant_6_bits_sink;
        CData/*0:0*/ __PVT__inflight_grant_7_valid;
        CData/*6:0*/ __PVT__inflight_grant_7_bits_set;
        CData/*7:0*/ __PVT__inflight_grant_7_bits_tag;
        CData/*7:0*/ __PVT__inflight_grant_7_bits_sink;
        CData/*0:0*/ __PVT__inflight_grant_8_valid;
        CData/*6:0*/ __PVT__inflight_grant_8_bits_set;
        CData/*7:0*/ __PVT__inflight_grant_8_bits_tag;
        CData/*7:0*/ __PVT__inflight_grant_8_bits_sink;
        CData/*0:0*/ __PVT__inflight_grant_9_valid;
        CData/*6:0*/ __PVT__inflight_grant_9_bits_set;
        CData/*7:0*/ __PVT__inflight_grant_9_bits_tag;
        CData/*7:0*/ __PVT__inflight_grant_9_bits_sink;
        CData/*0:0*/ __PVT__inflight_grant_10_valid;
        CData/*6:0*/ __PVT__inflight_grant_10_bits_set;
        CData/*7:0*/ __PVT__inflight_grant_10_bits_tag;
        CData/*7:0*/ __PVT__inflight_grant_10_bits_sink;
        CData/*0:0*/ __PVT__inflight_grant_11_valid;
        CData/*6:0*/ __PVT__inflight_grant_11_bits_set;
        CData/*7:0*/ __PVT__inflight_grant_11_bits_tag;
        CData/*7:0*/ __PVT__inflight_grant_11_bits_sink;
        CData/*0:0*/ __PVT__inflight_grant_12_valid;
        CData/*6:0*/ __PVT__inflight_grant_12_bits_set;
        CData/*7:0*/ __PVT__inflight_grant_12_bits_tag;
        CData/*7:0*/ __PVT__inflight_grant_12_bits_sink;
        CData/*0:0*/ __PVT__inflight_grant_13_valid;
        CData/*6:0*/ __PVT__inflight_grant_13_bits_set;
        CData/*7:0*/ __PVT__inflight_grant_13_bits_tag;
        CData/*7:0*/ __PVT__inflight_grant_13_bits_sink;
        CData/*0:0*/ __PVT__inflight_grant_14_valid;
        CData/*6:0*/ __PVT__inflight_grant_14_bits_set;
        CData/*7:0*/ __PVT__inflight_grant_14_bits_tag;
        CData/*7:0*/ __PVT__inflight_grant_14_bits_sink;
        CData/*0:0*/ __PVT__inflight_grant_15_valid;
        CData/*6:0*/ __PVT__inflight_grant_15_bits_set;
        CData/*7:0*/ __PVT__inflight_grant_15_bits_tag;
        CData/*7:0*/ __PVT__inflight_grant_15_bits_sink;
        CData/*0:0*/ __PVT___T_12;
        CData/*3:0*/ __PVT__insertIdx;
        CData/*0:0*/ __PVT___GEN_64;
        CData/*0:0*/ __PVT___GEN_65;
        CData/*0:0*/ __PVT___GEN_66;
        CData/*0:0*/ __PVT___GEN_67;
        CData/*0:0*/ __PVT___GEN_68;
        CData/*0:0*/ __PVT___GEN_69;
    };
    struct {
        CData/*0:0*/ __PVT___GEN_70;
        CData/*0:0*/ __PVT___GEN_71;
        CData/*0:0*/ __PVT___GEN_72;
        CData/*0:0*/ __PVT___GEN_73;
        CData/*0:0*/ __PVT___GEN_74;
        CData/*0:0*/ __PVT___GEN_75;
        CData/*0:0*/ __PVT___GEN_76;
        CData/*0:0*/ __PVT___GEN_77;
        CData/*0:0*/ __PVT___GEN_78;
        CData/*0:0*/ __PVT___GEN_79;
        CData/*3:0*/ __PVT__bufIdx;
        CData/*0:0*/ __PVT__REG;
        CData/*0:0*/ __PVT__REG_1;
        CData/*0:0*/ __PVT__REG_2;
        CData/*0:0*/ __PVT__REG_3;
        CData/*0:0*/ __PVT__REG_4;
        CData/*0:0*/ __PVT__REG_5;
        CData/*0:0*/ __PVT__REG_6;
        CData/*0:0*/ __PVT__REG_7;
        CData/*0:0*/ __PVT__REG_8;
        CData/*0:0*/ __PVT__REG_9;
        CData/*0:0*/ __PVT__REG_10;
        CData/*0:0*/ __PVT__REG_11;
        CData/*0:0*/ __PVT__REG_12;
        CData/*0:0*/ __PVT__REG_13;
        CData/*0:0*/ __PVT__REG_14;
        CData/*0:0*/ __PVT__REG_15;
        CData/*0:0*/ __PVT__enqPtrExt_flag;
        CData/*3:0*/ __PVT__enqPtrExt_value;
        CData/*0:0*/ __PVT__deqPtrExt_flag;
        CData/*3:0*/ __PVT__deqPtrExt_value;
        CData/*4:0*/ __PVT__globalCounter;
        CData/*4:0*/ __PVT__beat_counters_0;
        CData/*4:0*/ __PVT__beat_counters_1;
        CData/*4:0*/ __PVT__beat_counters_2;
        CData/*4:0*/ __PVT__beat_counters_3;
        CData/*4:0*/ __PVT__beat_counters_4;
        CData/*4:0*/ __PVT__beat_counters_5;
        CData/*4:0*/ __PVT__beat_counters_6;
        CData/*4:0*/ __PVT__beat_counters_7;
        CData/*4:0*/ __PVT__beat_counters_8;
        CData/*4:0*/ __PVT__beat_counters_9;
        CData/*4:0*/ __PVT__beat_counters_10;
        CData/*4:0*/ __PVT__beat_counters_11;
        CData/*4:0*/ __PVT__beat_counters_12;
        CData/*4:0*/ __PVT__beat_counters_13;
        CData/*4:0*/ __PVT__beat_counters_14;
        CData/*4:0*/ __PVT__beat_counters_15;
        CData/*4:0*/ __PVT___globalCounter_T_1;
        CData/*4:0*/ __PVT___globalCounter_T_4;
        CData/*4:0*/ __PVT___T_790;
        CData/*4:0*/ __PVT___beat_counters_0_T_3;
        CData/*4:0*/ __PVT___beat_counters_1_T_3;
        CData/*4:0*/ __PVT___beat_counters_2_T_3;
        CData/*4:0*/ __PVT___beat_counters_3_T_3;
        CData/*4:0*/ __PVT___beat_counters_4_T_3;
        CData/*4:0*/ __PVT___beat_counters_5_T_3;
        CData/*4:0*/ __PVT___beat_counters_6_T_3;
        CData/*4:0*/ __PVT___beat_counters_7_T_3;
        CData/*4:0*/ __PVT___beat_counters_8_T_3;
        CData/*4:0*/ __PVT___beat_counters_9_T_3;
        CData/*4:0*/ __PVT___beat_counters_10_T_3;
        CData/*4:0*/ __PVT___beat_counters_11_T_3;
        CData/*4:0*/ __PVT___beat_counters_12_T_3;
    };
    struct {
        CData/*4:0*/ __PVT___beat_counters_13_T_3;
        CData/*4:0*/ __PVT___beat_counters_14_T_3;
        CData/*4:0*/ __PVT___beat_counters_15_T_3;
        CData/*4:0*/ __PVT___enqPtrExt_new_ptr_T_2;
        CData/*0:0*/ __PVT___GEN_1090;
        CData/*0:0*/ __PVT___GEN_1091;
        CData/*0:0*/ __PVT___GEN_1092;
        CData/*0:0*/ __PVT___GEN_1093;
        CData/*0:0*/ __PVT___GEN_1094;
        CData/*0:0*/ __PVT___GEN_1095;
        CData/*0:0*/ __PVT___GEN_1096;
        CData/*0:0*/ __PVT___GEN_1097;
        CData/*0:0*/ __PVT___GEN_1098;
        CData/*0:0*/ __PVT___GEN_1099;
        CData/*0:0*/ __PVT___GEN_1100;
        CData/*0:0*/ __PVT___GEN_1101;
        CData/*0:0*/ __PVT___GEN_1102;
        CData/*0:0*/ __PVT___GEN_1103;
        CData/*0:0*/ __PVT___GEN_1104;
        CData/*0:0*/ __PVT___GEN_1105;
        CData/*0:0*/ __PVT___GEN_1106;
        CData/*0:0*/ __PVT___GEN_1107;
        CData/*0:0*/ __PVT___GEN_1108;
        CData/*0:0*/ __PVT___GEN_1109;
        CData/*0:0*/ __PVT___GEN_1110;
        CData/*0:0*/ __PVT___GEN_1111;
        CData/*0:0*/ __PVT___GEN_1112;
        CData/*0:0*/ __PVT___GEN_1113;
        CData/*0:0*/ __PVT___GEN_1114;
        CData/*0:0*/ __PVT___GEN_1115;
        CData/*0:0*/ __PVT___GEN_1116;
        CData/*0:0*/ __PVT___GEN_1117;
        CData/*0:0*/ __PVT___GEN_1118;
        CData/*0:0*/ __PVT___GEN_1119;
        CData/*0:0*/ __PVT___GEN_1120;
        CData/*0:0*/ __PVT___GEN_1121;
        CData/*1:0*/ __PVT__next_beatsOH;
        CData/*0:0*/ __PVT___T_803;
        CData/*4:0*/ __PVT___deqPtrExt_new_ptr_T_2;
        CData/*1:0*/ __PVT__next_beatsOH_1;
        CData/*1:0*/ __PVT__next_beatsOH_2;
        CData/*1:0*/ __PVT__next_beatsOH_3;
        CData/*1:0*/ __PVT__next_beatsOH_4;
        CData/*1:0*/ __PVT__next_beatsOH_5;
        CData/*1:0*/ __PVT__next_beatsOH_6;
        CData/*1:0*/ __PVT__next_beatsOH_7;
        CData/*1:0*/ __PVT__next_beatsOH_8;
        CData/*1:0*/ __PVT__next_beatsOH_9;
        CData/*1:0*/ __PVT__next_beatsOH_10;
        CData/*1:0*/ __PVT__next_beatsOH_11;
        CData/*1:0*/ __PVT__next_beatsOH_12;
        CData/*1:0*/ __PVT__next_beatsOH_13;
        CData/*1:0*/ __PVT__next_beatsOH_14;
        CData/*3:0*/ __PVT___GEN_1947;
        CData/*0:0*/ __PVT___GEN_1948;
        CData/*1:0*/ __PVT__next_beatsOH_15;
        CData/*4:0*/ __VdfgRegularize_ha337dbbd_1_72;
        CData/*3:0*/ __VdfgRegularize_ha337dbbd_1_73;
        VL_IN16(io_d_task_bits_data_data,15,0);
        SData/*15:0*/ __PVT__dataAll_0_data;
        SData/*15:0*/ __PVT__dataAll_1_data;
        SData/*15:0*/ __PVT__dataAll_2_data;
        SData/*15:0*/ __PVT__dataAll_3_data;
        SData/*15:0*/ __PVT__dataAll_4_data;
    };
    struct {
        SData/*15:0*/ __PVT__dataAll_5_data;
        SData/*15:0*/ __PVT__dataAll_6_data;
        SData/*15:0*/ __PVT__dataAll_7_data;
        SData/*15:0*/ __PVT__dataAll_8_data;
        SData/*15:0*/ __PVT__dataAll_9_data;
        SData/*15:0*/ __PVT__dataAll_10_data;
        SData/*15:0*/ __PVT__dataAll_11_data;
        SData/*15:0*/ __PVT__dataAll_12_data;
        SData/*15:0*/ __PVT__dataAll_13_data;
        SData/*15:0*/ __PVT__dataAll_14_data;
        SData/*15:0*/ __PVT__dataAll_15_data;
        QData/*63:0*/ __PVT__timers_0;
        QData/*63:0*/ __PVT__timers_1;
        QData/*63:0*/ __PVT__timers_2;
        QData/*63:0*/ __PVT__timers_3;
        QData/*63:0*/ __PVT__timers_4;
        QData/*63:0*/ __PVT__timers_5;
        QData/*63:0*/ __PVT__timers_6;
        QData/*63:0*/ __PVT__timers_7;
        QData/*63:0*/ __PVT__timers_8;
        QData/*63:0*/ __PVT__timers_9;
        QData/*63:0*/ __PVT__timers_10;
        QData/*63:0*/ __PVT__timers_11;
        QData/*63:0*/ __PVT__timers_12;
        QData/*63:0*/ __PVT__timers_13;
        QData/*63:0*/ __PVT__timers_14;
        QData/*63:0*/ __PVT__timers_15;
        QData/*63:0*/ __PVT___timers_0_T_1;
        QData/*63:0*/ __PVT___timers_1_T_1;
        QData/*63:0*/ __PVT___timers_2_T_1;
        QData/*63:0*/ __PVT___timers_3_T_1;
        QData/*63:0*/ __PVT___timers_4_T_1;
        QData/*63:0*/ __PVT___timers_5_T_1;
        QData/*63:0*/ __PVT___timers_6_T_1;
        QData/*63:0*/ __PVT___timers_7_T_1;
        QData/*63:0*/ __PVT___timers_8_T_1;
        QData/*63:0*/ __PVT___timers_9_T_1;
        QData/*63:0*/ __PVT___timers_10_T_1;
        QData/*63:0*/ __PVT___timers_11_T_1;
        QData/*63:0*/ __PVT___timers_12_T_1;
        QData/*63:0*/ __PVT___timers_13_T_1;
        QData/*63:0*/ __PVT___timers_14_T_1;
        QData/*63:0*/ __PVT___timers_15_T_1;
    };

    // INTERNAL VARIABLES
    VTestTop_L2L3L2__Syms* const vlSymsp;

    // CONSTRUCTORS
    VTestTop_L2L3L2_GrantBufferFIFO(VTestTop_L2L3L2__Syms* symsp, const char* v__name);
    ~VTestTop_L2L3L2_GrantBufferFIFO();
    VL_UNCOPYABLE(VTestTop_L2L3L2_GrantBufferFIFO);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
