// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design implementation internals
// See VTestTop_L2L3L2.h for the primary calling header

#include "VTestTop_L2L3L2__pch.h"
#include "VTestTop_L2L3L2_RequestBuffer.h"

VL_ATTR_COLD void VTestTop_L2L3L2_RequestBuffer___ctor_var_reset(VTestTop_L2L3L2_RequestBuffer* vlSelf) {
    (void)vlSelf;  // Prevent unused variable warning
    VTestTop_L2L3L2__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+            VTestTop_L2L3L2_RequestBuffer___ctor_var_reset\n"); );
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    vlSelf->clock = VL_RAND_RESET_I(1);
    vlSelf->reset = VL_RAND_RESET_I(1);
    vlSelf->io_in_ready = VL_RAND_RESET_I(1);
    vlSelf->io_in_valid = VL_RAND_RESET_I(1);
    vlSelf->io_in_bits_set = VL_RAND_RESET_I(7);
    vlSelf->io_in_bits_tag = VL_RAND_RESET_I(8);
    vlSelf->io_in_bits_off = VL_RAND_RESET_I(1);
    vlSelf->io_in_bits_alias = VL_RAND_RESET_I(2);
    vlSelf->io_in_bits_opcode = VL_RAND_RESET_I(3);
    vlSelf->io_in_bits_param = VL_RAND_RESET_I(3);
    vlSelf->io_in_bits_size = VL_RAND_RESET_I(1);
    vlSelf->io_in_bits_sourceId = VL_RAND_RESET_I(5);
    vlSelf->io_out_ready = VL_RAND_RESET_I(1);
    vlSelf->io_out_valid = VL_RAND_RESET_I(1);
    vlSelf->io_out_bits_channel = VL_RAND_RESET_I(3);
    vlSelf->io_out_bits_set = VL_RAND_RESET_I(7);
    vlSelf->io_out_bits_tag = VL_RAND_RESET_I(8);
    vlSelf->io_out_bits_off = VL_RAND_RESET_I(1);
    vlSelf->io_out_bits_alias = VL_RAND_RESET_I(2);
    vlSelf->io_out_bits_opcode = VL_RAND_RESET_I(3);
    vlSelf->io_out_bits_param = VL_RAND_RESET_I(3);
    vlSelf->io_out_bits_size = VL_RAND_RESET_I(1);
    vlSelf->io_out_bits_sourceId = VL_RAND_RESET_I(5);
    vlSelf->io_out_bits_bufIdx = VL_RAND_RESET_I(2);
    vlSelf->io_out_bits_needProbeAckData = VL_RAND_RESET_I(1);
    vlSelf->io_out_bits_mshrTask = VL_RAND_RESET_I(1);
    vlSelf->io_out_bits_mshrId = VL_RAND_RESET_I(8);
    vlSelf->io_out_bits_aliasTask = VL_RAND_RESET_I(1);
    vlSelf->io_out_bits_useProbeData = VL_RAND_RESET_I(1);
    vlSelf->io_out_bits_dirty = VL_RAND_RESET_I(1);
    vlSelf->io_out_bits_way = VL_RAND_RESET_I(2);
    vlSelf->io_out_bits_meta_dirty = VL_RAND_RESET_I(1);
    vlSelf->io_out_bits_meta_state = VL_RAND_RESET_I(2);
    vlSelf->io_out_bits_meta_clients = VL_RAND_RESET_I(1);
    vlSelf->io_out_bits_meta_alias = VL_RAND_RESET_I(2);
    vlSelf->io_out_bits_meta_accessed = VL_RAND_RESET_I(1);
    vlSelf->io_out_bits_metaWen = VL_RAND_RESET_I(1);
    vlSelf->io_out_bits_tagWen = VL_RAND_RESET_I(1);
    vlSelf->io_out_bits_dsWen = VL_RAND_RESET_I(1);
    vlSelf->io_out_bits_replTask = VL_RAND_RESET_I(1);
    vlSelf->io_out_bits_reqSource = VL_RAND_RESET_I(4);
    vlSelf->io_mshrInfo_0_valid = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_0_bits_set = VL_RAND_RESET_I(7);
    vlSelf->io_mshrInfo_0_bits_reqTag = VL_RAND_RESET_I(8);
    vlSelf->io_mshrInfo_0_bits_willFree = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_0_bits_needRelease = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_0_bits_metaTag = VL_RAND_RESET_I(8);
    vlSelf->io_mshrInfo_0_bits_isAcqOrPrefetch = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_0_bits_isPrefetch = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_1_valid = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_1_bits_set = VL_RAND_RESET_I(7);
    vlSelf->io_mshrInfo_1_bits_reqTag = VL_RAND_RESET_I(8);
    vlSelf->io_mshrInfo_1_bits_willFree = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_1_bits_needRelease = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_1_bits_metaTag = VL_RAND_RESET_I(8);
    vlSelf->io_mshrInfo_1_bits_isAcqOrPrefetch = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_1_bits_isPrefetch = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_2_valid = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_2_bits_set = VL_RAND_RESET_I(7);
    vlSelf->io_mshrInfo_2_bits_reqTag = VL_RAND_RESET_I(8);
    vlSelf->io_mshrInfo_2_bits_willFree = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_2_bits_needRelease = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_2_bits_metaTag = VL_RAND_RESET_I(8);
    vlSelf->io_mshrInfo_2_bits_isAcqOrPrefetch = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_2_bits_isPrefetch = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_3_valid = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_3_bits_set = VL_RAND_RESET_I(7);
    vlSelf->io_mshrInfo_3_bits_reqTag = VL_RAND_RESET_I(8);
    vlSelf->io_mshrInfo_3_bits_willFree = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_3_bits_needRelease = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_3_bits_metaTag = VL_RAND_RESET_I(8);
    vlSelf->io_mshrInfo_3_bits_isAcqOrPrefetch = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_3_bits_isPrefetch = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_4_valid = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_4_bits_set = VL_RAND_RESET_I(7);
    vlSelf->io_mshrInfo_4_bits_reqTag = VL_RAND_RESET_I(8);
    vlSelf->io_mshrInfo_4_bits_willFree = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_4_bits_needRelease = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_4_bits_metaTag = VL_RAND_RESET_I(8);
    vlSelf->io_mshrInfo_4_bits_isAcqOrPrefetch = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_4_bits_isPrefetch = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_5_valid = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_5_bits_set = VL_RAND_RESET_I(7);
    vlSelf->io_mshrInfo_5_bits_reqTag = VL_RAND_RESET_I(8);
    vlSelf->io_mshrInfo_5_bits_willFree = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_5_bits_needRelease = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_5_bits_metaTag = VL_RAND_RESET_I(8);
    vlSelf->io_mshrInfo_5_bits_isAcqOrPrefetch = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_5_bits_isPrefetch = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_6_valid = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_6_bits_set = VL_RAND_RESET_I(7);
    vlSelf->io_mshrInfo_6_bits_reqTag = VL_RAND_RESET_I(8);
    vlSelf->io_mshrInfo_6_bits_willFree = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_6_bits_needRelease = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_6_bits_metaTag = VL_RAND_RESET_I(8);
    vlSelf->io_mshrInfo_6_bits_isAcqOrPrefetch = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_6_bits_isPrefetch = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_7_valid = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_7_bits_set = VL_RAND_RESET_I(7);
    vlSelf->io_mshrInfo_7_bits_reqTag = VL_RAND_RESET_I(8);
    vlSelf->io_mshrInfo_7_bits_willFree = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_7_bits_needRelease = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_7_bits_metaTag = VL_RAND_RESET_I(8);
    vlSelf->io_mshrInfo_7_bits_isAcqOrPrefetch = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_7_bits_isPrefetch = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_8_valid = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_8_bits_set = VL_RAND_RESET_I(7);
    vlSelf->io_mshrInfo_8_bits_reqTag = VL_RAND_RESET_I(8);
    vlSelf->io_mshrInfo_8_bits_willFree = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_8_bits_needRelease = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_8_bits_metaTag = VL_RAND_RESET_I(8);
    vlSelf->io_mshrInfo_8_bits_isAcqOrPrefetch = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_8_bits_isPrefetch = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_9_valid = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_9_bits_set = VL_RAND_RESET_I(7);
    vlSelf->io_mshrInfo_9_bits_reqTag = VL_RAND_RESET_I(8);
    vlSelf->io_mshrInfo_9_bits_willFree = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_9_bits_needRelease = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_9_bits_metaTag = VL_RAND_RESET_I(8);
    vlSelf->io_mshrInfo_9_bits_isAcqOrPrefetch = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_9_bits_isPrefetch = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_10_valid = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_10_bits_set = VL_RAND_RESET_I(7);
    vlSelf->io_mshrInfo_10_bits_reqTag = VL_RAND_RESET_I(8);
    vlSelf->io_mshrInfo_10_bits_willFree = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_10_bits_needRelease = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_10_bits_metaTag = VL_RAND_RESET_I(8);
    vlSelf->io_mshrInfo_10_bits_isAcqOrPrefetch = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_10_bits_isPrefetch = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_11_valid = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_11_bits_set = VL_RAND_RESET_I(7);
    vlSelf->io_mshrInfo_11_bits_reqTag = VL_RAND_RESET_I(8);
    vlSelf->io_mshrInfo_11_bits_willFree = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_11_bits_needRelease = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_11_bits_metaTag = VL_RAND_RESET_I(8);
    vlSelf->io_mshrInfo_11_bits_isAcqOrPrefetch = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_11_bits_isPrefetch = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_12_valid = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_12_bits_set = VL_RAND_RESET_I(7);
    vlSelf->io_mshrInfo_12_bits_reqTag = VL_RAND_RESET_I(8);
    vlSelf->io_mshrInfo_12_bits_willFree = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_12_bits_needRelease = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_12_bits_metaTag = VL_RAND_RESET_I(8);
    vlSelf->io_mshrInfo_12_bits_isAcqOrPrefetch = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_12_bits_isPrefetch = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_13_valid = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_13_bits_set = VL_RAND_RESET_I(7);
    vlSelf->io_mshrInfo_13_bits_reqTag = VL_RAND_RESET_I(8);
    vlSelf->io_mshrInfo_13_bits_willFree = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_13_bits_needRelease = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_13_bits_metaTag = VL_RAND_RESET_I(8);
    vlSelf->io_mshrInfo_13_bits_isAcqOrPrefetch = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_13_bits_isPrefetch = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_14_valid = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_14_bits_set = VL_RAND_RESET_I(7);
    vlSelf->io_mshrInfo_14_bits_reqTag = VL_RAND_RESET_I(8);
    vlSelf->io_mshrInfo_14_bits_willFree = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_14_bits_needRelease = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_14_bits_metaTag = VL_RAND_RESET_I(8);
    vlSelf->io_mshrInfo_14_bits_isAcqOrPrefetch = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_14_bits_isPrefetch = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_15_valid = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_15_bits_set = VL_RAND_RESET_I(7);
    vlSelf->io_mshrInfo_15_bits_reqTag = VL_RAND_RESET_I(8);
    vlSelf->io_mshrInfo_15_bits_willFree = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_15_bits_needRelease = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_15_bits_metaTag = VL_RAND_RESET_I(8);
    vlSelf->io_mshrInfo_15_bits_isAcqOrPrefetch = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_15_bits_isPrefetch = VL_RAND_RESET_I(1);
    vlSelf->io_mainPipeBlock_0 = VL_RAND_RESET_I(1);
    vlSelf->io_mainPipeBlock_1 = VL_RAND_RESET_I(1);
    vlSelf->io_ATag = VL_RAND_RESET_I(8);
    vlSelf->io_ASet = VL_RAND_RESET_I(7);
    vlSelf->io_s1Entrance_valid = VL_RAND_RESET_I(1);
    vlSelf->io_s1Entrance_bits_set = VL_RAND_RESET_I(7);
    vlSelf->io_hasLatePF = VL_RAND_RESET_I(1);
    vlSelf->__PVT__buffer_0_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__buffer_0_rdy = VL_RAND_RESET_I(1);
    vlSelf->__PVT__buffer_0_task_channel = VL_RAND_RESET_I(3);
    vlSelf->__PVT__buffer_0_task_set = VL_RAND_RESET_I(7);
    vlSelf->__PVT__buffer_0_task_tag = VL_RAND_RESET_I(8);
    vlSelf->__PVT__buffer_0_task_off = VL_RAND_RESET_I(1);
    vlSelf->__PVT__buffer_0_task_alias = VL_RAND_RESET_I(2);
    vlSelf->__PVT__buffer_0_task_opcode = VL_RAND_RESET_I(3);
    vlSelf->__PVT__buffer_0_task_param = VL_RAND_RESET_I(3);
    vlSelf->__PVT__buffer_0_task_size = VL_RAND_RESET_I(1);
    vlSelf->__PVT__buffer_0_task_sourceId = VL_RAND_RESET_I(5);
    vlSelf->__PVT__buffer_0_waitMP = VL_RAND_RESET_I(4);
    vlSelf->__PVT__buffer_0_waitMS = VL_RAND_RESET_I(16);
    vlSelf->__PVT__buffer_1_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__buffer_1_rdy = VL_RAND_RESET_I(1);
    vlSelf->__PVT__buffer_1_task_channel = VL_RAND_RESET_I(3);
    vlSelf->__PVT__buffer_1_task_set = VL_RAND_RESET_I(7);
    vlSelf->__PVT__buffer_1_task_tag = VL_RAND_RESET_I(8);
    vlSelf->__PVT__buffer_1_task_off = VL_RAND_RESET_I(1);
    vlSelf->__PVT__buffer_1_task_alias = VL_RAND_RESET_I(2);
    vlSelf->__PVT__buffer_1_task_opcode = VL_RAND_RESET_I(3);
    vlSelf->__PVT__buffer_1_task_param = VL_RAND_RESET_I(3);
    vlSelf->__PVT__buffer_1_task_size = VL_RAND_RESET_I(1);
    vlSelf->__PVT__buffer_1_task_sourceId = VL_RAND_RESET_I(5);
    vlSelf->__PVT__buffer_1_waitMP = VL_RAND_RESET_I(4);
    vlSelf->__PVT__buffer_1_waitMS = VL_RAND_RESET_I(16);
    vlSelf->__PVT__buffer_2_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__buffer_2_rdy = VL_RAND_RESET_I(1);
    vlSelf->__PVT__buffer_2_task_channel = VL_RAND_RESET_I(3);
    vlSelf->__PVT__buffer_2_task_set = VL_RAND_RESET_I(7);
    vlSelf->__PVT__buffer_2_task_tag = VL_RAND_RESET_I(8);
    vlSelf->__PVT__buffer_2_task_off = VL_RAND_RESET_I(1);
    vlSelf->__PVT__buffer_2_task_alias = VL_RAND_RESET_I(2);
    vlSelf->__PVT__buffer_2_task_opcode = VL_RAND_RESET_I(3);
    vlSelf->__PVT__buffer_2_task_param = VL_RAND_RESET_I(3);
    vlSelf->__PVT__buffer_2_task_size = VL_RAND_RESET_I(1);
    vlSelf->__PVT__buffer_2_task_sourceId = VL_RAND_RESET_I(5);
    vlSelf->__PVT__buffer_2_waitMP = VL_RAND_RESET_I(4);
    vlSelf->__PVT__buffer_2_waitMS = VL_RAND_RESET_I(16);
    vlSelf->__PVT__buffer_3_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__buffer_3_rdy = VL_RAND_RESET_I(1);
    vlSelf->__PVT__buffer_3_task_channel = VL_RAND_RESET_I(3);
    vlSelf->__PVT__buffer_3_task_set = VL_RAND_RESET_I(7);
    vlSelf->__PVT__buffer_3_task_tag = VL_RAND_RESET_I(8);
    vlSelf->__PVT__buffer_3_task_off = VL_RAND_RESET_I(1);
    vlSelf->__PVT__buffer_3_task_alias = VL_RAND_RESET_I(2);
    vlSelf->__PVT__buffer_3_task_opcode = VL_RAND_RESET_I(3);
    vlSelf->__PVT__buffer_3_task_param = VL_RAND_RESET_I(3);
    vlSelf->__PVT__buffer_3_task_size = VL_RAND_RESET_I(1);
    vlSelf->__PVT__buffer_3_task_sourceId = VL_RAND_RESET_I(5);
    vlSelf->__PVT__buffer_3_waitMP = VL_RAND_RESET_I(4);
    vlSelf->__PVT__buffer_3_waitMS = VL_RAND_RESET_I(16);
    vlSelf->__PVT___canFlow_T = VL_RAND_RESET_I(1);
    vlSelf->__PVT___canFlow_T_146 = VL_RAND_RESET_I(16);
    vlSelf->__PVT___canFlow_T_154 = VL_RAND_RESET_I(1);
    vlSelf->__PVT__canFlow = VL_RAND_RESET_I(1);
    vlSelf->__PVT__doFlow = VL_RAND_RESET_I(1);
    vlSelf->__PVT___io_hasLatePF_T_1 = VL_RAND_RESET_I(15);
    vlSelf->__PVT___io_hasLatePF_T_3 = VL_RAND_RESET_I(1);
    vlSelf->__PVT___io_hasLatePF_T_17 = VL_RAND_RESET_I(1);
    vlSelf->__PVT___io_hasLatePF_T_31 = VL_RAND_RESET_I(1);
    vlSelf->__PVT___io_hasLatePF_T_45 = VL_RAND_RESET_I(1);
    vlSelf->__PVT___io_hasLatePF_T_59 = VL_RAND_RESET_I(1);
    vlSelf->__PVT___io_hasLatePF_T_73 = VL_RAND_RESET_I(1);
    vlSelf->__PVT___io_hasLatePF_T_87 = VL_RAND_RESET_I(1);
    vlSelf->__PVT___io_hasLatePF_T_101 = VL_RAND_RESET_I(1);
    vlSelf->__PVT___io_hasLatePF_T_115 = VL_RAND_RESET_I(1);
    vlSelf->__PVT___io_hasLatePF_T_129 = VL_RAND_RESET_I(1);
    vlSelf->__PVT___io_hasLatePF_T_143 = VL_RAND_RESET_I(1);
    vlSelf->__PVT___io_hasLatePF_T_157 = VL_RAND_RESET_I(1);
    vlSelf->__PVT___io_hasLatePF_T_171 = VL_RAND_RESET_I(1);
    vlSelf->__PVT___io_hasLatePF_T_185 = VL_RAND_RESET_I(1);
    vlSelf->__PVT___io_hasLatePF_T_199 = VL_RAND_RESET_I(1);
    vlSelf->__PVT___io_hasLatePF_T_213 = VL_RAND_RESET_I(1);
    vlSelf->__PVT__insertIdx = VL_RAND_RESET_I(2);
    vlSelf->__PVT__alloc = VL_RAND_RESET_I(1);
    vlSelf->__PVT__s1Block = VL_RAND_RESET_I(1);
    vlSelf->__PVT___buffer_waitMP_T = VL_RAND_RESET_I(4);
    vlSelf->__PVT___GEN_128 = VL_RAND_RESET_I(1);
    vlSelf->__PVT___GEN_129 = VL_RAND_RESET_I(1);
    vlSelf->__PVT___GEN_130 = VL_RAND_RESET_I(1);
    vlSelf->__PVT___GEN_131 = VL_RAND_RESET_I(1);
    vlSelf->__PVT___pipeBlockOut_T_2 = VL_RAND_RESET_I(1);
    vlSelf->__PVT___pipeBlockOut_T_3 = VL_RAND_RESET_I(1);
    vlSelf->__PVT___pipeBlockOut_T_4 = VL_RAND_RESET_I(1);
    vlSelf->__PVT___pipeBlockOut_T_5 = VL_RAND_RESET_I(1);
    vlSelf->__PVT___waitMSUpdate_T_1 = VL_RAND_RESET_I(16);
    vlSelf->__PVT___buffer_0_waitMP_T = VL_RAND_RESET_I(4);
    vlSelf->__PVT___waitMSUpdate_T_146 = VL_RAND_RESET_I(16);
    vlSelf->__PVT__waitMSUpdate = VL_RAND_RESET_I(16);
    vlSelf->__PVT__s1_Block = VL_RAND_RESET_I(1);
    vlSelf->__PVT___buffer_0_waitMP_T_1 = VL_RAND_RESET_I(4);
    vlSelf->__PVT___waitMSUpdate_T_148 = VL_RAND_RESET_I(16);
    vlSelf->__PVT___buffer_1_waitMP_T = VL_RAND_RESET_I(4);
    vlSelf->__PVT___waitMSUpdate_T_293 = VL_RAND_RESET_I(16);
    vlSelf->__PVT__waitMSUpdate_1 = VL_RAND_RESET_I(16);
    vlSelf->__PVT__s1_Block_1 = VL_RAND_RESET_I(1);
    vlSelf->__PVT___buffer_1_waitMP_T_1 = VL_RAND_RESET_I(4);
    vlSelf->__PVT___waitMSUpdate_T_295 = VL_RAND_RESET_I(16);
    vlSelf->__PVT___buffer_2_waitMP_T = VL_RAND_RESET_I(4);
    vlSelf->__PVT___waitMSUpdate_T_440 = VL_RAND_RESET_I(16);
    vlSelf->__PVT__waitMSUpdate_2 = VL_RAND_RESET_I(16);
    vlSelf->__PVT__s1_Block_2 = VL_RAND_RESET_I(1);
    vlSelf->__PVT___buffer_2_waitMP_T_1 = VL_RAND_RESET_I(4);
    vlSelf->__PVT___waitMSUpdate_T_442 = VL_RAND_RESET_I(16);
    vlSelf->__PVT___buffer_3_waitMP_T = VL_RAND_RESET_I(4);
    vlSelf->__PVT___waitMSUpdate_T_587 = VL_RAND_RESET_I(16);
    vlSelf->__PVT__waitMSUpdate_3 = VL_RAND_RESET_I(16);
    vlSelf->__PVT__s1_Block_3 = VL_RAND_RESET_I(1);
    vlSelf->__PVT___buffer_3_waitMP_T_1 = VL_RAND_RESET_I(4);
    vlSelf->__PVT___io_out_valid_T = VL_RAND_RESET_I(1);
    vlSelf->__PVT__bufferTimer_0 = VL_RAND_RESET_I(16);
    vlSelf->__PVT__bufferTimer_1 = VL_RAND_RESET_I(16);
    vlSelf->__PVT__bufferTimer_2 = VL_RAND_RESET_I(16);
    vlSelf->__PVT__bufferTimer_3 = VL_RAND_RESET_I(16);
    vlSelf->__PVT___bufferTimer_0_T_1 = VL_RAND_RESET_I(16);
    vlSelf->__PVT__REG = VL_RAND_RESET_I(1);
    vlSelf->__PVT__REG_1 = VL_RAND_RESET_I(1);
    vlSelf->__PVT___bufferTimer_1_T_1 = VL_RAND_RESET_I(16);
    vlSelf->__PVT__REG_2 = VL_RAND_RESET_I(1);
    vlSelf->__PVT__REG_3 = VL_RAND_RESET_I(1);
    vlSelf->__PVT___bufferTimer_2_T_1 = VL_RAND_RESET_I(16);
    vlSelf->__PVT__REG_4 = VL_RAND_RESET_I(1);
    vlSelf->__PVT__REG_5 = VL_RAND_RESET_I(1);
    vlSelf->__PVT___bufferTimer_3_T_1 = VL_RAND_RESET_I(16);
    vlSelf->__PVT__REG_6 = VL_RAND_RESET_I(1);
    vlSelf->__PVT__REG_7 = VL_RAND_RESET_I(1);
    vlSelf->__PVT__issueArb__DOT__valids = VL_RAND_RESET_I(4);
    vlSelf->__PVT__issueArb__DOT__rrGrantMask = VL_RAND_RESET_I(4);
    vlSelf->__PVT__issueArb__DOT__pendingMask = VL_RAND_RESET_I(4);
    vlSelf->__PVT__issueArb__DOT__rrSelOH = VL_RAND_RESET_I(4);
    vlSelf->__PVT__issueArb__DOT__chosenOH = VL_RAND_RESET_I(4);
    vlSelf->__PVT__issueArb__DOT___pendingMask_T_2 = VL_RAND_RESET_I(1);
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_channel[__Vi0] = VL_RAND_RESET_I(3);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_set[__Vi0] = VL_RAND_RESET_I(7);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_tag[__Vi0] = VL_RAND_RESET_I(8);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_off[__Vi0] = VL_RAND_RESET_I(1);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_alias[__Vi0] = VL_RAND_RESET_I(2);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_opcode[__Vi0] = VL_RAND_RESET_I(3);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_param[__Vi0] = VL_RAND_RESET_I(3);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_sourceId[__Vi0] = VL_RAND_RESET_I(5);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_bufIdx[__Vi0] = VL_RAND_RESET_I(2);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_needProbeAckData[__Vi0] = VL_RAND_RESET_I(1);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_mshrTask[__Vi0] = VL_RAND_RESET_I(1);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_mshrId[__Vi0] = VL_RAND_RESET_I(8);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_useProbeData[__Vi0] = VL_RAND_RESET_I(1);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_dirty[__Vi0] = VL_RAND_RESET_I(1);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_way[__Vi0] = VL_RAND_RESET_I(2);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_meta_dirty[__Vi0] = VL_RAND_RESET_I(1);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_meta_state[__Vi0] = VL_RAND_RESET_I(2);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_meta_clients[__Vi0] = VL_RAND_RESET_I(1);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_meta_alias[__Vi0] = VL_RAND_RESET_I(2);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_meta_accessed[__Vi0] = VL_RAND_RESET_I(1);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_metaWen[__Vi0] = VL_RAND_RESET_I(1);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_tagWen[__Vi0] = VL_RAND_RESET_I(1);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_dsWen[__Vi0] = VL_RAND_RESET_I(1);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_replTask[__Vi0] = VL_RAND_RESET_I(1);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_reqSource[__Vi0] = VL_RAND_RESET_I(4);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_id[__Vi0] = VL_RAND_RESET_I(2);
    }
    vlSelf->__PVT__chosenQ__DOT__maybe_full = VL_RAND_RESET_I(1);
    vlSelf->__PVT__chosenQ__DOT__do_deq = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__chosenQ__DOT__ram_bits_task_metaWen__v0 = 0;
    vlSelf->__VdlySet__chosenQ__DOT__ram_bits_task_meta_accessed__v0 = 0;
    vlSelf->__VdlySet__chosenQ__DOT__ram_bits_task_meta_alias__v0 = 0;
    vlSelf->__VdlySet__chosenQ__DOT__ram_bits_task_meta_clients__v0 = 0;
    vlSelf->__VdlySet__chosenQ__DOT__ram_bits_task_way__v0 = 0;
    vlSelf->__VdlySet__chosenQ__DOT__ram_bits_task_dirty__v0 = 0;
    vlSelf->__VdlySet__chosenQ__DOT__ram_bits_task_useProbeData__v0 = 0;
    vlSelf->__VdlySet__chosenQ__DOT__ram_bits_task_mshrTask__v0 = 0;
    vlSelf->__VdlyVal__chosenQ__DOT__ram_bits_task_off__v0 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__chosenQ__DOT__ram_bits_task_off__v0 = 0;
    vlSelf->__VdlySet__chosenQ__DOT__ram_bits_task_tagWen__v0 = 0;
    vlSelf->__VdlyVal__chosenQ__DOT__ram_bits_task_alias__v0 = VL_RAND_RESET_I(2);
    vlSelf->__VdlySet__chosenQ__DOT__ram_bits_task_alias__v0 = 0;
    vlSelf->__VdlySet__chosenQ__DOT__ram_bits_task_meta_dirty__v0 = 0;
    vlSelf->__VdlyVal__chosenQ__DOT__ram_bits_task_param__v0 = VL_RAND_RESET_I(3);
    vlSelf->__VdlySet__chosenQ__DOT__ram_bits_task_param__v0 = 0;
    vlSelf->__VdlySet__chosenQ__DOT__ram_bits_task_meta_state__v0 = 0;
    vlSelf->__VdlyVal__chosenQ__DOT__ram_bits_task_sourceId__v0 = VL_RAND_RESET_I(5);
    vlSelf->__VdlySet__chosenQ__DOT__ram_bits_task_sourceId__v0 = 0;
    vlSelf->__VdlySet__chosenQ__DOT__ram_bits_task_bufIdx__v0 = 0;
    vlSelf->__VdlySet__chosenQ__DOT__ram_bits_task_needProbeAckData__v0 = 0;
    vlSelf->__VdlySet__chosenQ__DOT__ram_bits_task_dsWen__v0 = 0;
    vlSelf->__VdlySet__chosenQ__DOT__ram_bits_task_replTask__v0 = 0;
}
