// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See VTestTop_L2L3L2.h for the primary calling header

#ifndef VERILATED_VTESTTOP_L2L3L2_DIRECTORY_H_
#define VERILATED_VTESTTOP_L2L3L2_DIRECTORY_H_  // guard

#include "verilated.h"


class VTestTop_L2L3L2__Syms;

class alignas(VL_CACHE_LINE_BYTES) VTestTop_L2L3L2_Directory final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clock,0,0);
        VL_IN8(reset,0,0);
        VL_OUT8(io_read_ready,0,0);
        VL_IN8(io_read_valid,0,0);
        VL_IN8(io_read_bits_tag,7,0);
        VL_IN8(io_read_bits_set,6,0);
        VL_IN8(io_read_bits_wayMask,3,0);
        VL_IN8(io_read_bits_replacerInfo_channel,2,0);
        VL_IN8(io_read_bits_replacerInfo_opcode,2,0);
        VL_IN8(io_read_bits_replacerInfo_reqSource,3,0);
        VL_IN8(io_read_bits_refill,0,0);
        VL_IN8(io_read_bits_mshrId,7,0);
        VL_OUT8(io_resp_hit,0,0);
        VL_OUT8(io_resp_tag,7,0);
        VL_OUT8(io_resp_set,6,0);
        VL_OUT8(io_resp_way,1,0);
        VL_OUT8(io_resp_meta_dirty,0,0);
        VL_OUT8(io_resp_meta_state,1,0);
        VL_OUT8(io_resp_meta_clients,0,0);
        VL_OUT8(io_resp_meta_alias,1,0);
        VL_OUT8(io_resp_meta_accessed,0,0);
        VL_OUT8(__PVT__io_resp_error,0,0);
        VL_OUT8(io_resp_replacerInfo_channel,2,0);
        VL_OUT8(io_resp_replacerInfo_opcode,2,0);
        VL_OUT8(io_resp_replacerInfo_reqSource,3,0);
        VL_IN8(io_metaWReq_valid,0,0);
        VL_IN8(io_metaWReq_bits_set,6,0);
        VL_IN8(io_metaWReq_bits_wayOH,3,0);
        VL_IN8(io_metaWReq_bits_wmeta_dirty,0,0);
        VL_IN8(io_metaWReq_bits_wmeta_state,1,0);
        VL_IN8(io_metaWReq_bits_wmeta_clients,0,0);
        VL_IN8(io_metaWReq_bits_wmeta_alias,1,0);
        VL_IN8(io_metaWReq_bits_wmeta_accessed,0,0);
        VL_IN8(io_tagWReq_valid,0,0);
        VL_IN8(io_tagWReq_bits_set,6,0);
        VL_IN8(io_tagWReq_bits_way,1,0);
        VL_IN8(io_tagWReq_bits_wtag,7,0);
        VL_OUT8(io_replResp_valid,0,0);
        VL_OUT8(io_replResp_bits_tag,7,0);
        VL_OUT8(io_replResp_bits_set,6,0);
        VL_OUT8(io_replResp_bits_way,1,0);
        VL_OUT8(io_replResp_bits_meta_dirty,0,0);
        VL_OUT8(io_replResp_bits_meta_state,1,0);
        VL_OUT8(io_replResp_bits_meta_clients,0,0);
        VL_OUT8(io_replResp_bits_meta_alias,1,0);
        VL_OUT8(io_replResp_bits_meta_accessed,0,0);
        VL_OUT8(io_replResp_bits_mshrId,7,0);
        VL_OUT8(io_replResp_bits_retry,0,0);
        VL_IN8(io_msInfo_0_valid,0,0);
        VL_IN8(io_msInfo_0_bits_set,6,0);
        VL_IN8(io_msInfo_0_bits_way,1,0);
        VL_IN8(io_msInfo_0_bits_reqTag,7,0);
        VL_IN8(io_msInfo_0_bits_willFree,0,0);
        VL_IN8(io_msInfo_0_bits_needRelease,0,0);
        VL_IN8(io_msInfo_0_bits_releaseNotSent,0,0);
        VL_IN8(io_msInfo_0_bits_metaTag,7,0);
        VL_IN8(io_msInfo_0_bits_dirHit,0,0);
        VL_IN8(io_msInfo_0_bits_nestB,0,0);
        VL_IN8(io_msInfo_0_bits_mergeB,0,0);
        VL_IN8(io_msInfo_0_bits_isAcqOrPrefetch,0,0);
        VL_IN8(io_msInfo_0_bits_isPrefetch,0,0);
        VL_IN8(io_msInfo_1_valid,0,0);
        VL_IN8(io_msInfo_1_bits_set,6,0);
        VL_IN8(io_msInfo_1_bits_way,1,0);
    };
    struct {
        VL_IN8(io_msInfo_1_bits_reqTag,7,0);
        VL_IN8(io_msInfo_1_bits_willFree,0,0);
        VL_IN8(io_msInfo_1_bits_needRelease,0,0);
        VL_IN8(io_msInfo_1_bits_releaseNotSent,0,0);
        VL_IN8(io_msInfo_1_bits_metaTag,7,0);
        VL_IN8(io_msInfo_1_bits_dirHit,0,0);
        VL_IN8(io_msInfo_1_bits_nestB,0,0);
        VL_IN8(io_msInfo_1_bits_mergeB,0,0);
        VL_IN8(io_msInfo_1_bits_isAcqOrPrefetch,0,0);
        VL_IN8(io_msInfo_1_bits_isPrefetch,0,0);
        VL_IN8(io_msInfo_2_valid,0,0);
        VL_IN8(io_msInfo_2_bits_set,6,0);
        VL_IN8(io_msInfo_2_bits_way,1,0);
        VL_IN8(io_msInfo_2_bits_reqTag,7,0);
        VL_IN8(io_msInfo_2_bits_willFree,0,0);
        VL_IN8(io_msInfo_2_bits_needRelease,0,0);
        VL_IN8(io_msInfo_2_bits_releaseNotSent,0,0);
        VL_IN8(io_msInfo_2_bits_metaTag,7,0);
        VL_IN8(io_msInfo_2_bits_dirHit,0,0);
        VL_IN8(io_msInfo_2_bits_nestB,0,0);
        VL_IN8(io_msInfo_2_bits_mergeB,0,0);
        VL_IN8(io_msInfo_2_bits_isAcqOrPrefetch,0,0);
        VL_IN8(io_msInfo_2_bits_isPrefetch,0,0);
        VL_IN8(io_msInfo_3_valid,0,0);
        VL_IN8(io_msInfo_3_bits_set,6,0);
        VL_IN8(io_msInfo_3_bits_way,1,0);
        VL_IN8(io_msInfo_3_bits_reqTag,7,0);
        VL_IN8(io_msInfo_3_bits_willFree,0,0);
        VL_IN8(io_msInfo_3_bits_needRelease,0,0);
        VL_IN8(io_msInfo_3_bits_releaseNotSent,0,0);
        VL_IN8(io_msInfo_3_bits_metaTag,7,0);
        VL_IN8(io_msInfo_3_bits_dirHit,0,0);
        VL_IN8(io_msInfo_3_bits_nestB,0,0);
        VL_IN8(io_msInfo_3_bits_mergeB,0,0);
        VL_IN8(io_msInfo_3_bits_isAcqOrPrefetch,0,0);
        VL_IN8(io_msInfo_3_bits_isPrefetch,0,0);
        VL_IN8(io_msInfo_4_valid,0,0);
        VL_IN8(io_msInfo_4_bits_set,6,0);
        VL_IN8(io_msInfo_4_bits_way,1,0);
        VL_IN8(io_msInfo_4_bits_reqTag,7,0);
        VL_IN8(io_msInfo_4_bits_willFree,0,0);
        VL_IN8(io_msInfo_4_bits_needRelease,0,0);
        VL_IN8(io_msInfo_4_bits_releaseNotSent,0,0);
        VL_IN8(io_msInfo_4_bits_metaTag,7,0);
        VL_IN8(io_msInfo_4_bits_dirHit,0,0);
        VL_IN8(io_msInfo_4_bits_nestB,0,0);
        VL_IN8(io_msInfo_4_bits_mergeB,0,0);
        VL_IN8(io_msInfo_4_bits_isAcqOrPrefetch,0,0);
        VL_IN8(io_msInfo_4_bits_isPrefetch,0,0);
        VL_IN8(io_msInfo_5_valid,0,0);
        VL_IN8(io_msInfo_5_bits_set,6,0);
        VL_IN8(io_msInfo_5_bits_way,1,0);
        VL_IN8(io_msInfo_5_bits_reqTag,7,0);
        VL_IN8(io_msInfo_5_bits_willFree,0,0);
        VL_IN8(io_msInfo_5_bits_needRelease,0,0);
        VL_IN8(io_msInfo_5_bits_releaseNotSent,0,0);
        VL_IN8(io_msInfo_5_bits_metaTag,7,0);
        VL_IN8(io_msInfo_5_bits_dirHit,0,0);
        VL_IN8(io_msInfo_5_bits_nestB,0,0);
        VL_IN8(io_msInfo_5_bits_mergeB,0,0);
        VL_IN8(io_msInfo_5_bits_isAcqOrPrefetch,0,0);
        VL_IN8(io_msInfo_5_bits_isPrefetch,0,0);
        VL_IN8(io_msInfo_6_valid,0,0);
        VL_IN8(io_msInfo_6_bits_set,6,0);
    };
    struct {
        VL_IN8(io_msInfo_6_bits_way,1,0);
        VL_IN8(io_msInfo_6_bits_reqTag,7,0);
        VL_IN8(io_msInfo_6_bits_willFree,0,0);
        VL_IN8(io_msInfo_6_bits_needRelease,0,0);
        VL_IN8(io_msInfo_6_bits_releaseNotSent,0,0);
        VL_IN8(io_msInfo_6_bits_metaTag,7,0);
        VL_IN8(io_msInfo_6_bits_dirHit,0,0);
        VL_IN8(io_msInfo_6_bits_nestB,0,0);
        VL_IN8(io_msInfo_6_bits_mergeB,0,0);
        VL_IN8(io_msInfo_6_bits_isAcqOrPrefetch,0,0);
        VL_IN8(io_msInfo_6_bits_isPrefetch,0,0);
        VL_IN8(io_msInfo_7_valid,0,0);
        VL_IN8(io_msInfo_7_bits_set,6,0);
        VL_IN8(io_msInfo_7_bits_way,1,0);
        VL_IN8(io_msInfo_7_bits_reqTag,7,0);
        VL_IN8(io_msInfo_7_bits_willFree,0,0);
        VL_IN8(io_msInfo_7_bits_needRelease,0,0);
        VL_IN8(io_msInfo_7_bits_releaseNotSent,0,0);
        VL_IN8(io_msInfo_7_bits_metaTag,7,0);
        VL_IN8(io_msInfo_7_bits_dirHit,0,0);
        VL_IN8(io_msInfo_7_bits_nestB,0,0);
        VL_IN8(io_msInfo_7_bits_mergeB,0,0);
        VL_IN8(io_msInfo_7_bits_isAcqOrPrefetch,0,0);
        VL_IN8(io_msInfo_7_bits_isPrefetch,0,0);
        VL_IN8(io_msInfo_8_valid,0,0);
        VL_IN8(io_msInfo_8_bits_set,6,0);
        VL_IN8(io_msInfo_8_bits_way,1,0);
        VL_IN8(io_msInfo_8_bits_reqTag,7,0);
        VL_IN8(io_msInfo_8_bits_willFree,0,0);
        VL_IN8(io_msInfo_8_bits_needRelease,0,0);
        VL_IN8(io_msInfo_8_bits_releaseNotSent,0,0);
        VL_IN8(io_msInfo_8_bits_metaTag,7,0);
        VL_IN8(io_msInfo_8_bits_dirHit,0,0);
        VL_IN8(io_msInfo_8_bits_nestB,0,0);
        VL_IN8(io_msInfo_8_bits_mergeB,0,0);
        VL_IN8(io_msInfo_8_bits_isAcqOrPrefetch,0,0);
        VL_IN8(io_msInfo_8_bits_isPrefetch,0,0);
        VL_IN8(io_msInfo_9_valid,0,0);
        VL_IN8(io_msInfo_9_bits_set,6,0);
        VL_IN8(io_msInfo_9_bits_way,1,0);
        VL_IN8(io_msInfo_9_bits_reqTag,7,0);
        VL_IN8(io_msInfo_9_bits_willFree,0,0);
        VL_IN8(io_msInfo_9_bits_needRelease,0,0);
        VL_IN8(io_msInfo_9_bits_releaseNotSent,0,0);
        VL_IN8(io_msInfo_9_bits_metaTag,7,0);
        VL_IN8(io_msInfo_9_bits_dirHit,0,0);
        VL_IN8(io_msInfo_9_bits_nestB,0,0);
        VL_IN8(io_msInfo_9_bits_mergeB,0,0);
        VL_IN8(io_msInfo_9_bits_isAcqOrPrefetch,0,0);
        VL_IN8(io_msInfo_9_bits_isPrefetch,0,0);
        VL_IN8(io_msInfo_10_valid,0,0);
        VL_IN8(io_msInfo_10_bits_set,6,0);
        VL_IN8(io_msInfo_10_bits_way,1,0);
        VL_IN8(io_msInfo_10_bits_reqTag,7,0);
        VL_IN8(io_msInfo_10_bits_willFree,0,0);
        VL_IN8(io_msInfo_10_bits_needRelease,0,0);
        VL_IN8(io_msInfo_10_bits_releaseNotSent,0,0);
        VL_IN8(io_msInfo_10_bits_metaTag,7,0);
        VL_IN8(io_msInfo_10_bits_dirHit,0,0);
        VL_IN8(io_msInfo_10_bits_nestB,0,0);
        VL_IN8(io_msInfo_10_bits_mergeB,0,0);
        VL_IN8(io_msInfo_10_bits_isAcqOrPrefetch,0,0);
        VL_IN8(io_msInfo_10_bits_isPrefetch,0,0);
        VL_IN8(io_msInfo_11_valid,0,0);
    };
    struct {
        VL_IN8(io_msInfo_11_bits_set,6,0);
        VL_IN8(io_msInfo_11_bits_way,1,0);
        VL_IN8(io_msInfo_11_bits_reqTag,7,0);
        VL_IN8(io_msInfo_11_bits_willFree,0,0);
        VL_IN8(io_msInfo_11_bits_needRelease,0,0);
        VL_IN8(io_msInfo_11_bits_releaseNotSent,0,0);
        VL_IN8(io_msInfo_11_bits_metaTag,7,0);
        VL_IN8(io_msInfo_11_bits_dirHit,0,0);
        VL_IN8(io_msInfo_11_bits_nestB,0,0);
        VL_IN8(io_msInfo_11_bits_mergeB,0,0);
        VL_IN8(io_msInfo_11_bits_isAcqOrPrefetch,0,0);
        VL_IN8(io_msInfo_11_bits_isPrefetch,0,0);
        VL_IN8(io_msInfo_12_valid,0,0);
        VL_IN8(io_msInfo_12_bits_set,6,0);
        VL_IN8(io_msInfo_12_bits_way,1,0);
        VL_IN8(io_msInfo_12_bits_reqTag,7,0);
        VL_IN8(io_msInfo_12_bits_willFree,0,0);
        VL_IN8(io_msInfo_12_bits_needRelease,0,0);
        VL_IN8(io_msInfo_12_bits_releaseNotSent,0,0);
        VL_IN8(io_msInfo_12_bits_metaTag,7,0);
        VL_IN8(io_msInfo_12_bits_dirHit,0,0);
        VL_IN8(io_msInfo_12_bits_nestB,0,0);
        VL_IN8(io_msInfo_12_bits_mergeB,0,0);
        VL_IN8(io_msInfo_12_bits_isAcqOrPrefetch,0,0);
        VL_IN8(io_msInfo_12_bits_isPrefetch,0,0);
        VL_IN8(io_msInfo_13_valid,0,0);
        VL_IN8(io_msInfo_13_bits_set,6,0);
        VL_IN8(io_msInfo_13_bits_way,1,0);
        VL_IN8(io_msInfo_13_bits_reqTag,7,0);
        VL_IN8(io_msInfo_13_bits_willFree,0,0);
        VL_IN8(io_msInfo_13_bits_needRelease,0,0);
        VL_IN8(io_msInfo_13_bits_releaseNotSent,0,0);
        VL_IN8(io_msInfo_13_bits_metaTag,7,0);
        VL_IN8(io_msInfo_13_bits_dirHit,0,0);
        VL_IN8(io_msInfo_13_bits_nestB,0,0);
        VL_IN8(io_msInfo_13_bits_mergeB,0,0);
        VL_IN8(io_msInfo_13_bits_isAcqOrPrefetch,0,0);
        VL_IN8(io_msInfo_13_bits_isPrefetch,0,0);
        VL_IN8(io_msInfo_14_valid,0,0);
        VL_IN8(io_msInfo_14_bits_set,6,0);
        VL_IN8(io_msInfo_14_bits_way,1,0);
        VL_IN8(io_msInfo_14_bits_reqTag,7,0);
        VL_IN8(io_msInfo_14_bits_willFree,0,0);
        VL_IN8(io_msInfo_14_bits_needRelease,0,0);
        VL_IN8(io_msInfo_14_bits_releaseNotSent,0,0);
        VL_IN8(io_msInfo_14_bits_metaTag,7,0);
        VL_IN8(io_msInfo_14_bits_dirHit,0,0);
        VL_IN8(io_msInfo_14_bits_nestB,0,0);
        VL_IN8(io_msInfo_14_bits_mergeB,0,0);
        VL_IN8(io_msInfo_14_bits_isAcqOrPrefetch,0,0);
        VL_IN8(io_msInfo_14_bits_isPrefetch,0,0);
        VL_IN8(io_msInfo_15_valid,0,0);
        VL_IN8(io_msInfo_15_bits_set,6,0);
        VL_IN8(io_msInfo_15_bits_way,1,0);
        VL_IN8(io_msInfo_15_bits_reqTag,7,0);
        VL_IN8(io_msInfo_15_bits_willFree,0,0);
        VL_IN8(io_msInfo_15_bits_needRelease,0,0);
        VL_IN8(io_msInfo_15_bits_releaseNotSent,0,0);
        VL_IN8(io_msInfo_15_bits_metaTag,7,0);
        VL_IN8(io_msInfo_15_bits_dirHit,0,0);
        VL_IN8(io_msInfo_15_bits_nestB,0,0);
        VL_IN8(io_msInfo_15_bits_mergeB,0,0);
        VL_IN8(io_msInfo_15_bits_isAcqOrPrefetch,0,0);
        VL_IN8(io_msInfo_15_bits_isPrefetch,0,0);
    };
    struct {
        CData/*0:0*/ __PVT__tagArray_io_r_req_valid;
        CData/*6:0*/ __PVT__replacer_sram_opt_io_w_req_bits_setIdx;
        CData/*2:0*/ __PVT__replacer_sram_opt_io_w_req_bits_data_0;
        CData/*0:0*/ __PVT__resetFinish;
        CData/*6:0*/ __PVT__resetIdx;
        CData/*0:0*/ __PVT__reqValid_s2;
        CData/*0:0*/ __PVT__reqValid_s3;
        CData/*7:0*/ __PVT__req_s2_tag;
        CData/*6:0*/ __PVT__req_s2_set;
        CData/*3:0*/ __PVT__req_s2_wayMask;
        CData/*2:0*/ __PVT__req_s2_replacerInfo_channel;
        CData/*2:0*/ __PVT__req_s2_replacerInfo_opcode;
        CData/*7:0*/ __PVT__req_s2_mshrId;
        CData/*7:0*/ __PVT__req_s3_tag;
        CData/*6:0*/ __PVT__req_s3_set;
        CData/*3:0*/ __PVT__req_s3_wayMask;
        CData/*2:0*/ __PVT__req_s3_replacerInfo_channel;
        CData/*2:0*/ __PVT__req_s3_replacerInfo_opcode;
        CData/*7:0*/ __PVT__req_s3_mshrId;
        CData/*0:0*/ __PVT__refillReqValid_s2;
        CData/*0:0*/ __PVT__refillReqValid_s3;
        CData/*0:0*/ __PVT__metaAll_s3_0_dirty;
        CData/*1:0*/ __PVT__metaAll_s3_0_state;
        CData/*0:0*/ __PVT__metaAll_s3_0_clients;
        CData/*1:0*/ __PVT__metaAll_s3_0_alias;
        CData/*0:0*/ __PVT__metaAll_s3_0_accessed;
        CData/*0:0*/ __PVT__metaAll_s3_1_dirty;
        CData/*1:0*/ __PVT__metaAll_s3_1_state;
        CData/*0:0*/ __PVT__metaAll_s3_1_clients;
        CData/*1:0*/ __PVT__metaAll_s3_1_alias;
        CData/*0:0*/ __PVT__metaAll_s3_1_accessed;
        CData/*0:0*/ __PVT__metaAll_s3_2_dirty;
        CData/*1:0*/ __PVT__metaAll_s3_2_state;
        CData/*0:0*/ __PVT__metaAll_s3_2_clients;
        CData/*1:0*/ __PVT__metaAll_s3_2_alias;
        CData/*0:0*/ __PVT__metaAll_s3_2_accessed;
        CData/*0:0*/ __PVT__metaAll_s3_3_dirty;
        CData/*1:0*/ __PVT__metaAll_s3_3_state;
        CData/*0:0*/ __PVT__metaAll_s3_3_clients;
        CData/*1:0*/ __PVT__metaAll_s3_3_alias;
        CData/*0:0*/ __PVT__metaAll_s3_3_accessed;
        CData/*7:0*/ __PVT__tagAll_s3_0;
        CData/*7:0*/ __PVT__tagAll_s3_1;
        CData/*7:0*/ __PVT__tagAll_s3_2;
        CData/*7:0*/ __PVT__tagAll_s3_3;
        CData/*2:0*/ __PVT__repl_state_s3;
        CData/*0:0*/ __PVT___GEN_89;
        CData/*6:0*/ __PVT___resetIdx_T_1;
        CData/*0:0*/ __PVT__tagArray__DOT__banks_0_io_r_req_valid;
        CData/*0:0*/ __PVT__tagArray__DOT__banks_0_io_w_req_valid;
        CData/*0:0*/ __PVT__tagArray__DOT__banks_1_io_r_req_valid;
        CData/*0:0*/ __PVT__tagArray__DOT__banks_1_io_w_req_valid;
        CData/*0:0*/ __PVT__tagArray__DOT__banks_2_io_r_req_valid;
        CData/*0:0*/ __PVT__tagArray__DOT__banks_2_io_w_req_valid;
        CData/*0:0*/ __PVT__tagArray__DOT__banks_3_io_r_req_valid;
        CData/*0:0*/ __PVT__tagArray__DOT__banks_3_io_w_req_valid;
        CData/*0:0*/ __PVT__tagArray__DOT__banks_4_io_r_req_valid;
        CData/*0:0*/ __PVT__tagArray__DOT__banks_4_io_w_req_valid;
        CData/*0:0*/ __PVT__tagArray__DOT__banks_5_io_r_req_valid;
        CData/*0:0*/ __PVT__tagArray__DOT__banks_5_io_w_req_valid;
        CData/*0:0*/ __PVT__tagArray__DOT__banks_6_io_r_req_valid;
        CData/*0:0*/ __PVT__tagArray__DOT__banks_6_io_w_req_valid;
        CData/*0:0*/ __PVT__tagArray__DOT__banks_7_io_r_req_valid;
        CData/*0:0*/ __PVT__tagArray__DOT__banks_7_io_w_req_valid;
    };
    struct {
        CData/*0:0*/ __PVT__tagArray__DOT__ren_vec_0_0;
        CData/*0:0*/ __PVT__tagArray__DOT__ren_vec_0_2;
        CData/*0:0*/ __PVT__tagArray__DOT__ren_vec_0_3;
        CData/*0:0*/ __PVT__tagArray__DOT__ren_vec_0_4;
        CData/*0:0*/ __PVT__tagArray__DOT__ren_vec___05F0;
        CData/*0:0*/ __PVT__tagArray__DOT__ren_vec___05F1;
        CData/*0:0*/ __PVT__tagArray__DOT__ren_vec___05F2;
        CData/*0:0*/ __PVT__tagArray__DOT__ren_vec___05F3;
        CData/*0:0*/ __PVT__tagArray__DOT__ren_vec___05F4;
        CData/*0:0*/ __PVT__tagArray__DOT__ren_vec___05F5;
        CData/*0:0*/ __PVT__tagArray__DOT__ren_vec___05F6;
        CData/*0:0*/ __PVT__tagArray__DOT__ren_vec___05F7;
        CData/*3:0*/ __PVT__tagArray__DOT__banks_0__DOT__array_0_mem_rdata_addr_pipe_0;
        CData/*3:0*/ __PVT__tagArray__DOT__banks_1__DOT__array_0_mem_rdata_addr_pipe_0;
        CData/*3:0*/ __PVT__tagArray__DOT__banks_2__DOT__array_0_mem_rdata_addr_pipe_0;
        CData/*3:0*/ __PVT__tagArray__DOT__banks_3__DOT__array_0_mem_rdata_addr_pipe_0;
        CData/*3:0*/ __PVT__tagArray__DOT__banks_4__DOT__array_0_mem_rdata_addr_pipe_0;
        CData/*3:0*/ __PVT__tagArray__DOT__banks_5__DOT__array_0_mem_rdata_addr_pipe_0;
        CData/*3:0*/ __PVT__tagArray__DOT__banks_6__DOT__array_0_mem_rdata_addr_pipe_0;
        CData/*3:0*/ __PVT__tagArray__DOT__banks_7__DOT__array_0_mem_rdata_addr_pipe_0;
        CData/*0:0*/ __PVT__metaArray__DOT__banks_0_io_w_req_valid;
        CData/*0:0*/ __PVT__metaArray__DOT__banks_1_io_w_req_valid;
        CData/*0:0*/ __PVT__metaArray__DOT__banks_2_io_w_req_valid;
        CData/*0:0*/ __PVT__metaArray__DOT__banks_3_io_w_req_valid;
        CData/*0:0*/ __PVT__metaArray__DOT__banks_4_io_w_req_valid;
        CData/*0:0*/ __PVT__metaArray__DOT__banks_5_io_w_req_valid;
        CData/*0:0*/ __PVT__metaArray__DOT__banks_6_io_w_req_valid;
        CData/*0:0*/ __PVT__metaArray__DOT__banks_7_io_w_req_valid;
        CData/*0:0*/ __PVT__metaArray__DOT__ren_vec_0_0;
        CData/*0:0*/ __PVT__metaArray__DOT__ren_vec_0_2;
        CData/*0:0*/ __PVT__metaArray__DOT__ren_vec_0_3;
        CData/*0:0*/ __PVT__metaArray__DOT__ren_vec_0_4;
        CData/*0:0*/ __PVT__metaArray__DOT__ren_vec___05F0;
        CData/*0:0*/ __PVT__metaArray__DOT__ren_vec___05F1;
        CData/*0:0*/ __PVT__metaArray__DOT__ren_vec___05F2;
        CData/*0:0*/ __PVT__metaArray__DOT__ren_vec___05F3;
        CData/*0:0*/ __PVT__metaArray__DOT__ren_vec___05F4;
        CData/*0:0*/ __PVT__metaArray__DOT__ren_vec___05F5;
        CData/*0:0*/ __PVT__metaArray__DOT__ren_vec___05F6;
        CData/*0:0*/ __PVT__metaArray__DOT__ren_vec___05F7;
        CData/*6:0*/ __PVT__metaArray__DOT__banks_0__DOT__array_0_MPORT_data;
        CData/*3:0*/ __PVT__metaArray__DOT__banks_0__DOT__array_0_mem_rdata_addr_pipe_0;
        CData/*3:0*/ __PVT__metaArray__DOT__banks_1__DOT__array_0_mem_rdata_addr_pipe_0;
        CData/*3:0*/ __PVT__metaArray__DOT__banks_2__DOT__array_0_mem_rdata_addr_pipe_0;
        CData/*3:0*/ __PVT__metaArray__DOT__banks_3__DOT__array_0_mem_rdata_addr_pipe_0;
        CData/*3:0*/ __PVT__metaArray__DOT__banks_4__DOT__array_0_mem_rdata_addr_pipe_0;
        CData/*3:0*/ __PVT__metaArray__DOT__banks_5__DOT__array_0_mem_rdata_addr_pipe_0;
        CData/*3:0*/ __PVT__metaArray__DOT__banks_6__DOT__array_0_mem_rdata_addr_pipe_0;
        CData/*3:0*/ __PVT__metaArray__DOT__banks_7__DOT__array_0_mem_rdata_addr_pipe_0;
        CData/*0:0*/ __PVT__replacer_sram_opt__DOT__banks_0_io_r_req_ready;
        CData/*0:0*/ __PVT__replacer_sram_opt__DOT__banks_0_io_w_req_valid;
        CData/*0:0*/ __PVT__replacer_sram_opt__DOT__banks_1_io_r_req_ready;
        CData/*0:0*/ __PVT__replacer_sram_opt__DOT__banks_1_io_w_req_valid;
        CData/*0:0*/ __PVT__replacer_sram_opt__DOT__banks_2_io_r_req_ready;
        CData/*0:0*/ __PVT__replacer_sram_opt__DOT__banks_2_io_w_req_valid;
        CData/*0:0*/ __PVT__replacer_sram_opt__DOT__banks_3_io_r_req_ready;
        CData/*0:0*/ __PVT__replacer_sram_opt__DOT__banks_3_io_w_req_valid;
        CData/*0:0*/ __PVT__replacer_sram_opt__DOT__banks_4_io_r_req_ready;
        CData/*0:0*/ __PVT__replacer_sram_opt__DOT__banks_4_io_w_req_valid;
        CData/*0:0*/ __PVT__replacer_sram_opt__DOT__banks_5_io_r_req_ready;
        CData/*0:0*/ __PVT__replacer_sram_opt__DOT__banks_5_io_w_req_valid;
        CData/*0:0*/ __PVT__replacer_sram_opt__DOT__banks_6_io_r_req_ready;
        CData/*0:0*/ __PVT__replacer_sram_opt__DOT__banks_6_io_w_req_valid;
        CData/*0:0*/ __PVT__replacer_sram_opt__DOT__banks_7_io_r_req_ready;
    };
    struct {
        CData/*0:0*/ __PVT__replacer_sram_opt__DOT__banks_7_io_w_req_valid;
        CData/*0:0*/ __PVT__replacer_sram_opt__DOT__ren_vec_0_0;
        CData/*0:0*/ __PVT__replacer_sram_opt__DOT__ren_vec_0_2;
        CData/*0:0*/ __PVT__replacer_sram_opt__DOT__ren_vec_0_3;
        CData/*0:0*/ __PVT__replacer_sram_opt__DOT__ren_vec_0_4;
        CData/*0:0*/ __PVT__replacer_sram_opt__DOT__ren_vec___05F0;
        CData/*0:0*/ __PVT__replacer_sram_opt__DOT__ren_vec___05F1;
        CData/*0:0*/ __PVT__replacer_sram_opt__DOT__ren_vec___05F2;
        CData/*0:0*/ __PVT__replacer_sram_opt__DOT__ren_vec___05F3;
        CData/*0:0*/ __PVT__replacer_sram_opt__DOT__ren_vec___05F4;
        CData/*0:0*/ __PVT__replacer_sram_opt__DOT__ren_vec___05F5;
        CData/*0:0*/ __PVT__replacer_sram_opt__DOT__ren_vec___05F6;
        CData/*0:0*/ __PVT__replacer_sram_opt__DOT__ren_vec___05F7;
        CData/*0:0*/ __PVT__replacer_sram_opt__DOT__banks_0__DOT__array_0_MPORT_en;
        CData/*3:0*/ __PVT__replacer_sram_opt__DOT__banks_0__DOT__array_0_mem_rdata_addr_pipe_0;
        CData/*0:0*/ __PVT__replacer_sram_opt__DOT__banks_0__DOT__resetState;
        CData/*3:0*/ __PVT__replacer_sram_opt__DOT__banks_0__DOT__resetSet;
        CData/*3:0*/ __PVT__replacer_sram_opt__DOT__banks_0__DOT___wrap_value_T_1;
        CData/*0:0*/ __PVT__replacer_sram_opt__DOT__banks_0__DOT___GEN_2;
        CData/*0:0*/ __PVT__replacer_sram_opt__DOT__banks_1__DOT__array_0_MPORT_en;
        CData/*3:0*/ __PVT__replacer_sram_opt__DOT__banks_1__DOT__array_0_mem_rdata_addr_pipe_0;
        CData/*0:0*/ __PVT__replacer_sram_opt__DOT__banks_1__DOT__resetState;
        CData/*3:0*/ __PVT__replacer_sram_opt__DOT__banks_1__DOT__resetSet;
        CData/*3:0*/ __PVT__replacer_sram_opt__DOT__banks_1__DOT___wrap_value_T_1;
        CData/*0:0*/ __PVT__replacer_sram_opt__DOT__banks_1__DOT___GEN_2;
        CData/*0:0*/ __PVT__replacer_sram_opt__DOT__banks_2__DOT__array_0_MPORT_en;
        CData/*3:0*/ __PVT__replacer_sram_opt__DOT__banks_2__DOT__array_0_mem_rdata_addr_pipe_0;
        CData/*0:0*/ __PVT__replacer_sram_opt__DOT__banks_2__DOT__resetState;
        CData/*3:0*/ __PVT__replacer_sram_opt__DOT__banks_2__DOT__resetSet;
        CData/*3:0*/ __PVT__replacer_sram_opt__DOT__banks_2__DOT___wrap_value_T_1;
        CData/*0:0*/ __PVT__replacer_sram_opt__DOT__banks_2__DOT___GEN_2;
        CData/*0:0*/ __PVT__replacer_sram_opt__DOT__banks_3__DOT__array_0_MPORT_en;
        CData/*3:0*/ __PVT__replacer_sram_opt__DOT__banks_3__DOT__array_0_mem_rdata_addr_pipe_0;
        CData/*0:0*/ __PVT__replacer_sram_opt__DOT__banks_3__DOT__resetState;
        CData/*3:0*/ __PVT__replacer_sram_opt__DOT__banks_3__DOT__resetSet;
        CData/*3:0*/ __PVT__replacer_sram_opt__DOT__banks_3__DOT___wrap_value_T_1;
        CData/*0:0*/ __PVT__replacer_sram_opt__DOT__banks_3__DOT___GEN_2;
        CData/*0:0*/ __PVT__replacer_sram_opt__DOT__banks_4__DOT__array_0_MPORT_en;
        CData/*3:0*/ __PVT__replacer_sram_opt__DOT__banks_4__DOT__array_0_mem_rdata_addr_pipe_0;
        CData/*0:0*/ __PVT__replacer_sram_opt__DOT__banks_4__DOT__resetState;
        CData/*3:0*/ __PVT__replacer_sram_opt__DOT__banks_4__DOT__resetSet;
        CData/*3:0*/ __PVT__replacer_sram_opt__DOT__banks_4__DOT___wrap_value_T_1;
        CData/*0:0*/ __PVT__replacer_sram_opt__DOT__banks_4__DOT___GEN_2;
        CData/*0:0*/ __PVT__replacer_sram_opt__DOT__banks_5__DOT__array_0_MPORT_en;
        CData/*3:0*/ __PVT__replacer_sram_opt__DOT__banks_5__DOT__array_0_mem_rdata_addr_pipe_0;
        CData/*0:0*/ __PVT__replacer_sram_opt__DOT__banks_5__DOT__resetState;
        CData/*3:0*/ __PVT__replacer_sram_opt__DOT__banks_5__DOT__resetSet;
        CData/*3:0*/ __PVT__replacer_sram_opt__DOT__banks_5__DOT___wrap_value_T_1;
        CData/*0:0*/ __PVT__replacer_sram_opt__DOT__banks_5__DOT___GEN_2;
        CData/*0:0*/ __PVT__replacer_sram_opt__DOT__banks_6__DOT__array_0_MPORT_en;
        CData/*3:0*/ __PVT__replacer_sram_opt__DOT__banks_6__DOT__array_0_mem_rdata_addr_pipe_0;
        CData/*0:0*/ __PVT__replacer_sram_opt__DOT__banks_6__DOT__resetState;
        CData/*3:0*/ __PVT__replacer_sram_opt__DOT__banks_6__DOT__resetSet;
        CData/*3:0*/ __PVT__replacer_sram_opt__DOT__banks_6__DOT___wrap_value_T_1;
        CData/*0:0*/ __PVT__replacer_sram_opt__DOT__banks_6__DOT___GEN_2;
        CData/*0:0*/ __PVT__replacer_sram_opt__DOT__banks_7__DOT__array_0_MPORT_en;
        CData/*3:0*/ __PVT__replacer_sram_opt__DOT__banks_7__DOT__array_0_mem_rdata_addr_pipe_0;
        CData/*0:0*/ __PVT__replacer_sram_opt__DOT__banks_7__DOT__resetState;
        CData/*3:0*/ __PVT__replacer_sram_opt__DOT__banks_7__DOT__resetSet;
        CData/*3:0*/ __PVT__replacer_sram_opt__DOT__banks_7__DOT___wrap_value_T_1;
        CData/*0:0*/ __PVT__replacer_sram_opt__DOT__banks_7__DOT___GEN_2;
        VlUnpacked<CData/*7:0*/, 16> __PVT__tagArray__DOT__banks_0__DOT__array_0;
        VlUnpacked<CData/*7:0*/, 16> __PVT__tagArray__DOT__banks_0__DOT__array_1;
        VlUnpacked<CData/*7:0*/, 16> __PVT__tagArray__DOT__banks_0__DOT__array_2;
    };
    struct {
        VlUnpacked<CData/*7:0*/, 16> __PVT__tagArray__DOT__banks_0__DOT__array_3;
        VlUnpacked<CData/*7:0*/, 16> __PVT__tagArray__DOT__banks_1__DOT__array_0;
        VlUnpacked<CData/*7:0*/, 16> __PVT__tagArray__DOT__banks_1__DOT__array_1;
        VlUnpacked<CData/*7:0*/, 16> __PVT__tagArray__DOT__banks_1__DOT__array_2;
        VlUnpacked<CData/*7:0*/, 16> __PVT__tagArray__DOT__banks_1__DOT__array_3;
        VlUnpacked<CData/*7:0*/, 16> __PVT__tagArray__DOT__banks_2__DOT__array_0;
        VlUnpacked<CData/*7:0*/, 16> __PVT__tagArray__DOT__banks_2__DOT__array_1;
        VlUnpacked<CData/*7:0*/, 16> __PVT__tagArray__DOT__banks_2__DOT__array_2;
        VlUnpacked<CData/*7:0*/, 16> __PVT__tagArray__DOT__banks_2__DOT__array_3;
        VlUnpacked<CData/*7:0*/, 16> __PVT__tagArray__DOT__banks_3__DOT__array_0;
        VlUnpacked<CData/*7:0*/, 16> __PVT__tagArray__DOT__banks_3__DOT__array_1;
        VlUnpacked<CData/*7:0*/, 16> __PVT__tagArray__DOT__banks_3__DOT__array_2;
        VlUnpacked<CData/*7:0*/, 16> __PVT__tagArray__DOT__banks_3__DOT__array_3;
        VlUnpacked<CData/*7:0*/, 16> __PVT__tagArray__DOT__banks_4__DOT__array_0;
        VlUnpacked<CData/*7:0*/, 16> __PVT__tagArray__DOT__banks_4__DOT__array_1;
        VlUnpacked<CData/*7:0*/, 16> __PVT__tagArray__DOT__banks_4__DOT__array_2;
        VlUnpacked<CData/*7:0*/, 16> __PVT__tagArray__DOT__banks_4__DOT__array_3;
        VlUnpacked<CData/*7:0*/, 16> __PVT__tagArray__DOT__banks_5__DOT__array_0;
        VlUnpacked<CData/*7:0*/, 16> __PVT__tagArray__DOT__banks_5__DOT__array_1;
        VlUnpacked<CData/*7:0*/, 16> __PVT__tagArray__DOT__banks_5__DOT__array_2;
        VlUnpacked<CData/*7:0*/, 16> __PVT__tagArray__DOT__banks_5__DOT__array_3;
        VlUnpacked<CData/*7:0*/, 16> __PVT__tagArray__DOT__banks_6__DOT__array_0;
        VlUnpacked<CData/*7:0*/, 16> __PVT__tagArray__DOT__banks_6__DOT__array_1;
        VlUnpacked<CData/*7:0*/, 16> __PVT__tagArray__DOT__banks_6__DOT__array_2;
        VlUnpacked<CData/*7:0*/, 16> __PVT__tagArray__DOT__banks_6__DOT__array_3;
        VlUnpacked<CData/*7:0*/, 16> __PVT__tagArray__DOT__banks_7__DOT__array_0;
        VlUnpacked<CData/*7:0*/, 16> __PVT__tagArray__DOT__banks_7__DOT__array_1;
        VlUnpacked<CData/*7:0*/, 16> __PVT__tagArray__DOT__banks_7__DOT__array_2;
        VlUnpacked<CData/*7:0*/, 16> __PVT__tagArray__DOT__banks_7__DOT__array_3;
        VlUnpacked<CData/*6:0*/, 16> __PVT__metaArray__DOT__banks_0__DOT__array_0;
        VlUnpacked<CData/*6:0*/, 16> __PVT__metaArray__DOT__banks_0__DOT__array_1;
        VlUnpacked<CData/*6:0*/, 16> __PVT__metaArray__DOT__banks_0__DOT__array_2;
        VlUnpacked<CData/*6:0*/, 16> __PVT__metaArray__DOT__banks_0__DOT__array_3;
        VlUnpacked<CData/*6:0*/, 16> __PVT__metaArray__DOT__banks_1__DOT__array_0;
        VlUnpacked<CData/*6:0*/, 16> __PVT__metaArray__DOT__banks_1__DOT__array_1;
        VlUnpacked<CData/*6:0*/, 16> __PVT__metaArray__DOT__banks_1__DOT__array_2;
        VlUnpacked<CData/*6:0*/, 16> __PVT__metaArray__DOT__banks_1__DOT__array_3;
        VlUnpacked<CData/*6:0*/, 16> __PVT__metaArray__DOT__banks_2__DOT__array_0;
        VlUnpacked<CData/*6:0*/, 16> __PVT__metaArray__DOT__banks_2__DOT__array_1;
        VlUnpacked<CData/*6:0*/, 16> __PVT__metaArray__DOT__banks_2__DOT__array_2;
        VlUnpacked<CData/*6:0*/, 16> __PVT__metaArray__DOT__banks_2__DOT__array_3;
        VlUnpacked<CData/*6:0*/, 16> __PVT__metaArray__DOT__banks_3__DOT__array_0;
        VlUnpacked<CData/*6:0*/, 16> __PVT__metaArray__DOT__banks_3__DOT__array_1;
        VlUnpacked<CData/*6:0*/, 16> __PVT__metaArray__DOT__banks_3__DOT__array_2;
        VlUnpacked<CData/*6:0*/, 16> __PVT__metaArray__DOT__banks_3__DOT__array_3;
        VlUnpacked<CData/*6:0*/, 16> __PVT__metaArray__DOT__banks_4__DOT__array_0;
        VlUnpacked<CData/*6:0*/, 16> __PVT__metaArray__DOT__banks_4__DOT__array_1;
        VlUnpacked<CData/*6:0*/, 16> __PVT__metaArray__DOT__banks_4__DOT__array_2;
        VlUnpacked<CData/*6:0*/, 16> __PVT__metaArray__DOT__banks_4__DOT__array_3;
        VlUnpacked<CData/*6:0*/, 16> __PVT__metaArray__DOT__banks_5__DOT__array_0;
        VlUnpacked<CData/*6:0*/, 16> __PVT__metaArray__DOT__banks_5__DOT__array_1;
        VlUnpacked<CData/*6:0*/, 16> __PVT__metaArray__DOT__banks_5__DOT__array_2;
        VlUnpacked<CData/*6:0*/, 16> __PVT__metaArray__DOT__banks_5__DOT__array_3;
        VlUnpacked<CData/*6:0*/, 16> __PVT__metaArray__DOT__banks_6__DOT__array_0;
        VlUnpacked<CData/*6:0*/, 16> __PVT__metaArray__DOT__banks_6__DOT__array_1;
        VlUnpacked<CData/*6:0*/, 16> __PVT__metaArray__DOT__banks_6__DOT__array_2;
        VlUnpacked<CData/*6:0*/, 16> __PVT__metaArray__DOT__banks_6__DOT__array_3;
        VlUnpacked<CData/*6:0*/, 16> __PVT__metaArray__DOT__banks_7__DOT__array_0;
        VlUnpacked<CData/*6:0*/, 16> __PVT__metaArray__DOT__banks_7__DOT__array_1;
        VlUnpacked<CData/*6:0*/, 16> __PVT__metaArray__DOT__banks_7__DOT__array_2;
        VlUnpacked<CData/*6:0*/, 16> __PVT__metaArray__DOT__banks_7__DOT__array_3;
        VlUnpacked<CData/*2:0*/, 16> __PVT__replacer_sram_opt__DOT__banks_0__DOT__array_0;
        VlUnpacked<CData/*2:0*/, 16> __PVT__replacer_sram_opt__DOT__banks_1__DOT__array_0;
        VlUnpacked<CData/*2:0*/, 16> __PVT__replacer_sram_opt__DOT__banks_2__DOT__array_0;
    };
    struct {
        VlUnpacked<CData/*2:0*/, 16> __PVT__replacer_sram_opt__DOT__banks_3__DOT__array_0;
        VlUnpacked<CData/*2:0*/, 16> __PVT__replacer_sram_opt__DOT__banks_4__DOT__array_0;
        VlUnpacked<CData/*2:0*/, 16> __PVT__replacer_sram_opt__DOT__banks_5__DOT__array_0;
        VlUnpacked<CData/*2:0*/, 16> __PVT__replacer_sram_opt__DOT__banks_6__DOT__array_0;
        VlUnpacked<CData/*2:0*/, 16> __PVT__replacer_sram_opt__DOT__banks_7__DOT__array_0;
    };

    // INTERNAL VARIABLES
    VTestTop_L2L3L2__Syms* const vlSymsp;

    // CONSTRUCTORS
    VTestTop_L2L3L2_Directory(VTestTop_L2L3L2__Syms* symsp, const char* v__name);
    ~VTestTop_L2L3L2_Directory();
    VL_UNCOPYABLE(VTestTop_L2L3L2_Directory);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
