// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See VTestTop_L2L3L2.h for the primary calling header

#ifndef VERILATED_VTESTTOP_L2L3L2_REQUESTBUFFER_H_
#define VERILATED_VTESTTOP_L2L3L2_REQUESTBUFFER_H_  // guard

#include "verilated.h"


class VTestTop_L2L3L2__Syms;

class alignas(VL_CACHE_LINE_BYTES) VTestTop_L2L3L2_RequestBuffer final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clock,0,0);
        VL_IN8(reset,0,0);
        VL_OUT8(io_in_ready,0,0);
        VL_IN8(io_in_valid,0,0);
        VL_IN8(io_in_bits_set,6,0);
        VL_IN8(io_in_bits_tag,7,0);
        VL_IN8(io_in_bits_off,0,0);
        VL_IN8(io_in_bits_alias,1,0);
        VL_IN8(io_in_bits_opcode,2,0);
        VL_IN8(io_in_bits_param,2,0);
        VL_IN8(io_in_bits_size,0,0);
        VL_IN8(io_in_bits_sourceId,4,0);
        VL_IN8(io_out_ready,0,0);
        VL_OUT8(io_out_valid,0,0);
        VL_OUT8(io_out_bits_channel,2,0);
        VL_OUT8(io_out_bits_set,6,0);
        VL_OUT8(io_out_bits_tag,7,0);
        VL_OUT8(io_out_bits_off,0,0);
        VL_OUT8(io_out_bits_alias,1,0);
        VL_OUT8(io_out_bits_opcode,2,0);
        VL_OUT8(io_out_bits_param,2,0);
        VL_OUT8(io_out_bits_size,0,0);
        VL_OUT8(io_out_bits_sourceId,4,0);
        VL_OUT8(io_out_bits_bufIdx,1,0);
        VL_OUT8(io_out_bits_needProbeAckData,0,0);
        VL_OUT8(io_out_bits_mshrTask,0,0);
        VL_OUT8(io_out_bits_mshrId,7,0);
        VL_OUT8(io_out_bits_aliasTask,0,0);
        VL_OUT8(io_out_bits_useProbeData,0,0);
        VL_OUT8(io_out_bits_dirty,0,0);
        VL_OUT8(io_out_bits_way,1,0);
        VL_OUT8(io_out_bits_meta_dirty,0,0);
        VL_OUT8(io_out_bits_meta_state,1,0);
        VL_OUT8(io_out_bits_meta_clients,0,0);
        VL_OUT8(io_out_bits_meta_alias,1,0);
        VL_OUT8(io_out_bits_meta_accessed,0,0);
        VL_OUT8(io_out_bits_metaWen,0,0);
        VL_OUT8(io_out_bits_tagWen,0,0);
        VL_OUT8(io_out_bits_dsWen,0,0);
        VL_OUT8(io_out_bits_replTask,0,0);
        VL_OUT8(io_out_bits_reqSource,3,0);
        VL_IN8(io_mshrInfo_0_valid,0,0);
        VL_IN8(io_mshrInfo_0_bits_set,6,0);
        VL_IN8(io_mshrInfo_0_bits_reqTag,7,0);
        VL_IN8(io_mshrInfo_0_bits_willFree,0,0);
        VL_IN8(io_mshrInfo_0_bits_needRelease,0,0);
        VL_IN8(io_mshrInfo_0_bits_metaTag,7,0);
        VL_IN8(io_mshrInfo_0_bits_isAcqOrPrefetch,0,0);
        VL_IN8(io_mshrInfo_0_bits_isPrefetch,0,0);
        VL_IN8(io_mshrInfo_1_valid,0,0);
        VL_IN8(io_mshrInfo_1_bits_set,6,0);
        VL_IN8(io_mshrInfo_1_bits_reqTag,7,0);
        VL_IN8(io_mshrInfo_1_bits_willFree,0,0);
        VL_IN8(io_mshrInfo_1_bits_needRelease,0,0);
        VL_IN8(io_mshrInfo_1_bits_metaTag,7,0);
        VL_IN8(io_mshrInfo_1_bits_isAcqOrPrefetch,0,0);
        VL_IN8(io_mshrInfo_1_bits_isPrefetch,0,0);
        VL_IN8(io_mshrInfo_2_valid,0,0);
        VL_IN8(io_mshrInfo_2_bits_set,6,0);
        VL_IN8(io_mshrInfo_2_bits_reqTag,7,0);
        VL_IN8(io_mshrInfo_2_bits_willFree,0,0);
        VL_IN8(io_mshrInfo_2_bits_needRelease,0,0);
        VL_IN8(io_mshrInfo_2_bits_metaTag,7,0);
        VL_IN8(io_mshrInfo_2_bits_isAcqOrPrefetch,0,0);
    };
    struct {
        VL_IN8(io_mshrInfo_2_bits_isPrefetch,0,0);
        VL_IN8(io_mshrInfo_3_valid,0,0);
        VL_IN8(io_mshrInfo_3_bits_set,6,0);
        VL_IN8(io_mshrInfo_3_bits_reqTag,7,0);
        VL_IN8(io_mshrInfo_3_bits_willFree,0,0);
        VL_IN8(io_mshrInfo_3_bits_needRelease,0,0);
        VL_IN8(io_mshrInfo_3_bits_metaTag,7,0);
        VL_IN8(io_mshrInfo_3_bits_isAcqOrPrefetch,0,0);
        VL_IN8(io_mshrInfo_3_bits_isPrefetch,0,0);
        VL_IN8(io_mshrInfo_4_valid,0,0);
        VL_IN8(io_mshrInfo_4_bits_set,6,0);
        VL_IN8(io_mshrInfo_4_bits_reqTag,7,0);
        VL_IN8(io_mshrInfo_4_bits_willFree,0,0);
        VL_IN8(io_mshrInfo_4_bits_needRelease,0,0);
        VL_IN8(io_mshrInfo_4_bits_metaTag,7,0);
        VL_IN8(io_mshrInfo_4_bits_isAcqOrPrefetch,0,0);
        VL_IN8(io_mshrInfo_4_bits_isPrefetch,0,0);
        VL_IN8(io_mshrInfo_5_valid,0,0);
        VL_IN8(io_mshrInfo_5_bits_set,6,0);
        VL_IN8(io_mshrInfo_5_bits_reqTag,7,0);
        VL_IN8(io_mshrInfo_5_bits_willFree,0,0);
        VL_IN8(io_mshrInfo_5_bits_needRelease,0,0);
        VL_IN8(io_mshrInfo_5_bits_metaTag,7,0);
        VL_IN8(io_mshrInfo_5_bits_isAcqOrPrefetch,0,0);
        VL_IN8(io_mshrInfo_5_bits_isPrefetch,0,0);
        VL_IN8(io_mshrInfo_6_valid,0,0);
        VL_IN8(io_mshrInfo_6_bits_set,6,0);
        VL_IN8(io_mshrInfo_6_bits_reqTag,7,0);
        VL_IN8(io_mshrInfo_6_bits_willFree,0,0);
        VL_IN8(io_mshrInfo_6_bits_needRelease,0,0);
        VL_IN8(io_mshrInfo_6_bits_metaTag,7,0);
        VL_IN8(io_mshrInfo_6_bits_isAcqOrPrefetch,0,0);
        VL_IN8(io_mshrInfo_6_bits_isPrefetch,0,0);
        VL_IN8(io_mshrInfo_7_valid,0,0);
        VL_IN8(io_mshrInfo_7_bits_set,6,0);
        VL_IN8(io_mshrInfo_7_bits_reqTag,7,0);
        VL_IN8(io_mshrInfo_7_bits_willFree,0,0);
        VL_IN8(io_mshrInfo_7_bits_needRelease,0,0);
        VL_IN8(io_mshrInfo_7_bits_metaTag,7,0);
        VL_IN8(io_mshrInfo_7_bits_isAcqOrPrefetch,0,0);
        VL_IN8(io_mshrInfo_7_bits_isPrefetch,0,0);
        VL_IN8(io_mshrInfo_8_valid,0,0);
        VL_IN8(io_mshrInfo_8_bits_set,6,0);
        VL_IN8(io_mshrInfo_8_bits_reqTag,7,0);
        VL_IN8(io_mshrInfo_8_bits_willFree,0,0);
        VL_IN8(io_mshrInfo_8_bits_needRelease,0,0);
        VL_IN8(io_mshrInfo_8_bits_metaTag,7,0);
        VL_IN8(io_mshrInfo_8_bits_isAcqOrPrefetch,0,0);
        VL_IN8(io_mshrInfo_8_bits_isPrefetch,0,0);
        VL_IN8(io_mshrInfo_9_valid,0,0);
        VL_IN8(io_mshrInfo_9_bits_set,6,0);
        VL_IN8(io_mshrInfo_9_bits_reqTag,7,0);
        VL_IN8(io_mshrInfo_9_bits_willFree,0,0);
        VL_IN8(io_mshrInfo_9_bits_needRelease,0,0);
        VL_IN8(io_mshrInfo_9_bits_metaTag,7,0);
        VL_IN8(io_mshrInfo_9_bits_isAcqOrPrefetch,0,0);
        VL_IN8(io_mshrInfo_9_bits_isPrefetch,0,0);
        VL_IN8(io_mshrInfo_10_valid,0,0);
        VL_IN8(io_mshrInfo_10_bits_set,6,0);
        VL_IN8(io_mshrInfo_10_bits_reqTag,7,0);
        VL_IN8(io_mshrInfo_10_bits_willFree,0,0);
        VL_IN8(io_mshrInfo_10_bits_needRelease,0,0);
        VL_IN8(io_mshrInfo_10_bits_metaTag,7,0);
        VL_IN8(io_mshrInfo_10_bits_isAcqOrPrefetch,0,0);
    };
    struct {
        VL_IN8(io_mshrInfo_10_bits_isPrefetch,0,0);
        VL_IN8(io_mshrInfo_11_valid,0,0);
        VL_IN8(io_mshrInfo_11_bits_set,6,0);
        VL_IN8(io_mshrInfo_11_bits_reqTag,7,0);
        VL_IN8(io_mshrInfo_11_bits_willFree,0,0);
        VL_IN8(io_mshrInfo_11_bits_needRelease,0,0);
        VL_IN8(io_mshrInfo_11_bits_metaTag,7,0);
        VL_IN8(io_mshrInfo_11_bits_isAcqOrPrefetch,0,0);
        VL_IN8(io_mshrInfo_11_bits_isPrefetch,0,0);
        VL_IN8(io_mshrInfo_12_valid,0,0);
        VL_IN8(io_mshrInfo_12_bits_set,6,0);
        VL_IN8(io_mshrInfo_12_bits_reqTag,7,0);
        VL_IN8(io_mshrInfo_12_bits_willFree,0,0);
        VL_IN8(io_mshrInfo_12_bits_needRelease,0,0);
        VL_IN8(io_mshrInfo_12_bits_metaTag,7,0);
        VL_IN8(io_mshrInfo_12_bits_isAcqOrPrefetch,0,0);
        VL_IN8(io_mshrInfo_12_bits_isPrefetch,0,0);
        VL_IN8(io_mshrInfo_13_valid,0,0);
        VL_IN8(io_mshrInfo_13_bits_set,6,0);
        VL_IN8(io_mshrInfo_13_bits_reqTag,7,0);
        VL_IN8(io_mshrInfo_13_bits_willFree,0,0);
        VL_IN8(io_mshrInfo_13_bits_needRelease,0,0);
        VL_IN8(io_mshrInfo_13_bits_metaTag,7,0);
        VL_IN8(io_mshrInfo_13_bits_isAcqOrPrefetch,0,0);
        VL_IN8(io_mshrInfo_13_bits_isPrefetch,0,0);
        VL_IN8(io_mshrInfo_14_valid,0,0);
        VL_IN8(io_mshrInfo_14_bits_set,6,0);
        VL_IN8(io_mshrInfo_14_bits_reqTag,7,0);
        VL_IN8(io_mshrInfo_14_bits_willFree,0,0);
        VL_IN8(io_mshrInfo_14_bits_needRelease,0,0);
        VL_IN8(io_mshrInfo_14_bits_metaTag,7,0);
        VL_IN8(io_mshrInfo_14_bits_isAcqOrPrefetch,0,0);
        VL_IN8(io_mshrInfo_14_bits_isPrefetch,0,0);
        VL_IN8(io_mshrInfo_15_valid,0,0);
        VL_IN8(io_mshrInfo_15_bits_set,6,0);
        VL_IN8(io_mshrInfo_15_bits_reqTag,7,0);
        VL_IN8(io_mshrInfo_15_bits_willFree,0,0);
        VL_IN8(io_mshrInfo_15_bits_needRelease,0,0);
        VL_IN8(io_mshrInfo_15_bits_metaTag,7,0);
        VL_IN8(io_mshrInfo_15_bits_isAcqOrPrefetch,0,0);
        VL_IN8(io_mshrInfo_15_bits_isPrefetch,0,0);
        VL_IN8(io_mainPipeBlock_0,0,0);
        VL_IN8(io_mainPipeBlock_1,0,0);
        VL_OUT8(io_ATag,7,0);
        VL_OUT8(io_ASet,6,0);
        VL_IN8(io_s1Entrance_valid,0,0);
        VL_IN8(io_s1Entrance_bits_set,6,0);
        VL_OUT8(io_hasLatePF,0,0);
        CData/*0:0*/ __PVT__buffer_0_valid;
        CData/*0:0*/ __PVT__buffer_0_rdy;
        CData/*2:0*/ __PVT__buffer_0_task_channel;
        CData/*6:0*/ __PVT__buffer_0_task_set;
        CData/*7:0*/ __PVT__buffer_0_task_tag;
        CData/*0:0*/ __PVT__buffer_0_task_off;
        CData/*1:0*/ __PVT__buffer_0_task_alias;
        CData/*2:0*/ __PVT__buffer_0_task_opcode;
        CData/*2:0*/ __PVT__buffer_0_task_param;
        CData/*0:0*/ __PVT__buffer_0_task_size;
        CData/*4:0*/ __PVT__buffer_0_task_sourceId;
        CData/*3:0*/ __PVT__buffer_0_waitMP;
        CData/*0:0*/ __PVT__buffer_1_valid;
        CData/*0:0*/ __PVT__buffer_1_rdy;
        CData/*2:0*/ __PVT__buffer_1_task_channel;
        CData/*6:0*/ __PVT__buffer_1_task_set;
    };
    struct {
        CData/*7:0*/ __PVT__buffer_1_task_tag;
        CData/*0:0*/ __PVT__buffer_1_task_off;
        CData/*1:0*/ __PVT__buffer_1_task_alias;
        CData/*2:0*/ __PVT__buffer_1_task_opcode;
        CData/*2:0*/ __PVT__buffer_1_task_param;
        CData/*0:0*/ __PVT__buffer_1_task_size;
        CData/*4:0*/ __PVT__buffer_1_task_sourceId;
        CData/*3:0*/ __PVT__buffer_1_waitMP;
        CData/*0:0*/ __PVT__buffer_2_valid;
        CData/*0:0*/ __PVT__buffer_2_rdy;
        CData/*2:0*/ __PVT__buffer_2_task_channel;
        CData/*6:0*/ __PVT__buffer_2_task_set;
        CData/*7:0*/ __PVT__buffer_2_task_tag;
        CData/*0:0*/ __PVT__buffer_2_task_off;
        CData/*1:0*/ __PVT__buffer_2_task_alias;
        CData/*2:0*/ __PVT__buffer_2_task_opcode;
        CData/*2:0*/ __PVT__buffer_2_task_param;
        CData/*0:0*/ __PVT__buffer_2_task_size;
        CData/*4:0*/ __PVT__buffer_2_task_sourceId;
        CData/*3:0*/ __PVT__buffer_2_waitMP;
        CData/*0:0*/ __PVT__buffer_3_valid;
        CData/*0:0*/ __PVT__buffer_3_rdy;
        CData/*2:0*/ __PVT__buffer_3_task_channel;
        CData/*6:0*/ __PVT__buffer_3_task_set;
        CData/*7:0*/ __PVT__buffer_3_task_tag;
        CData/*0:0*/ __PVT__buffer_3_task_off;
        CData/*1:0*/ __PVT__buffer_3_task_alias;
        CData/*2:0*/ __PVT__buffer_3_task_opcode;
        CData/*2:0*/ __PVT__buffer_3_task_param;
        CData/*0:0*/ __PVT__buffer_3_task_size;
        CData/*4:0*/ __PVT__buffer_3_task_sourceId;
        CData/*3:0*/ __PVT__buffer_3_waitMP;
        CData/*0:0*/ __PVT___canFlow_T;
        CData/*0:0*/ __PVT___canFlow_T_154;
        CData/*0:0*/ __PVT__canFlow;
        CData/*0:0*/ __PVT__doFlow;
        CData/*0:0*/ __PVT___io_hasLatePF_T_3;
        CData/*0:0*/ __PVT___io_hasLatePF_T_17;
        CData/*0:0*/ __PVT___io_hasLatePF_T_31;
        CData/*0:0*/ __PVT___io_hasLatePF_T_45;
        CData/*0:0*/ __PVT___io_hasLatePF_T_59;
        CData/*0:0*/ __PVT___io_hasLatePF_T_73;
        CData/*0:0*/ __PVT___io_hasLatePF_T_87;
        CData/*0:0*/ __PVT___io_hasLatePF_T_101;
        CData/*0:0*/ __PVT___io_hasLatePF_T_115;
        CData/*0:0*/ __PVT___io_hasLatePF_T_129;
        CData/*0:0*/ __PVT___io_hasLatePF_T_143;
        CData/*0:0*/ __PVT___io_hasLatePF_T_157;
        CData/*0:0*/ __PVT___io_hasLatePF_T_171;
        CData/*0:0*/ __PVT___io_hasLatePF_T_185;
        CData/*0:0*/ __PVT___io_hasLatePF_T_199;
        CData/*0:0*/ __PVT___io_hasLatePF_T_213;
        CData/*6:0*/ __PVT__io_hasLatePF_REG_set;
        CData/*7:0*/ __PVT__io_hasLatePF_REG_tag;
        CData/*1:0*/ __PVT__insertIdx;
        CData/*0:0*/ __PVT__alloc;
        CData/*0:0*/ __PVT__s1Block;
        CData/*3:0*/ __PVT___buffer_waitMP_T;
        CData/*0:0*/ __PVT___GEN_128;
        CData/*0:0*/ __PVT___GEN_129;
        CData/*0:0*/ __PVT___GEN_130;
        CData/*0:0*/ __PVT___GEN_131;
        CData/*0:0*/ __PVT___pipeBlockOut_T_2;
        CData/*0:0*/ __PVT___pipeBlockOut_T_3;
    };
    struct {
        CData/*0:0*/ __PVT___pipeBlockOut_T_4;
        CData/*0:0*/ __PVT___pipeBlockOut_T_5;
        CData/*3:0*/ __PVT___buffer_0_waitMP_T;
        CData/*0:0*/ __PVT__s1_Block;
        CData/*3:0*/ __PVT___buffer_0_waitMP_T_1;
        CData/*3:0*/ __PVT___buffer_1_waitMP_T;
        CData/*0:0*/ __PVT__s1_Block_1;
        CData/*3:0*/ __PVT___buffer_1_waitMP_T_1;
        CData/*3:0*/ __PVT___buffer_2_waitMP_T;
        CData/*0:0*/ __PVT__s1_Block_2;
        CData/*3:0*/ __PVT___buffer_2_waitMP_T_1;
        CData/*3:0*/ __PVT___buffer_3_waitMP_T;
        CData/*0:0*/ __PVT__s1_Block_3;
        CData/*3:0*/ __PVT___buffer_3_waitMP_T_1;
        CData/*0:0*/ __PVT___io_out_valid_T;
        CData/*0:0*/ __PVT__REG;
        CData/*0:0*/ __PVT__REG_1;
        CData/*0:0*/ __PVT__REG_2;
        CData/*0:0*/ __PVT__REG_3;
        CData/*0:0*/ __PVT__REG_4;
        CData/*0:0*/ __PVT__REG_5;
        CData/*0:0*/ __PVT__REG_6;
        CData/*0:0*/ __PVT__REG_7;
        CData/*0:0*/ __VdfgRegularize_ha1527a7f_2_0;
        CData/*3:0*/ __PVT__issueArb__DOT__valids;
        CData/*3:0*/ __PVT__issueArb__DOT__rrGrantMask;
        CData/*3:0*/ __PVT__issueArb__DOT__pendingMask;
        CData/*3:0*/ __PVT__issueArb__DOT__rrSelOH;
        CData/*3:0*/ __PVT__issueArb__DOT__chosenOH;
        CData/*0:0*/ __PVT__issueArb__DOT___pendingMask_T_2;
        CData/*0:0*/ __PVT__chosenQ__DOT__maybe_full;
        CData/*0:0*/ __PVT__chosenQ__DOT__do_deq;
        CData/*0:0*/ __VdlySet__chosenQ__DOT__ram_bits_task_metaWen__v0;
        CData/*0:0*/ __VdlySet__chosenQ__DOT__ram_bits_task_meta_accessed__v0;
        CData/*0:0*/ __VdlySet__chosenQ__DOT__ram_bits_task_meta_alias__v0;
        CData/*0:0*/ __VdlySet__chosenQ__DOT__ram_bits_task_meta_clients__v0;
        CData/*0:0*/ __VdlySet__chosenQ__DOT__ram_bits_task_way__v0;
        CData/*0:0*/ __VdlySet__chosenQ__DOT__ram_bits_task_dirty__v0;
        CData/*0:0*/ __VdlySet__chosenQ__DOT__ram_bits_task_useProbeData__v0;
        CData/*0:0*/ __VdlySet__chosenQ__DOT__ram_bits_task_mshrTask__v0;
        CData/*0:0*/ __VdlyVal__chosenQ__DOT__ram_bits_task_off__v0;
        CData/*0:0*/ __VdlySet__chosenQ__DOT__ram_bits_task_off__v0;
        CData/*0:0*/ __VdlySet__chosenQ__DOT__ram_bits_task_tagWen__v0;
        CData/*1:0*/ __VdlyVal__chosenQ__DOT__ram_bits_task_alias__v0;
        CData/*0:0*/ __VdlySet__chosenQ__DOT__ram_bits_task_alias__v0;
        CData/*0:0*/ __VdlySet__chosenQ__DOT__ram_bits_task_meta_dirty__v0;
        CData/*2:0*/ __VdlyVal__chosenQ__DOT__ram_bits_task_param__v0;
        CData/*0:0*/ __VdlySet__chosenQ__DOT__ram_bits_task_param__v0;
        CData/*0:0*/ __VdlySet__chosenQ__DOT__ram_bits_task_meta_state__v0;
        CData/*4:0*/ __VdlyVal__chosenQ__DOT__ram_bits_task_sourceId__v0;
        CData/*0:0*/ __VdlySet__chosenQ__DOT__ram_bits_task_sourceId__v0;
        CData/*0:0*/ __VdlySet__chosenQ__DOT__ram_bits_task_bufIdx__v0;
        CData/*0:0*/ __VdlySet__chosenQ__DOT__ram_bits_task_needProbeAckData__v0;
        CData/*0:0*/ __VdlySet__chosenQ__DOT__ram_bits_task_dsWen__v0;
        CData/*0:0*/ __VdlySet__chosenQ__DOT__ram_bits_task_replTask__v0;
        SData/*15:0*/ __PVT__buffer_0_waitMS;
        SData/*15:0*/ __PVT__buffer_1_waitMS;
        SData/*15:0*/ __PVT__buffer_2_waitMS;
        SData/*15:0*/ __PVT__buffer_3_waitMS;
        SData/*15:0*/ __PVT___canFlow_T_146;
        SData/*14:0*/ __PVT___io_hasLatePF_T_1;
        SData/*15:0*/ __PVT___waitMSUpdate_T_1;
        SData/*15:0*/ __PVT___waitMSUpdate_T_146;
        SData/*15:0*/ __PVT__waitMSUpdate;
    };
    struct {
        SData/*15:0*/ __PVT___waitMSUpdate_T_148;
        SData/*15:0*/ __PVT___waitMSUpdate_T_293;
        SData/*15:0*/ __PVT__waitMSUpdate_1;
        SData/*15:0*/ __PVT___waitMSUpdate_T_295;
        SData/*15:0*/ __PVT___waitMSUpdate_T_440;
        SData/*15:0*/ __PVT__waitMSUpdate_2;
        SData/*15:0*/ __PVT___waitMSUpdate_T_442;
        SData/*15:0*/ __PVT___waitMSUpdate_T_587;
        SData/*15:0*/ __PVT__waitMSUpdate_3;
        SData/*15:0*/ __PVT__bufferTimer_0;
        SData/*15:0*/ __PVT__bufferTimer_1;
        SData/*15:0*/ __PVT__bufferTimer_2;
        SData/*15:0*/ __PVT__bufferTimer_3;
        SData/*15:0*/ __PVT___bufferTimer_0_T_1;
        SData/*15:0*/ __PVT___bufferTimer_1_T_1;
        SData/*15:0*/ __PVT___bufferTimer_2_T_1;
        SData/*15:0*/ __PVT___bufferTimer_3_T_1;
        VlUnpacked<CData/*2:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_channel;
        VlUnpacked<CData/*6:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_set;
        VlUnpacked<CData/*7:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_tag;
        VlUnpacked<CData/*0:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_off;
        VlUnpacked<CData/*1:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_alias;
        VlUnpacked<CData/*2:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_opcode;
        VlUnpacked<CData/*2:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_param;
        VlUnpacked<CData/*4:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_sourceId;
        VlUnpacked<CData/*1:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_bufIdx;
        VlUnpacked<CData/*0:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_needProbeAckData;
        VlUnpacked<CData/*0:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_mshrTask;
        VlUnpacked<CData/*7:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_mshrId;
        VlUnpacked<CData/*0:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_useProbeData;
        VlUnpacked<CData/*0:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_dirty;
        VlUnpacked<CData/*1:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_way;
        VlUnpacked<CData/*0:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_meta_dirty;
        VlUnpacked<CData/*1:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_meta_state;
        VlUnpacked<CData/*0:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_meta_clients;
        VlUnpacked<CData/*1:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_meta_alias;
        VlUnpacked<CData/*0:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_meta_accessed;
        VlUnpacked<CData/*0:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_metaWen;
        VlUnpacked<CData/*0:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_tagWen;
        VlUnpacked<CData/*0:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_dsWen;
        VlUnpacked<CData/*0:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_replTask;
        VlUnpacked<CData/*3:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_reqSource;
        VlUnpacked<CData/*1:0*/, 1> __PVT__chosenQ__DOT__ram_id;
    };

    // INTERNAL VARIABLES
    VTestTop_L2L3L2__Syms* const vlSymsp;

    // CONSTRUCTORS
    VTestTop_L2L3L2_RequestBuffer(VTestTop_L2L3L2__Syms* symsp, const char* v__name);
    ~VTestTop_L2L3L2_RequestBuffer();
    VL_UNCOPYABLE(VTestTop_L2L3L2_RequestBuffer);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
