// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See VVerifyTop.h for the primary calling header

#ifndef VERILATED_VVERIFYTOP_MSHR_16_H_
#define VERILATED_VVERIFYTOP_MSHR_16_H_  // guard

#include "verilated.h"


class VVerifyTop__Syms;

class alignas(VL_CACHE_LINE_BYTES) VVerifyTop_MSHR_16 final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clock,0,0);
        VL_IN8(reset,0,0);
        VL_IN8(io_id,2,0);
        VL_IN8(io_enable,0,0);
        VL_IN8(io_alloc_valid,0,0);
        VL_IN8(io_alloc_bits_channel,2,0);
        VL_IN8(io_alloc_bits_opcode,2,0);
        VL_IN8(io_alloc_bits_param,2,0);
        VL_IN8(io_alloc_bits_size,0,0);
        VL_IN8(io_alloc_bits_set,1,0);
        VL_IN8(io_alloc_bits_tag,1,0);
        VL_IN8(io_alloc_bits_off,0,0);
        VL_IN8(io_alloc_bits_mask,0,0);
        VL_IN8(io_alloc_bits_bufIdx,2,0);
        VL_IN8(io_alloc_bits_preferCache,0,0);
        VL_IN8(io_alloc_bits_dirty,0,0);
        VL_IN8(io_alloc_bits_fromProbeHelper,0,0);
        VL_IN8(io_alloc_bits_fromCmoHelper,0,0);
        VL_IN8(io_alloc_bits_needProbeAckData,0,0);
        VL_IN8(io_alloc_bits_reqSource,3,0);
        VL_OUT8(io_status_valid,0,0);
        VL_OUT8(io_status_bits_channel,2,0);
        VL_OUT8(io_status_bits_set,1,0);
        VL_OUT8(io_status_bits_tag,1,0);
        VL_OUT8(io_status_bits_way,0,0);
        VL_OUT8(io_status_bits_way_reg,0,0);
        VL_OUT8(io_status_bits_is_miss,0,0);
        VL_OUT8(io_status_bits_nestB,0,0);
        VL_OUT8(io_status_bits_nestC,0,0);
        VL_OUT8(io_status_bits_will_grant_data,0,0);
        VL_OUT8(io_status_bits_will_save_data,0,0);
        VL_OUT8(io_status_bits_will_free,0,0);
        VL_IN8(io_resps_sink_c_valid,0,0);
        VL_IN8(io_resps_sink_c_bits_hasData,0,0);
        VL_IN8(io_resps_sink_c_bits_param,2,0);
        VL_IN8(io_resps_sink_c_bits_last,0,0);
        VL_IN8(io_resps_sink_c_bits_bufIdx,2,0);
        VL_IN8(io_resps_sink_d_valid,0,0);
        VL_IN8(io_resps_sink_d_bits_opcode,2,0);
        VL_IN8(io_resps_sink_d_bits_param,2,0);
        VL_IN8(io_resps_sink_d_bits_sink,2,0);
        VL_IN8(io_resps_sink_d_bits_last,0,0);
        VL_IN8(io_resps_sink_d_bits_denied,0,0);
        VL_IN8(io_resps_sink_d_bits_dirty,0,0);
        VL_IN8(io_resps_sink_d_bits_bufIdx,2,0);
        VL_IN8(io_resps_sink_e_valid,0,0);
        VL_IN8(io_resps_source_d_valid,0,0);
        VL_IN8(io_resps_sink_c_ack_valid,0,0);
        VL_IN8(io_nestedwb_set,1,0);
        VL_IN8(io_nestedwb_tag,1,0);
        VL_IN8(io_nestedwb_b_toN,0,0);
        VL_IN8(io_nestedwb_b_toB,0,0);
        VL_IN8(io_nestedwb_b_clr_dirty,0,0);
        VL_IN8(io_nestedwb_b_set_dirty,0,0);
        VL_IN8(io_nestedwb_c_set_dirty,0,0);
        VL_IN8(io_nestedwb_c_set_hit,0,0);
        VL_IN8(io_nestedwb_clients_0_isToN,0,0);
        VL_IN8(io_nestedwb_clients_1_isToN,0,0);
        VL_IN8(io_tasks_sink_a_ready,0,0);
        VL_OUT8(__PVT__io_tasks_sink_a_valid,0,0);
        VL_OUT8(io_tasks_sink_a_bits_set,1,0);
        VL_OUT8(io_tasks_sink_a_bits_tag,1,0);
        VL_OUT8(io_tasks_sink_a_bits_size,0,0);
        VL_OUT8(io_tasks_sink_a_bits_off,0,0);
    };
    struct {
        VL_IN8(io_tasks_source_b_ready,0,0);
        VL_OUT8(io_tasks_source_b_valid,0,0);
        VL_OUT8(io_tasks_source_b_bits_set,1,0);
        VL_OUT8(io_tasks_source_b_bits_tag,1,0);
        VL_OUT8(io_tasks_source_b_bits_param,2,0);
        VL_OUT8(io_tasks_source_b_bits_clients,1,0);
        VL_OUT8(io_tasks_source_b_bits_needData,0,0);
        VL_IN8(io_tasks_sink_c_ready,0,0);
        VL_OUT8(io_tasks_sink_c_valid,0,0);
        VL_OUT8(io_tasks_sink_c_bits_set,1,0);
        VL_OUT8(io_tasks_sink_c_bits_tag,1,0);
        VL_OUT8(io_tasks_sink_c_bits_size,0,0);
        VL_OUT8(io_tasks_sink_c_bits_way,0,0);
        VL_OUT8(io_tasks_sink_c_bits_off,0,0);
        VL_OUT8(io_tasks_sink_c_bits_bufIdx,2,0);
        VL_OUT8(io_tasks_sink_c_bits_opcode,2,0);
        VL_OUT8(io_tasks_sink_c_bits_param,2,0);
        VL_OUT8(io_tasks_sink_c_bits_source,2,0);
        VL_OUT8(io_tasks_sink_c_bits_save,0,0);
        VL_OUT8(io_tasks_sink_c_bits_drop,0,0);
        VL_OUT8(io_tasks_sink_c_bits_release,0,0);
        VL_OUT8(io_tasks_sink_c_bits_dirty,0,0);
        VL_IN8(io_tasks_source_d_ready,0,0);
        VL_OUT8(io_tasks_source_d_valid,0,0);
        VL_OUT8(io_tasks_source_d_bits_set,1,0);
        VL_OUT8(io_tasks_source_d_bits_tag,1,0);
        VL_OUT8(io_tasks_source_d_bits_channel,2,0);
        VL_OUT8(io_tasks_source_d_bits_opcode,2,0);
        VL_OUT8(io_tasks_source_d_bits_param,2,0);
        VL_OUT8(io_tasks_source_d_bits_size,0,0);
        VL_OUT8(io_tasks_source_d_bits_way,0,0);
        VL_OUT8(io_tasks_source_d_bits_off,0,0);
        VL_OUT8(io_tasks_source_d_bits_useBypass,0,0);
        VL_OUT8(io_tasks_source_d_bits_bufIdx,2,0);
        VL_OUT8(io_tasks_source_d_bits_denied,0,0);
        VL_OUT8(io_tasks_source_d_bits_sinkId,2,0);
        VL_OUT8(io_tasks_source_d_bits_bypassPut,0,0);
        VL_OUT8(io_tasks_source_d_bits_dirty,0,0);
        VL_OUT8(io_tasks_source_d_bits_isHit,0,0);
        VL_IN8(io_tasks_source_a_ready,0,0);
        VL_OUT8(io_tasks_source_a_valid,0,0);
        VL_OUT8(io_tasks_source_a_bits_tag,1,0);
        VL_OUT8(io_tasks_source_a_bits_set,1,0);
        VL_OUT8(io_tasks_source_a_bits_off,0,0);
        VL_OUT8(io_tasks_source_a_bits_mask,0,0);
        VL_OUT8(io_tasks_source_a_bits_opcode,2,0);
        VL_OUT8(io_tasks_source_a_bits_param,2,0);
        VL_OUT8(io_tasks_source_a_bits_source,2,0);
        VL_OUT8(io_tasks_source_a_bits_bufIdx,2,0);
        VL_OUT8(io_tasks_source_a_bits_size,0,0);
        VL_OUT8(io_tasks_source_a_bits_needData,0,0);
        VL_OUT8(io_tasks_source_a_bits_putData,0,0);
        VL_OUT8(io_tasks_source_a_bits_reqSource,3,0);
        VL_IN8(io_tasks_source_c_ready,0,0);
        VL_OUT8(io_tasks_source_c_valid,0,0);
        VL_OUT8(io_tasks_source_c_bits_opcode,2,0);
        VL_OUT8(io_tasks_source_c_bits_tag,1,0);
        VL_OUT8(io_tasks_source_c_bits_set,1,0);
        VL_OUT8(io_tasks_source_c_bits_param,2,0);
        VL_OUT8(io_tasks_source_c_bits_source,2,0);
        VL_OUT8(io_tasks_source_c_bits_way,0,0);
        VL_OUT8(io_tasks_source_c_bits_dirty,0,0);
        VL_IN8(io_tasks_source_e_ready,0,0);
        VL_OUT8(io_tasks_source_e_valid,0,0);
    };
    struct {
        VL_OUT8(io_tasks_source_e_bits_sink,2,0);
        VL_IN8(io_tasks_dir_write_ready,0,0);
        VL_OUT8(io_tasks_dir_write_valid,0,0);
        VL_OUT8(io_tasks_dir_write_bits_set,1,0);
        VL_OUT8(io_tasks_dir_write_bits_way,0,0);
        VL_OUT8(io_tasks_dir_write_bits_data_dirty,0,0);
        VL_OUT8(io_tasks_dir_write_bits_data_state,1,0);
        VL_OUT8(io_tasks_dir_write_bits_data_clientStates_0,1,0);
        VL_OUT8(io_tasks_dir_write_bits_data_clientStates_1,1,0);
        VL_IN8(io_tasks_tag_write_ready,0,0);
        VL_OUT8(io_tasks_tag_write_valid,0,0);
        VL_OUT8(io_tasks_tag_write_bits_set,1,0);
        VL_OUT8(io_tasks_tag_write_bits_way,0,0);
        VL_OUT8(io_tasks_tag_write_bits_tag,1,0);
        VL_IN8(io_tasks_client_dir_write_ready,0,0);
        VL_OUT8(io_tasks_client_dir_write_valid,0,0);
        VL_OUT8(io_tasks_client_dir_write_bits_set,1,0);
        VL_OUT8(io_tasks_client_dir_write_bits_way,1,0);
        VL_OUT8(io_tasks_client_dir_write_bits_data_0_state,1,0);
        VL_OUT8(io_tasks_client_dir_write_bits_data_1_state,1,0);
        VL_IN8(io_tasks_client_tag_write_ready,0,0);
        VL_OUT8(io_tasks_client_tag_write_valid,0,0);
        VL_OUT8(io_tasks_client_tag_write_bits_set,1,0);
        VL_OUT8(io_tasks_client_tag_write_bits_way,1,0);
        VL_OUT8(io_tasks_client_tag_write_bits_tag,1,0);
        VL_IN8(io_dirResult_valid,0,0);
        VL_IN8(io_dirResult_bits_idOH,7,0);
        VL_IN8(io_dirResult_bits_self_dirty,0,0);
        VL_IN8(io_dirResult_bits_self_state,1,0);
        VL_IN8(io_dirResult_bits_self_clientStates_0,1,0);
        VL_IN8(io_dirResult_bits_self_clientStates_1,1,0);
        VL_IN8(io_dirResult_bits_self_hit,0,0);
        VL_IN8(io_dirResult_bits_self_way,0,0);
        VL_IN8(io_dirResult_bits_self_tag,1,0);
        VL_IN8(io_dirResult_bits_clients_states_0_state,1,0);
        VL_IN8(io_dirResult_bits_clients_states_0_hit,0,0);
        VL_IN8(io_dirResult_bits_clients_states_1_state,1,0);
        VL_IN8(io_dirResult_bits_clients_states_1_hit,0,0);
        VL_IN8(io_dirResult_bits_clients_tag,1,0);
        VL_IN8(io_dirResult_bits_clients_way,1,0);
        VL_IN8(io_c_status_set,1,0);
        VL_IN8(io_c_status_tag,1,0);
        VL_IN8(io_c_status_way,0,0);
        VL_IN8(io_c_status_nestedReleaseData,0,0);
        VL_OUT8(io_c_status_releaseThrough,0,0);
        VL_IN8(io_c_status_metaValid,0,0);
        VL_IN8(io_c_status_reqDirty,0,0);
        VL_IN8(io_b_status_set,1,0);
        VL_IN8(io_b_status_tag,1,0);
        VL_IN8(io_b_status_way,0,0);
        VL_IN8(io_b_status_nestedProbeAckData,0,0);
        VL_IN8(io_b_status_probeHelperFinish,0,0);
        VL_OUT8(io_b_status_probeAckDataThrough,0,0);
        VL_IN8(io_releaseThrough,0,0);
        VL_IN8(io_probeAckDataThrough,0,0);
        VL_OUT8(io_is_nestedReleaseData,0,0);
        VL_OUT8(io_is_nestedProbeAckData,0,0);
        VL_OUT8(io_probeHelperFinish,0,0);
        VL_OUT8(io_metaValid,0,0);
        VL_OUT8(io_reqDirty,0,0);
        CData/*2:0*/ __PVT__req_channel;
        CData/*2:0*/ __PVT__req_opcode;
        CData/*2:0*/ __PVT__req_param;
        CData/*0:0*/ __PVT__req_size;
    };
    struct {
        CData/*1:0*/ __PVT__req_set;
        CData/*1:0*/ __PVT__req_tag;
        CData/*0:0*/ __PVT__req_off;
        CData/*2:0*/ __PVT__req_bufIdx;
        CData/*0:0*/ __PVT__req_preferCache;
        CData/*0:0*/ __PVT__req_dirty;
        CData/*0:0*/ __PVT__req_fromProbeHelper;
        CData/*0:0*/ __PVT__req_fromCmoHelper;
        CData/*0:0*/ __PVT__req_needProbeAckData;
        CData/*0:0*/ __PVT__req_valid;
        CData/*1:0*/ __PVT__iam;
        CData/*0:0*/ __PVT__meta_reg_self_dirty;
        CData/*1:0*/ __PVT__meta_reg_self_state;
        CData/*1:0*/ __PVT__meta_reg_self_clientStates_0;
        CData/*1:0*/ __PVT__meta_reg_self_clientStates_1;
        CData/*0:0*/ __PVT__meta_reg_self_hit;
        CData/*0:0*/ __PVT__meta_reg_self_way;
        CData/*1:0*/ __PVT__meta_reg_self_tag;
        CData/*1:0*/ __PVT__meta_reg_clients_states_0_state;
        CData/*0:0*/ __PVT__meta_reg_clients_states_0_hit;
        CData/*1:0*/ __PVT__meta_reg_clients_states_1_state;
        CData/*0:0*/ __PVT__meta_reg_clients_states_1_hit;
        CData/*1:0*/ __PVT__meta_reg_clients_tag;
        CData/*1:0*/ __PVT__meta_reg_clients_way;
        CData/*0:0*/ __PVT__meta_valid;
        CData/*0:0*/ __PVT__REG;
        CData/*3:0*/ __PVT___T_5;
        CData/*0:0*/ __PVT___GEN_2;
        CData/*1:0*/ __PVT___GEN_3;
        CData/*1:0*/ __PVT___GEN_4;
        CData/*1:0*/ __PVT___GEN_5;
        CData/*1:0*/ __PVT___GEN_8;
        CData/*1:0*/ __PVT___GEN_10;
        CData/*0:0*/ __PVT___GEN_11;
        CData/*1:0*/ __PVT___GEN_12;
        CData/*0:0*/ __PVT___GEN_13;
        CData/*0:0*/ __PVT__req_acquire;
        CData/*0:0*/ __PVT__req_needT;
        CData/*0:0*/ __PVT__promoteT_safe;
        CData/*0:0*/ __PVT__gotT;
        CData/*0:0*/ __PVT__gotDirty;
        CData/*0:0*/ __PVT__a_do_release;
        CData/*0:0*/ __PVT__a_do_probe;
        CData/*0:0*/ __PVT__meta_no_clients;
        CData/*0:0*/ __PVT__req_promoteT;
        CData/*0:0*/ __PVT__probe_dirty;
        CData/*1:0*/ __PVT__probes_done;
        CData/*0:0*/ __PVT___client_shrink_perm_T_4;
        CData/*1:0*/ __PVT___GEN_24;
        CData/*0:0*/ __PVT___client_shrink_perm_T_10;
        CData/*0:0*/ __PVT___clients_have_T_T_1;
        CData/*0:0*/ __PVT___clients_have_T_T_3;
        CData/*0:0*/ __PVT__clients_have_T;
        CData/*0:0*/ __PVT___GEN_28;
        CData/*1:0*/ __PVT___highest_perm_T_2;
        CData/*1:0*/ __PVT___highest_perm_T_3;
        CData/*1:0*/ __PVT___highest_perm_T_4;
        CData/*1:0*/ __PVT___highest_perm_T_6;
        CData/*1:0*/ __PVT__highest_perm;
        CData/*1:0*/ __PVT__highest_perm_reg_reg;
        CData/*0:0*/ __PVT__w_probeacklast;
        CData/*0:0*/ __PVT__w_grantlast;
        CData/*0:0*/ __PVT__w_releaseack;
        CData/*0:0*/ __PVT__w_grantack;
    };
    struct {
        CData/*0:0*/ __PVT__w_putwritten;
        CData/*0:0*/ __PVT__w_sinkcack;
        CData/*0:0*/ __PVT__no_wait;
        CData/*0:0*/ __PVT__s_probeack;
        CData/*0:0*/ __PVT__s_execute;
        CData/*0:0*/ __PVT__s_grantack;
        CData/*0:0*/ __PVT__no_schedule_REG;
        CData/*0:0*/ __PVT__s_writerelease;
        CData/*0:0*/ __PVT__s_writeprobe;
        CData/*0:0*/ __PVT__s_transferput;
        CData/*0:0*/ __PVT__no_schedule;
        CData/*1:0*/ __PVT__highest_perm_reg;
        CData/*1:0*/ __PVT__highest_perm_except_me;
        CData/*0:0*/ __PVT__inv_self_dir;
        CData/*2:0*/ __PVT__client_probeack_param_vec_reg_0;
        CData/*2:0*/ __PVT__client_probeack_param_vec_reg_1;
        CData/*0:0*/ __PVT__replace_need_release;
        CData/*0:0*/ __PVT__prefetch_miss_need_probe_vec_0;
        CData/*0:0*/ __PVT__prefetch_miss_need_probe_vec_1;
        CData/*0:0*/ __PVT__prefetch_miss_need_probe;
        CData/*0:0*/ __PVT__prefetch_need_data;
        CData/*0:0*/ __PVT___transmit_from_other_client_T_2;
        CData/*0:0*/ __PVT___transmit_from_other_client_T_12;
        CData/*0:0*/ __PVT__transmit_from_other_client_reg;
        CData/*0:0*/ __PVT__transmit_from_other_client;
        CData/*0:0*/ __PVT__releaseThrough;
        CData/*0:0*/ __PVT__releaseDrop;
        CData/*0:0*/ __PVT__releaseSave;
        CData/*0:0*/ __PVT__probeAckDataThrough;
        CData/*0:0*/ __PVT__probeAckDataDrop;
        CData/*0:0*/ __PVT__probeAckDataSave;
        CData/*0:0*/ __PVT__someClientHasProbeAckData;
        CData/*0:0*/ __PVT__nested_c_hit_reg;
        CData/*0:0*/ __PVT___new_self_meta_dirty_T;
        CData/*0:0*/ __PVT___new_self_meta_dirty_T_8;
        CData/*0:0*/ __PVT___new_self_meta_dirty_T_9;
        CData/*0:0*/ __PVT__sink_c_resp_valid;
        CData/*0:0*/ __PVT__sinkc_resp_last;
        CData/*2:0*/ __PVT__client_probeack_param_vec_0;
        CData/*1:0*/ __PVT___new_clients_meta_0_state_T_24;
        CData/*2:0*/ __PVT__client_probeack_param_vec_1;
        CData/*1:0*/ __PVT___new_clients_meta_1_state_T_24;
        CData/*0:0*/ __PVT___new_self_meta_dirty_T_13;
        CData/*0:0*/ __PVT___new_self_meta_dirty_T_15;
        CData/*1:0*/ __PVT___new_self_meta_state_T_34;
        CData/*1:0*/ __PVT___new_self_meta_clientStates_0_T_27;
        CData/*0:0*/ __PVT___new_self_meta_clientStates_0_T_33;
        CData/*0:0*/ __PVT___new_self_meta_clientStates_0_T_36;
        CData/*0:0*/ __PVT___new_self_meta_clientStates_0_T_37;
        CData/*1:0*/ __PVT___new_self_meta_clientStates_0_T_38;
        CData/*1:0*/ __PVT___new_self_meta_clientStates_0_T_45;
        CData/*0:0*/ __PVT___new_self_meta_clientStates_1_T_37;
        CData/*1:0*/ __PVT___new_self_meta_clientStates_1_T_38;
        CData/*1:0*/ __PVT___new_self_meta_clientStates_1_T_45;
        CData/*1:0*/ __PVT___new_clients_meta_0_state_T_36;
        CData/*1:0*/ __PVT___new_clients_meta_1_state_T_36;
        CData/*1:0*/ __PVT__new_self_meta_clientStates_0;
        CData/*1:0*/ __PVT__new_self_meta_clientStates_1;
        CData/*0:0*/ __PVT___T_40;
        CData/*0:0*/ __PVT__nested_c_hit;
        CData/*2:0*/ __PVT__sink;
        CData/*0:0*/ __PVT__bad_grant;
        CData/*0:0*/ __PVT__REG_1;
        CData/*0:0*/ __PVT__change_self_meta;
    };
    struct {
        CData/*0:0*/ __PVT__change_clients_meta_0;
        CData/*0:0*/ __PVT__change_clients_meta_1;
        CData/*0:0*/ __PVT__s_acquire;
        CData/*0:0*/ __PVT__s_probe;
        CData/*0:0*/ __PVT__s_release;
        CData/*0:0*/ __PVT__s_wbselfdir;
        CData/*0:0*/ __PVT__s_wbselftag;
        CData/*0:0*/ __PVT__s_wbclientsdir;
        CData/*0:0*/ __PVT__s_wbclientstag;
        CData/*0:0*/ __PVT__w_probeackfirst;
        CData/*0:0*/ __PVT__w_probeack;
        CData/*0:0*/ __PVT__w_grantfirst;
        CData/*0:0*/ __PVT__w_grant;
        CData/*0:0*/ __PVT__acquire_flag;
        CData/*0:0*/ __PVT__nestC_save_flag;
        CData/*0:0*/ __PVT__nestC_saveDirty_flag;
        CData/*0:0*/ __PVT___GEN_92;
        CData/*0:0*/ __PVT__bypassPut;
        CData/*0:0*/ __PVT__bypassPut_latch_reg;
        CData/*0:0*/ __PVT__preferCache;
        CData/*0:0*/ __PVT__bypassGet;
        CData/*0:0*/ __PVT___GEN_101;
        CData/*0:0*/ __PVT___GEN_103;
        CData/*0:0*/ __PVT___T_57;
        CData/*0:0*/ __PVT___T_216;
        CData/*0:0*/ __PVT___GEN_110;
        CData/*0:0*/ __PVT__will_release_through;
        CData/*0:0*/ __PVT__will_probeack_through;
        CData/*0:0*/ __PVT___T_78;
        CData/*0:0*/ __PVT___GEN_125;
        CData/*0:0*/ __PVT___T_130;
        CData/*0:0*/ __PVT___T_143;
        CData/*0:0*/ __PVT___GEN_130;
        CData/*0:0*/ __PVT___T_161;
        CData/*0:0*/ __PVT___T_168;
        CData/*0:0*/ __PVT___GEN_156;
        CData/*0:0*/ __PVT___GEN_159;
        CData/*0:0*/ __PVT___T_182;
        CData/*0:0*/ __PVT___GEN_161;
        CData/*0:0*/ __PVT___GEN_184;
        CData/*0:0*/ __PVT___GEN_185;
        CData/*0:0*/ __PVT___GEN_217;
        CData/*0:0*/ __PVT___GEN_227;
        CData/*0:0*/ __PVT___GEN_234;
        CData/*0:0*/ __PVT___GEN_237;
        CData/*0:0*/ __PVT___GEN_272;
        CData/*0:0*/ __PVT___GEN_273;
        CData/*0:0*/ __PVT___GEN_277;
        CData/*0:0*/ __PVT___GEN_278;
        CData/*0:0*/ __PVT___GEN_279;
        CData/*0:0*/ __PVT___GEN_283;
        CData/*0:0*/ __PVT___GEN_284;
        CData/*0:0*/ __PVT___GEN_285;
        CData/*0:0*/ __PVT___GEN_288;
        CData/*0:0*/ __PVT___GEN_290;
        CData/*0:0*/ __PVT___GEN_292;
        CData/*0:0*/ __PVT__will_drop_release;
        CData/*0:0*/ __PVT___T_222;
        CData/*0:0*/ __PVT___probeAckDataSave_T_4;
        CData/*0:0*/ __PVT___GEN_309;
        CData/*0:0*/ __PVT___GEN_310;
        CData/*0:0*/ __PVT___GEN_311;
        CData/*0:0*/ __PVT__clients_meta_busy;
        CData/*0:0*/ __PVT__client_dir_conflict;
    };
    struct {
        CData/*0:0*/ __PVT__probe_helper_finish;
        CData/*0:0*/ __PVT__client_set_match;
        CData/*0:0*/ __PVT___GEN_322;
        CData/*0:0*/ __PVT__REG_2;
        CData/*0:0*/ __PVT__can_start;
        CData/*0:0*/ __PVT___probe_clients_T_3;
        CData/*1:0*/ __PVT__probe_clients;
        CData/*0:0*/ __PVT___nestedReleaseDataSave_T_1;
        CData/*0:0*/ __PVT__nest_c_tag_match;
        CData/*0:0*/ __PVT__nest_c_way_match;
        CData/*0:0*/ __PVT___a_c_through_T_3;
        CData/*0:0*/ __PVT__preferCache_latch;
        CData/*0:0*/ __PVT__a_c_through_reg;
        CData/*0:0*/ __PVT__transmit_from_other_client_latch;
        CData/*0:0*/ __PVT__a_c_through;
        CData/*2:0*/ __PVT___GEN_334;
        CData/*0:0*/ __PVT__nestC_saveDirty;
        CData/*2:0*/ __PVT__io_tasks_sink_c_bits_bufIdx_r;
        CData/*0:0*/ __PVT___GEN_337;
        CData/*0:0*/ __PVT___GEN_338;
        CData/*0:0*/ __PVT___T_246;
        CData/*0:0*/ __PVT___GEN_339;
        CData/*0:0*/ __PVT___T_251;
        CData/*0:0*/ __PVT___GEN_340;
        CData/*0:0*/ __PVT___GEN_341;
        CData/*0:0*/ __PVT___GEN_342;
        CData/*0:0*/ __PVT___GEN_343;
        CData/*0:0*/ __PVT___GEN_344;
        CData/*0:0*/ __PVT___GEN_345;
        CData/*0:0*/ __PVT___GEN_346;
        CData/*0:0*/ __PVT___GEN_347;
        CData/*0:0*/ __PVT___T_258;
        CData/*0:0*/ __PVT___GEN_350;
        CData/*1:0*/ __PVT___probeack_last_T;
        CData/*0:0*/ __PVT___GEN_360;
        CData/*0:0*/ __PVT___T_268;
        CData/*0:0*/ __PVT___GEN_371;
        CData/*0:0*/ __PVT___T_293;
        CData/*0:0*/ __PVT___T_310;
        CData/*0:0*/ __PVT___GEN_386;
        CData/*0:0*/ __PVT___GEN_387;
        CData/*0:0*/ __PVT___GEN_388;
        CData/*0:0*/ __PVT___GEN_392;
        CData/*0:0*/ __PVT___GEN_393;
        CData/*0:0*/ __PVT___GEN_394;
        CData/*0:0*/ __PVT___GEN_411;
        CData/*0:0*/ __PVT___GEN_418;
        CData/*0:0*/ __PVT___GEN_419;
        CData/*0:0*/ __PVT__REG_3;
        CData/*1:0*/ __PVT__clientBitOH;
        CData/*0:0*/ __PVT___GEN_430;
        CData/*0:0*/ __PVT___io_status_bits_nestB_T_7;
        CData/*0:0*/ __PVT___GEN_451;
        CData/*0:0*/ __PVT___GEN_452;
        CData/*0:0*/ __PVT___GEN_480;
        CData/*0:0*/ __PVT___GEN_481;
        CData/*0:0*/ __VdfgRegularize_hd4a67951_2_17;
        CData/*0:0*/ __VdfgRegularize_hd4a67951_2_19;
        CData/*0:0*/ __VdfgRegularize_hd4a67951_2_21;
        CData/*0:0*/ __VdfgRegularize_hd4a67951_2_22;
        CData/*0:0*/ __VdfgRegularize_hd4a67951_2_24;
        CData/*0:0*/ __VdfgRegularize_hd4a67951_2_26;
        CData/*0:0*/ __VdfgRegularize_hd4a67951_2_27;
        CData/*0:0*/ __VdfgRegularize_hd4a67951_2_28;
    };
    struct {
        CData/*0:0*/ __VdfgRegularize_hd4a67951_2_31;
        CData/*0:0*/ __VdfgRegularize_hd4a67951_2_32;
        CData/*0:0*/ __VdfgRegularize_hd4a67951_2_33;
        CData/*0:0*/ __VdfgRegularize_hd4a67951_2_36;
        CData/*0:0*/ __VdfgRegularize_hd4a67951_2_38;
        VL_IN16(io_alloc_bits_source,8,0);
        VL_IN16(io_resps_sink_c_bits_source,8,0);
        VL_OUT16(io_tasks_sink_a_bits_sourceId,8,0);
        VL_OUT16(__PVT__io_tasks_sink_c_bits_sourceId,8,0);
        VL_OUT16(io_tasks_source_d_bits_sourceId,8,0);
        SData/*8:0*/ __PVT__req_source;
    };

    // INTERNAL VARIABLES
    VVerifyTop__Syms* const vlSymsp;

    // CONSTRUCTORS
    VVerifyTop_MSHR_16(VVerifyTop__Syms* symsp, const char* v__name);
    ~VVerifyTop_MSHR_16();
    VL_UNCOPYABLE(VVerifyTop_MSHR_16);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
