// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See VVerifyTop.h for the primary calling header

#ifndef VERILATED_VVERIFYTOP_REQUESTBUFFER_H_
#define VERILATED_VVERIFYTOP_REQUESTBUFFER_H_  // guard

#include "verilated.h"


class VVerifyTop__Syms;

class alignas(VL_CACHE_LINE_BYTES) VVerifyTop_RequestBuffer final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clock,0,0);
        VL_IN8(reset,0,0);
        VL_OUT8(io_in_ready,0,0);
        VL_IN8(io_in_bits_set,0,0);
        VL_IN8(io_in_bits_tag,2,0);
        VL_IN8(io_in_bits_off,0,0);
        VL_IN8(io_in_bits_alias,1,0);
        VL_IN8(io_in_bits_opcode,2,0);
        VL_IN8(io_in_bits_param,2,0);
        VL_IN8(io_in_bits_size,2,0);
        VL_IN8(io_in_bits_sourceId,4,0);
        VL_IN8(io_out_ready,0,0);
        VL_OUT8(io_out_valid,0,0);
        VL_OUT8(io_out_bits_channel,2,0);
        VL_OUT8(io_out_bits_txChannel,2,0);
        VL_OUT8(io_out_bits_set,0,0);
        VL_OUT8(io_out_bits_tag,2,0);
        VL_OUT8(io_out_bits_off,0,0);
        VL_OUT8(io_out_bits_alias,1,0);
        VL_OUT8(io_out_bits_opcode,2,0);
        VL_OUT8(io_out_bits_param,2,0);
        VL_OUT8(io_out_bits_size,2,0);
        VL_OUT8(io_out_bits_sourceId,4,0);
        VL_OUT8(io_out_bits_bufIdx,1,0);
        VL_OUT8(io_out_bits_needProbeAckData,0,0);
        VL_OUT8(io_out_bits_mshrTask,0,0);
        VL_OUT8(io_out_bits_mshrId,7,0);
        VL_OUT8(io_out_bits_aliasTask,0,0);
        VL_OUT8(io_out_bits_useProbeData,0,0);
        VL_OUT8(io_out_bits_mshrRetry,0,0);
        VL_OUT8(io_out_bits_fromL2pft,0,0);
        VL_OUT8(io_out_bits_needHint,0,0);
        VL_OUT8(io_out_bits_dirty,0,0);
        VL_OUT8(io_out_bits_way,0,0);
        VL_OUT8(io_out_bits_meta_dirty,0,0);
        VL_OUT8(io_out_bits_meta_state,1,0);
        VL_OUT8(io_out_bits_meta_clients,0,0);
        VL_OUT8(io_out_bits_meta_alias,1,0);
        VL_OUT8(io_out_bits_meta_prefetch,0,0);
        VL_OUT8(io_out_bits_meta_prefetchSrc,2,0);
        VL_OUT8(io_out_bits_meta_accessed,0,0);
        VL_OUT8(io_out_bits_metaWen,0,0);
        VL_OUT8(io_out_bits_tagWen,0,0);
        VL_OUT8(io_out_bits_dsWen,0,0);
        VL_OUT8(io_out_bits_replTask,0,0);
        VL_OUT8(io_out_bits_reqSource,3,0);
        VL_OUT8(io_out_bits_mergeA,0,0);
        VL_OUT8(io_out_bits_aMergeTask_off,0,0);
        VL_OUT8(io_out_bits_aMergeTask_alias,1,0);
        VL_OUT8(io_out_bits_aMergeTask_opcode,2,0);
        VL_OUT8(io_out_bits_aMergeTask_param,2,0);
        VL_OUT8(io_out_bits_aMergeTask_sourceId,4,0);
        VL_OUT8(io_out_bits_aMergeTask_meta_dirty,0,0);
        VL_OUT8(io_out_bits_aMergeTask_meta_state,1,0);
        VL_OUT8(io_out_bits_aMergeTask_meta_clients,0,0);
        VL_OUT8(io_out_bits_aMergeTask_meta_alias,1,0);
        VL_OUT8(io_out_bits_aMergeTask_meta_prefetch,0,0);
        VL_OUT8(io_out_bits_aMergeTask_meta_prefetchSrc,2,0);
        VL_OUT8(io_out_bits_aMergeTask_meta_accessed,0,0);
        VL_OUT8(io_out_bits_snpHitRelease,0,0);
        VL_OUT8(io_out_bits_snpHitReleaseWithData,0,0);
        VL_OUT8(io_out_bits_snpHitReleaseIdx,7,0);
        VL_IN8(io_mshrInfo_0_valid,0,0);
        VL_IN8(io_mshrInfo_0_bits_set,0,0);
    };
    struct {
        VL_IN8(io_mshrInfo_0_bits_reqTag,2,0);
        VL_IN8(io_mshrInfo_0_bits_willFree,0,0);
        VL_IN8(io_mshrInfo_0_bits_needRelease,0,0);
        VL_IN8(io_mshrInfo_0_bits_metaTag,2,0);
        VL_IN8(io_mshrInfo_0_bits_dirHit,0,0);
        VL_IN8(io_mshrInfo_0_bits_isAcqOrPrefetch,0,0);
        VL_IN8(io_mshrInfo_0_bits_isPrefetch,0,0);
        VL_IN8(io_mshrInfo_0_bits_param,2,0);
        VL_IN8(io_mshrInfo_0_bits_mergeA,0,0);
        VL_IN8(io_mshrInfo_0_bits_s_refill,0,0);
        VL_IN8(io_mshrInfo_1_valid,0,0);
        VL_IN8(io_mshrInfo_1_bits_set,0,0);
        VL_IN8(io_mshrInfo_1_bits_reqTag,2,0);
        VL_IN8(io_mshrInfo_1_bits_willFree,0,0);
        VL_IN8(io_mshrInfo_1_bits_needRelease,0,0);
        VL_IN8(io_mshrInfo_1_bits_metaTag,2,0);
        VL_IN8(io_mshrInfo_1_bits_dirHit,0,0);
        VL_IN8(io_mshrInfo_1_bits_isAcqOrPrefetch,0,0);
        VL_IN8(io_mshrInfo_1_bits_isPrefetch,0,0);
        VL_IN8(io_mshrInfo_1_bits_param,2,0);
        VL_IN8(io_mshrInfo_1_bits_mergeA,0,0);
        VL_IN8(io_mshrInfo_1_bits_s_refill,0,0);
        VL_IN8(io_mshrInfo_2_valid,0,0);
        VL_IN8(io_mshrInfo_2_bits_set,0,0);
        VL_IN8(io_mshrInfo_2_bits_reqTag,2,0);
        VL_IN8(io_mshrInfo_2_bits_willFree,0,0);
        VL_IN8(io_mshrInfo_2_bits_needRelease,0,0);
        VL_IN8(io_mshrInfo_2_bits_metaTag,2,0);
        VL_IN8(io_mshrInfo_2_bits_dirHit,0,0);
        VL_IN8(io_mshrInfo_2_bits_isAcqOrPrefetch,0,0);
        VL_IN8(io_mshrInfo_2_bits_isPrefetch,0,0);
        VL_IN8(io_mshrInfo_2_bits_param,2,0);
        VL_IN8(io_mshrInfo_2_bits_mergeA,0,0);
        VL_IN8(io_mshrInfo_2_bits_s_refill,0,0);
        VL_IN8(io_mshrInfo_3_valid,0,0);
        VL_IN8(io_mshrInfo_3_bits_set,0,0);
        VL_IN8(io_mshrInfo_3_bits_reqTag,2,0);
        VL_IN8(io_mshrInfo_3_bits_willFree,0,0);
        VL_IN8(io_mshrInfo_3_bits_needRelease,0,0);
        VL_IN8(io_mshrInfo_3_bits_metaTag,2,0);
        VL_IN8(io_mshrInfo_3_bits_dirHit,0,0);
        VL_IN8(io_mshrInfo_3_bits_isAcqOrPrefetch,0,0);
        VL_IN8(io_mshrInfo_3_bits_isPrefetch,0,0);
        VL_IN8(io_mshrInfo_3_bits_param,2,0);
        VL_IN8(io_mshrInfo_3_bits_mergeA,0,0);
        VL_IN8(io_mshrInfo_3_bits_s_refill,0,0);
        VL_OUT8(io_aMergeTask_valid,0,0);
        VL_OUT8(io_aMergeTask_bits_id,7,0);
        VL_OUT8(io_aMergeTask_bits_task_off,0,0);
        VL_OUT8(io_aMergeTask_bits_task_alias,1,0);
        VL_OUT8(io_aMergeTask_bits_task_opcode,2,0);
        VL_OUT8(io_aMergeTask_bits_task_param,2,0);
        VL_OUT8(io_aMergeTask_bits_task_sourceId,4,0);
        VL_IN8(io_mainPipeBlock_0,0,0);
        VL_IN8(io_mainPipeBlock_1,0,0);
        VL_OUT8(io_ATag,2,0);
        VL_OUT8(io_ASet,0,0);
        VL_IN8(io_s1Entrance_valid,0,0);
        VL_IN8(io_s1Entrance_bits_set,0,0);
        VL_OUT8(io_hasLatePF,0,0);
        VL_OUT8(io_hasMergeA,0,0);
        CData/*0:0*/ __PVT__issueArb_io_in_0_valid;
        CData/*0:0*/ __PVT__issueArb_io_in_1_valid;
        CData/*0:0*/ __PVT__issueArb_io_in_2_valid;
    };
    struct {
        CData/*0:0*/ __PVT__issueArb_io_in_3_valid;
        CData/*1:0*/ __PVT__issueArb_io_chosen;
        CData/*0:0*/ __PVT__helper_clean;
        CData/*0:0*/ __PVT__helper_dump;
        CData/*0:0*/ __PVT__helper_1_clean;
        CData/*0:0*/ __PVT__helper_1_dump;
        CData/*0:0*/ __PVT__helper_2_clean;
        CData/*0:0*/ __PVT__helper_2_dump;
        CData/*0:0*/ __PVT__helper_3_clean;
        CData/*0:0*/ __PVT__helper_3_dump;
        CData/*0:0*/ __PVT__helper_4_clean;
        CData/*0:0*/ __PVT__helper_4_dump;
        CData/*0:0*/ __PVT__helper_5_clean;
        CData/*0:0*/ __PVT__helper_5_dump;
        CData/*0:0*/ __PVT__helper_6_clean;
        CData/*0:0*/ __PVT__helper_6_dump;
        CData/*0:0*/ __PVT__helper_7_clean;
        CData/*0:0*/ __PVT__helper_7_dump;
        CData/*0:0*/ __PVT__helper_8_clean;
        CData/*0:0*/ __PVT__helper_8_dump;
        CData/*0:0*/ __PVT__helper_9_clean;
        CData/*0:0*/ __PVT__helper_9_dump;
        CData/*0:0*/ __PVT__helper_10_clean;
        CData/*0:0*/ __PVT__helper_10_dump;
        CData/*0:0*/ __PVT__helper_11_clean;
        CData/*0:0*/ __PVT__helper_11_dump;
        CData/*0:0*/ __PVT__helper_12_clean;
        CData/*0:0*/ __PVT__helper_12_dump;
        CData/*0:0*/ __PVT__helper_13_clean;
        CData/*0:0*/ __PVT__helper_13_dump;
        CData/*0:0*/ __PVT__helper_14_clean;
        CData/*0:0*/ __PVT__helper_14_dump;
        CData/*0:0*/ __PVT__helper_15_clean;
        CData/*0:0*/ __PVT__helper_15_dump;
        CData/*0:0*/ __PVT__helper_16_clean;
        CData/*0:0*/ __PVT__helper_16_dump;
        CData/*0:0*/ __PVT__helper_17_clean;
        CData/*0:0*/ __PVT__helper_17_dump;
        CData/*0:0*/ __PVT__helper_18_clean;
        CData/*0:0*/ __PVT__helper_18_dump;
        CData/*0:0*/ __PVT__helper_19_clean;
        CData/*0:0*/ __PVT__helper_19_dump;
        CData/*0:0*/ __PVT__helper_20_clean;
        CData/*0:0*/ __PVT__helper_20_dump;
        CData/*0:0*/ __PVT__helper_21_clean;
        CData/*0:0*/ __PVT__helper_21_dump;
        CData/*0:0*/ __PVT__helper_22_clean;
        CData/*0:0*/ __PVT__helper_22_dump;
        CData/*0:0*/ __PVT__helper_23_clean;
        CData/*0:0*/ __PVT__helper_23_dump;
        CData/*0:0*/ __PVT__buffer_0_valid;
        CData/*0:0*/ __PVT__buffer_0_rdy;
        CData/*2:0*/ __PVT__buffer_0_task_channel;
        CData/*0:0*/ __PVT__buffer_0_task_set;
        CData/*2:0*/ __PVT__buffer_0_task_tag;
        CData/*0:0*/ __PVT__buffer_0_task_off;
        CData/*1:0*/ __PVT__buffer_0_task_alias;
        CData/*2:0*/ __PVT__buffer_0_task_opcode;
        CData/*2:0*/ __PVT__buffer_0_task_param;
        CData/*2:0*/ __PVT__buffer_0_task_size;
        CData/*4:0*/ __PVT__buffer_0_task_sourceId;
        CData/*3:0*/ __PVT__buffer_0_waitMP;
        CData/*3:0*/ __PVT__buffer_0_waitMS;
        CData/*0:0*/ __PVT__buffer_1_valid;
    };
    struct {
        CData/*0:0*/ __PVT__buffer_1_rdy;
        CData/*2:0*/ __PVT__buffer_1_task_channel;
        CData/*0:0*/ __PVT__buffer_1_task_set;
        CData/*2:0*/ __PVT__buffer_1_task_tag;
        CData/*0:0*/ __PVT__buffer_1_task_off;
        CData/*1:0*/ __PVT__buffer_1_task_alias;
        CData/*2:0*/ __PVT__buffer_1_task_opcode;
        CData/*2:0*/ __PVT__buffer_1_task_param;
        CData/*2:0*/ __PVT__buffer_1_task_size;
        CData/*4:0*/ __PVT__buffer_1_task_sourceId;
        CData/*3:0*/ __PVT__buffer_1_waitMP;
        CData/*3:0*/ __PVT__buffer_1_waitMS;
        CData/*0:0*/ __PVT__buffer_2_valid;
        CData/*0:0*/ __PVT__buffer_2_rdy;
        CData/*2:0*/ __PVT__buffer_2_task_channel;
        CData/*0:0*/ __PVT__buffer_2_task_set;
        CData/*2:0*/ __PVT__buffer_2_task_tag;
        CData/*0:0*/ __PVT__buffer_2_task_off;
        CData/*1:0*/ __PVT__buffer_2_task_alias;
        CData/*2:0*/ __PVT__buffer_2_task_opcode;
        CData/*2:0*/ __PVT__buffer_2_task_param;
        CData/*2:0*/ __PVT__buffer_2_task_size;
        CData/*4:0*/ __PVT__buffer_2_task_sourceId;
        CData/*3:0*/ __PVT__buffer_2_waitMP;
        CData/*3:0*/ __PVT__buffer_2_waitMS;
        CData/*0:0*/ __PVT__buffer_3_valid;
        CData/*0:0*/ __PVT__buffer_3_rdy;
        CData/*2:0*/ __PVT__buffer_3_task_channel;
        CData/*0:0*/ __PVT__buffer_3_task_set;
        CData/*2:0*/ __PVT__buffer_3_task_tag;
        CData/*0:0*/ __PVT__buffer_3_task_off;
        CData/*1:0*/ __PVT__buffer_3_task_alias;
        CData/*2:0*/ __PVT__buffer_3_task_opcode;
        CData/*2:0*/ __PVT__buffer_3_task_param;
        CData/*2:0*/ __PVT__buffer_3_task_size;
        CData/*4:0*/ __PVT__buffer_3_task_sourceId;
        CData/*3:0*/ __PVT__buffer_3_waitMP;
        CData/*3:0*/ __PVT__buffer_3_waitMS;
        CData/*0:0*/ __PVT__full;
        CData/*0:0*/ __PVT___canFlow_T_10;
        CData/*0:0*/ __PVT___canFlow_T_28;
        CData/*0:0*/ __PVT___canFlow_T_37;
        CData/*3:0*/ __PVT___canFlow_T_38;
        CData/*0:0*/ __PVT___canFlow_T_46;
        CData/*0:0*/ __PVT__canFlow;
        CData/*0:0*/ __PVT__io_hasMergeA_REG_set;
        CData/*2:0*/ __PVT__io_hasMergeA_REG_tag;
        CData/*0:0*/ __PVT__dup;
        CData/*1:0*/ __PVT__insertIdx;
        CData/*0:0*/ __PVT__alloc;
        CData/*0:0*/ __PVT__s1Block;
        CData/*3:0*/ __PVT___buffer_waitMP_T;
        CData/*0:0*/ __PVT___GEN_216;
        CData/*0:0*/ __PVT___GEN_217;
        CData/*0:0*/ __PVT___GEN_218;
        CData/*0:0*/ __PVT___GEN_219;
        CData/*0:0*/ __PVT___pipeBlockOut_T_2;
        CData/*0:0*/ __PVT___pipeBlockOut_T_3;
        CData/*0:0*/ __PVT___pipeBlockOut_T_4;
        CData/*0:0*/ __PVT___pipeBlockOut_T_5;
        CData/*3:0*/ __PVT___waitMSUpdate_T_1;
        CData/*3:0*/ __PVT___waitMSUpdate_T_38;
        CData/*3:0*/ __PVT__waitMSUpdate;
        CData/*0:0*/ __PVT__s1_Block;
    };
    struct {
        CData/*2:0*/ __PVT___GEN_433;
        CData/*3:0*/ __PVT___waitMSUpdate_T_40;
        CData/*3:0*/ __PVT___waitMSUpdate_T_77;
        CData/*3:0*/ __PVT__waitMSUpdate_1;
        CData/*0:0*/ __PVT__s1_Block_1;
        CData/*2:0*/ __PVT___GEN_438;
        CData/*3:0*/ __PVT___waitMSUpdate_T_79;
        CData/*3:0*/ __PVT___waitMSUpdate_T_116;
        CData/*3:0*/ __PVT__waitMSUpdate_2;
        CData/*0:0*/ __PVT__s1_Block_2;
        CData/*2:0*/ __PVT___GEN_443;
        CData/*3:0*/ __PVT___waitMSUpdate_T_118;
        CData/*3:0*/ __PVT___waitMSUpdate_T_155;
        CData/*3:0*/ __PVT__waitMSUpdate_3;
        CData/*0:0*/ __PVT__s1_Block_3;
        CData/*2:0*/ __PVT___GEN_448;
        CData/*0:0*/ __PVT___io_out_valid_T;
        CData/*0:0*/ __PVT__REG;
        CData/*0:0*/ __PVT__REG_1;
        CData/*0:0*/ __PVT__enable_REG;
        CData/*0:0*/ __PVT__enable;
        CData/*0:0*/ __PVT__REG_2;
        CData/*0:0*/ __PVT__REG_3;
        CData/*0:0*/ __PVT__enable_REG_1;
        CData/*0:0*/ __PVT__enable_1;
        CData/*0:0*/ __PVT__REG_4;
        CData/*0:0*/ __PVT__REG_5;
        CData/*0:0*/ __PVT__enable_REG_2;
        CData/*0:0*/ __PVT__enable_2;
        CData/*0:0*/ __PVT__REG_6;
        CData/*0:0*/ __PVT__REG_7;
        CData/*0:0*/ __PVT__enable_REG_3;
        CData/*0:0*/ __PVT__enable_3;
        CData/*1:0*/ __VdfgRegularize_ha1527a7f_2_6;
        CData/*0:0*/ __PVT__issueArb__DOT___ctrl_validMask_grantMask_lastGrant_T;
        CData/*1:0*/ __PVT__issueArb__DOT__ctrl_validMask_grantMask_lastGrant;
        CData/*0:0*/ __PVT__chosenQ__DOT__maybe_full;
        CData/*0:0*/ __PVT__chosenQ__DOT__do_deq;
        CData/*0:0*/ __VdlySet__chosenQ__DOT__ram_bits_task_replTask__v0;
        CData/*0:0*/ __VdlySet__chosenQ__DOT__ram_bits_task_dsWen__v0;
        CData/*0:0*/ __VdlySet__chosenQ__DOT__ram_bits_task_meta_accessed__v0;
        CData/*0:0*/ __VdlySet__chosenQ__DOT__ram_bits_task_meta_prefetchSrc__v0;
        CData/*0:0*/ __VdlySet__chosenQ__DOT__ram_bits_task_meta_prefetch__v0;
        CData/*0:0*/ __VdlySet__chosenQ__DOT__ram_bits_task_snpHitRelease__v0;
        CData/*2:0*/ __VdlyVal__chosenQ__DOT__ram_bits_task_param__v0;
        CData/*0:0*/ __VdlySet__chosenQ__DOT__ram_bits_task_param__v0;
        CData/*0:0*/ __VdlySet__chosenQ__DOT__ram_bits_task_needHint__v0;
        CData/*0:0*/ __VdlySet__chosenQ__DOT__ram_bits_task_aMergeTask_meta_alias__v0;
        CData/*0:0*/ __VdlySet__chosenQ__DOT__ram_bits_task_aMergeTask_meta_clients__v0;
        CData/*0:0*/ __VdlySet__chosenQ__DOT__ram_bits_task_metaWen__v0;
        CData/*1:0*/ __VdlyVal__chosenQ__DOT__ram_bits_task_alias__v0;
        CData/*0:0*/ __VdlySet__chosenQ__DOT__ram_bits_task_alias__v0;
        CData/*0:0*/ __VdlySet__chosenQ__DOT__ram_bits_task_meta_clients__v0;
        CData/*0:0*/ __VdlySet__chosenQ__DOT__ram_bits_task_meta_alias__v0;
        CData/*0:0*/ __VdlyVal__chosenQ__DOT__ram_bits_task_off__v0;
        CData/*0:0*/ __VdlySet__chosenQ__DOT__ram_bits_task_off__v0;
        CData/*0:0*/ __VdlySet__chosenQ__DOT__ram_bits_task_aMergeTask_meta_accessed__v0;
        CData/*0:0*/ __VdlySet__chosenQ__DOT__ram_bits_task_tagWen__v0;
        CData/*0:0*/ __VdlySet__chosenQ__DOT__ram_bits_task_needProbeAckData__v0;
        CData/*0:0*/ __VdlySet__chosenQ__DOT__ram_bits_task_aMergeTask_meta_dirty__v0;
        CData/*0:0*/ __VdlySet__chosenQ__DOT__ram_bits_task_useProbeData__v0;
        CData/*0:0*/ __VdlySet__chosenQ__DOT__ram_bits_task_aMergeTask_meta_state__v0;
        CData/*0:0*/ __VdlySet__chosenQ__DOT__ram_bits_task_fromL2pft__v0;
        CData/*0:0*/ __VdlySet__chosenQ__DOT__ram_bits_task_aMergeTask_meta_prefetch__v0;
    };
    struct {
        CData/*0:0*/ __VdlySet__chosenQ__DOT__ram_bits_task_aMergeTask_meta_prefetchSrc__v0;
        CData/*0:0*/ __VdlySet__chosenQ__DOT__ram_bits_task_way__v0;
        CData/*0:0*/ __VdlySet__chosenQ__DOT__ram_bits_task_meta_dirty__v0;
        CData/*0:0*/ __VdlySet__chosenQ__DOT__ram_bits_task_meta_state__v0;
        CData/*0:0*/ __VdlySet__chosenQ__DOT__ram_bits_task_snpHitReleaseIdx__v0;
        SData/*15:0*/ __PVT__bufferTimer_0;
        SData/*15:0*/ __PVT__bufferTimer_1;
        SData/*15:0*/ __PVT__bufferTimer_2;
        SData/*15:0*/ __PVT__bufferTimer_3;
        SData/*15:0*/ __PVT___bufferTimer_0_T_1;
        SData/*15:0*/ __PVT___bufferTimer_1_T_1;
        SData/*15:0*/ __PVT___bufferTimer_2_T_1;
        SData/*15:0*/ __PVT___bufferTimer_3_T_1;
        QData/*63:0*/ __PVT__helper_timer;
        QData/*63:0*/ __PVT__helper_1_timer;
        QData/*63:0*/ __PVT__helper_2_timer;
        QData/*63:0*/ __PVT__helper_3_timer;
        QData/*63:0*/ __PVT__helper_4_timer;
        QData/*63:0*/ __PVT__helper_5_timer;
        QData/*63:0*/ __PVT__helper_6_timer;
        QData/*63:0*/ __PVT__helper_7_timer;
        QData/*63:0*/ __PVT__helper_8_timer;
        QData/*63:0*/ __PVT__helper_9_timer;
        QData/*63:0*/ __PVT__helper_10_timer;
        QData/*63:0*/ __PVT__helper_11_timer;
        QData/*63:0*/ __PVT__helper_12_timer;
        QData/*63:0*/ __PVT__helper_13_timer;
        QData/*63:0*/ __PVT__helper_14_timer;
        QData/*63:0*/ __PVT__helper_15_timer;
        QData/*63:0*/ __PVT__helper_16_timer;
        QData/*63:0*/ __PVT__helper_17_timer;
        QData/*63:0*/ __PVT__helper_18_timer;
        QData/*63:0*/ __PVT__helper_19_timer;
        QData/*63:0*/ __PVT__helper_20_timer;
        QData/*63:0*/ __PVT__helper_21_timer;
        QData/*63:0*/ __PVT__helper_22_timer;
        QData/*63:0*/ __PVT__helper_23_timer;
        QData/*63:0*/ __PVT__counter;
        QData/*63:0*/ __PVT__next_counter;
        QData/*63:0*/ __PVT__counter_1;
        QData/*63:0*/ __PVT__next_counter_1;
        QData/*63:0*/ __PVT__counter_2;
        QData/*63:0*/ __PVT__next_counter_2;
        QData/*63:0*/ __PVT__counter_3;
        QData/*63:0*/ __PVT__next_counter_3;
        QData/*63:0*/ __PVT__counter_4;
        QData/*63:0*/ __PVT__next_counter_4;
        QData/*63:0*/ __PVT__counter_5;
        QData/*63:0*/ __PVT__next_counter_5;
        QData/*63:0*/ __PVT__counter_6;
        QData/*63:0*/ __PVT__next_counter_6;
        QData/*63:0*/ __PVT__counter_7;
        QData/*63:0*/ __PVT__next_counter_7;
        QData/*63:0*/ __PVT__counter_8;
        QData/*63:0*/ __PVT__next_counter_8;
        QData/*63:0*/ __PVT__counter_9;
        QData/*63:0*/ __PVT__next_counter_9;
        QData/*63:0*/ __PVT__counter_10;
        QData/*63:0*/ __PVT__next_counter_10;
        QData/*63:0*/ __PVT__counter_11;
        QData/*63:0*/ __PVT__next_counter_11;
        QData/*63:0*/ __PVT__counter_12;
        QData/*63:0*/ __PVT___counter_T_13;
        QData/*63:0*/ __PVT__counter_13;
    };
    struct {
        QData/*63:0*/ __PVT___counter_T_15;
        QData/*63:0*/ __PVT__counter_14;
        QData/*63:0*/ __PVT___counter_T_17;
        QData/*63:0*/ __PVT__counter_15;
        QData/*63:0*/ __PVT___counter_T_19;
        QData/*63:0*/ __PVT__counter_16;
        QData/*63:0*/ __PVT___counter_T_21;
        QData/*63:0*/ __PVT__counter_17;
        QData/*63:0*/ __PVT___counter_T_23;
        QData/*63:0*/ __PVT__counter_18;
        QData/*63:0*/ __PVT___counter_T_25;
        QData/*63:0*/ __PVT__counter_19;
        QData/*63:0*/ __PVT___counter_T_27;
        QData/*63:0*/ __PVT__counter_20;
        QData/*63:0*/ __PVT___counter_T_29;
        QData/*63:0*/ __PVT__counter_21;
        QData/*63:0*/ __PVT___counter_T_31;
        QData/*63:0*/ __PVT__counter_22;
        QData/*63:0*/ __PVT___counter_T_33;
        QData/*63:0*/ __PVT__counter_23;
        QData/*63:0*/ __PVT___counter_T_35;
        QData/*63:0*/ __PVT__counter_24;
        QData/*63:0*/ __PVT___counter_T_37;
        QData/*63:0*/ __PVT__counter_25;
        QData/*63:0*/ __PVT___counter_T_39;
        QData/*63:0*/ __PVT__counter_26;
        QData/*63:0*/ __PVT___counter_T_41;
        QData/*63:0*/ __PVT__counter_27;
        QData/*63:0*/ __PVT___counter_T_43;
        QData/*63:0*/ __PVT__counter_28;
        QData/*63:0*/ __PVT___counter_T_45;
        QData/*63:0*/ __PVT__counter_29;
        QData/*63:0*/ __PVT___counter_T_47;
        QData/*63:0*/ __PVT__counter_30;
        QData/*63:0*/ __PVT___counter_T_49;
        QData/*63:0*/ __PVT__counter_31;
        QData/*63:0*/ __PVT___counter_T_51;
        QData/*63:0*/ __PVT__counter_32;
        QData/*63:0*/ __PVT___counter_T_53;
        QData/*63:0*/ __PVT__counter_33;
        QData/*63:0*/ __PVT___counter_T_55;
        QData/*63:0*/ __PVT__counter_34;
        QData/*63:0*/ __PVT___counter_T_57;
        QData/*63:0*/ __PVT__counter_35;
        QData/*63:0*/ __PVT___counter_T_59;
        QData/*63:0*/ __PVT__counter_36;
        QData/*63:0*/ __PVT___counter_T_61;
        QData/*63:0*/ __PVT__counter_37;
        QData/*63:0*/ __PVT___counter_T_63;
        QData/*63:0*/ __PVT__counter_38;
        QData/*63:0*/ __PVT___counter_T_65;
        QData/*63:0*/ __PVT__counter_39;
        QData/*63:0*/ __PVT___counter_T_67;
        QData/*63:0*/ __PVT__counter_40;
        QData/*63:0*/ __PVT___counter_T_69;
        QData/*63:0*/ __PVT__counter_41;
        QData/*63:0*/ __PVT___counter_T_71;
        QData/*63:0*/ __PVT__counter_42;
        QData/*63:0*/ __PVT___counter_T_73;
        QData/*63:0*/ __PVT__counter_43;
        QData/*63:0*/ __PVT___counter_T_75;
        QData/*63:0*/ __PVT__counter_44;
        QData/*63:0*/ __PVT___counter_T_77;
        QData/*63:0*/ __PVT__counter_45;
    };
    struct {
        QData/*63:0*/ __PVT___counter_T_79;
        QData/*63:0*/ __PVT__counter_46;
        QData/*63:0*/ __PVT___counter_T_81;
        QData/*63:0*/ __PVT__counter_47;
        QData/*63:0*/ __PVT___counter_T_83;
        QData/*63:0*/ __PVT__counter_48;
        QData/*63:0*/ __PVT___counter_T_85;
        QData/*63:0*/ __PVT__counter_49;
        QData/*63:0*/ __PVT___counter_T_87;
        QData/*63:0*/ __PVT__counter_50;
        QData/*63:0*/ __PVT___counter_T_89;
        QData/*63:0*/ __PVT__max;
        QData/*63:0*/ __PVT__next_max;
        QData/*63:0*/ __PVT__counter_51;
        QData/*63:0*/ __PVT___counter_T_91;
        QData/*63:0*/ __PVT__counter_52;
        QData/*63:0*/ __PVT___counter_T_93;
        QData/*63:0*/ __PVT__counter_53;
        QData/*63:0*/ __PVT___counter_T_95;
        QData/*63:0*/ __PVT__counter_54;
        QData/*63:0*/ __PVT___counter_T_97;
        QData/*63:0*/ __PVT__counter_55;
        QData/*63:0*/ __PVT___counter_T_99;
        QData/*63:0*/ __PVT__counter_56;
        QData/*63:0*/ __PVT___counter_T_101;
        QData/*63:0*/ __PVT__counter_57;
        QData/*63:0*/ __PVT___counter_T_103;
        QData/*63:0*/ __PVT__counter_58;
        QData/*63:0*/ __PVT___counter_T_105;
        QData/*63:0*/ __PVT__counter_59;
        QData/*63:0*/ __PVT___counter_T_107;
        QData/*63:0*/ __PVT__counter_60;
        QData/*63:0*/ __PVT___counter_T_109;
        QData/*63:0*/ __PVT__counter_61;
        QData/*63:0*/ __PVT___counter_T_111;
        QData/*63:0*/ __PVT__counter_62;
        QData/*63:0*/ __PVT___counter_T_113;
        QData/*63:0*/ __PVT__counter_63;
        QData/*63:0*/ __PVT___counter_T_115;
        QData/*63:0*/ __PVT__counter_64;
        QData/*63:0*/ __PVT___counter_T_117;
        QData/*63:0*/ __PVT__counter_65;
        QData/*63:0*/ __PVT___counter_T_119;
        QData/*63:0*/ __PVT__counter_66;
        QData/*63:0*/ __PVT___counter_T_121;
        QData/*63:0*/ __PVT__counter_67;
        QData/*63:0*/ __PVT___counter_T_123;
        QData/*63:0*/ __PVT__counter_68;
        QData/*63:0*/ __PVT___counter_T_125;
        QData/*63:0*/ __PVT__counter_69;
        QData/*63:0*/ __PVT___counter_T_127;
        QData/*63:0*/ __PVT__counter_70;
        QData/*63:0*/ __PVT___counter_T_129;
        QData/*63:0*/ __PVT__counter_71;
        QData/*63:0*/ __PVT___counter_T_131;
        QData/*63:0*/ __PVT__counter_72;
        QData/*63:0*/ __PVT___counter_T_133;
        QData/*63:0*/ __PVT__counter_73;
        QData/*63:0*/ __PVT___counter_T_135;
        QData/*63:0*/ __PVT__counter_74;
        QData/*63:0*/ __PVT___counter_T_137;
        QData/*63:0*/ __PVT__counter_75;
        QData/*63:0*/ __PVT___counter_T_139;
        QData/*63:0*/ __PVT__counter_76;
    };
    struct {
        QData/*63:0*/ __PVT___counter_T_141;
        QData/*63:0*/ __PVT__counter_77;
        QData/*63:0*/ __PVT___counter_T_143;
        QData/*63:0*/ __PVT__counter_78;
        QData/*63:0*/ __PVT___counter_T_145;
        QData/*63:0*/ __PVT__counter_79;
        QData/*63:0*/ __PVT___counter_T_147;
        QData/*63:0*/ __PVT__counter_80;
        QData/*63:0*/ __PVT___counter_T_149;
        QData/*63:0*/ __PVT__counter_81;
        QData/*63:0*/ __PVT___counter_T_151;
        QData/*63:0*/ __PVT__counter_82;
        QData/*63:0*/ __PVT___counter_T_153;
        QData/*63:0*/ __PVT__counter_83;
        QData/*63:0*/ __PVT___counter_T_155;
        QData/*63:0*/ __PVT__counter_84;
        QData/*63:0*/ __PVT___counter_T_157;
        QData/*63:0*/ __PVT__counter_85;
        QData/*63:0*/ __PVT___counter_T_159;
        QData/*63:0*/ __PVT__counter_86;
        QData/*63:0*/ __PVT___counter_T_161;
        QData/*63:0*/ __PVT__counter_87;
        QData/*63:0*/ __PVT___counter_T_163;
        QData/*63:0*/ __PVT__counter_88;
        QData/*63:0*/ __PVT___counter_T_165;
        QData/*63:0*/ __PVT__counter_89;
        QData/*63:0*/ __PVT___counter_T_167;
        QData/*63:0*/ __PVT__max_1;
        QData/*63:0*/ __PVT__next_max_1;
        QData/*63:0*/ __PVT__counter_90;
        QData/*63:0*/ __PVT___counter_T_169;
        QData/*63:0*/ __PVT__counter_91;
        QData/*63:0*/ __PVT___counter_T_171;
        QData/*63:0*/ __PVT__counter_92;
        QData/*63:0*/ __PVT___counter_T_173;
        QData/*63:0*/ __PVT__counter_93;
        QData/*63:0*/ __PVT___counter_T_175;
        QData/*63:0*/ __PVT__counter_94;
        QData/*63:0*/ __PVT___counter_T_177;
        QData/*63:0*/ __PVT__counter_95;
        QData/*63:0*/ __PVT___counter_T_179;
        QData/*63:0*/ __PVT__counter_96;
        QData/*63:0*/ __PVT___counter_T_181;
        QData/*63:0*/ __PVT__counter_97;
        QData/*63:0*/ __PVT___counter_T_183;
        QData/*63:0*/ __PVT__counter_98;
        QData/*63:0*/ __PVT___counter_T_185;
        QData/*63:0*/ __PVT__counter_99;
        QData/*63:0*/ __PVT___counter_T_187;
        QData/*63:0*/ __PVT__counter_100;
        QData/*63:0*/ __PVT___counter_T_189;
        QData/*63:0*/ __PVT__counter_101;
        QData/*63:0*/ __PVT___counter_T_191;
        QData/*63:0*/ __PVT__counter_102;
        QData/*63:0*/ __PVT___counter_T_193;
        QData/*63:0*/ __PVT__counter_103;
        QData/*63:0*/ __PVT___counter_T_195;
        QData/*63:0*/ __PVT__counter_104;
        QData/*63:0*/ __PVT___counter_T_197;
        QData/*63:0*/ __PVT__counter_105;
        QData/*63:0*/ __PVT___counter_T_199;
        QData/*63:0*/ __PVT__counter_106;
        QData/*63:0*/ __PVT___counter_T_201;
        QData/*63:0*/ __PVT__counter_107;
    };
    struct {
        QData/*63:0*/ __PVT___counter_T_203;
        QData/*63:0*/ __PVT__counter_108;
        QData/*63:0*/ __PVT___counter_T_205;
        QData/*63:0*/ __PVT__counter_109;
        QData/*63:0*/ __PVT___counter_T_207;
        QData/*63:0*/ __PVT__counter_110;
        QData/*63:0*/ __PVT___counter_T_209;
        QData/*63:0*/ __PVT__counter_111;
        QData/*63:0*/ __PVT___counter_T_211;
        QData/*63:0*/ __PVT__counter_112;
        QData/*63:0*/ __PVT___counter_T_213;
        QData/*63:0*/ __PVT__counter_113;
        QData/*63:0*/ __PVT___counter_T_215;
        QData/*63:0*/ __PVT__counter_114;
        QData/*63:0*/ __PVT___counter_T_217;
        QData/*63:0*/ __PVT__counter_115;
        QData/*63:0*/ __PVT___counter_T_219;
        QData/*63:0*/ __PVT__counter_116;
        QData/*63:0*/ __PVT___counter_T_221;
        QData/*63:0*/ __PVT__counter_117;
        QData/*63:0*/ __PVT___counter_T_223;
        QData/*63:0*/ __PVT__counter_118;
        QData/*63:0*/ __PVT___counter_T_225;
        QData/*63:0*/ __PVT__counter_119;
        QData/*63:0*/ __PVT___counter_T_227;
        QData/*63:0*/ __PVT__counter_120;
        QData/*63:0*/ __PVT___counter_T_229;
        QData/*63:0*/ __PVT__counter_121;
        QData/*63:0*/ __PVT___counter_T_231;
        QData/*63:0*/ __PVT__counter_122;
        QData/*63:0*/ __PVT___counter_T_233;
        QData/*63:0*/ __PVT__counter_123;
        QData/*63:0*/ __PVT___counter_T_235;
        QData/*63:0*/ __PVT__counter_124;
        QData/*63:0*/ __PVT___counter_T_237;
        QData/*63:0*/ __PVT__counter_125;
        QData/*63:0*/ __PVT___counter_T_239;
        QData/*63:0*/ __PVT__counter_126;
        QData/*63:0*/ __PVT___counter_T_241;
        QData/*63:0*/ __PVT__counter_127;
        QData/*63:0*/ __PVT___counter_T_243;
        QData/*63:0*/ __PVT__counter_128;
        QData/*63:0*/ __PVT___counter_T_245;
        QData/*63:0*/ __PVT__max_2;
        QData/*63:0*/ __PVT__next_max_2;
        QData/*63:0*/ __PVT__counter_129;
        QData/*63:0*/ __PVT___counter_T_247;
        QData/*63:0*/ __PVT__counter_130;
        QData/*63:0*/ __PVT___counter_T_249;
        QData/*63:0*/ __PVT__counter_131;
        QData/*63:0*/ __PVT___counter_T_251;
        QData/*63:0*/ __PVT__counter_132;
        QData/*63:0*/ __PVT___counter_T_253;
        QData/*63:0*/ __PVT__counter_133;
        QData/*63:0*/ __PVT___counter_T_255;
        QData/*63:0*/ __PVT__counter_134;
        QData/*63:0*/ __PVT___counter_T_257;
        QData/*63:0*/ __PVT__counter_135;
        QData/*63:0*/ __PVT___counter_T_259;
        QData/*63:0*/ __PVT__counter_136;
        QData/*63:0*/ __PVT___counter_T_261;
        QData/*63:0*/ __PVT__counter_137;
        QData/*63:0*/ __PVT___counter_T_263;
        QData/*63:0*/ __PVT__counter_138;
    };
    struct {
        QData/*63:0*/ __PVT___counter_T_265;
        QData/*63:0*/ __PVT__counter_139;
        QData/*63:0*/ __PVT___counter_T_267;
        QData/*63:0*/ __PVT__counter_140;
        QData/*63:0*/ __PVT___counter_T_269;
        QData/*63:0*/ __PVT__counter_141;
        QData/*63:0*/ __PVT___counter_T_271;
        QData/*63:0*/ __PVT__counter_142;
        QData/*63:0*/ __PVT___counter_T_273;
        QData/*63:0*/ __PVT__counter_143;
        QData/*63:0*/ __PVT___counter_T_275;
        QData/*63:0*/ __PVT__counter_144;
        QData/*63:0*/ __PVT___counter_T_277;
        QData/*63:0*/ __PVT__counter_145;
        QData/*63:0*/ __PVT___counter_T_279;
        QData/*63:0*/ __PVT__counter_146;
        QData/*63:0*/ __PVT___counter_T_281;
        QData/*63:0*/ __PVT__counter_147;
        QData/*63:0*/ __PVT___counter_T_283;
        QData/*63:0*/ __PVT__counter_148;
        QData/*63:0*/ __PVT___counter_T_285;
        QData/*63:0*/ __PVT__counter_149;
        QData/*63:0*/ __PVT___counter_T_287;
        QData/*63:0*/ __PVT__counter_150;
        QData/*63:0*/ __PVT___counter_T_289;
        QData/*63:0*/ __PVT__counter_151;
        QData/*63:0*/ __PVT___counter_T_291;
        QData/*63:0*/ __PVT__counter_152;
        QData/*63:0*/ __PVT___counter_T_293;
        QData/*63:0*/ __PVT__counter_153;
        QData/*63:0*/ __PVT___counter_T_295;
        QData/*63:0*/ __PVT__counter_154;
        QData/*63:0*/ __PVT___counter_T_297;
        QData/*63:0*/ __PVT__counter_155;
        QData/*63:0*/ __PVT___counter_T_299;
        QData/*63:0*/ __PVT__counter_156;
        QData/*63:0*/ __PVT___counter_T_301;
        QData/*63:0*/ __PVT__counter_157;
        QData/*63:0*/ __PVT___counter_T_303;
        QData/*63:0*/ __PVT__counter_158;
        QData/*63:0*/ __PVT___counter_T_305;
        QData/*63:0*/ __PVT__counter_159;
        QData/*63:0*/ __PVT___counter_T_307;
        QData/*63:0*/ __PVT__counter_160;
        QData/*63:0*/ __PVT___counter_T_309;
        QData/*63:0*/ __PVT__counter_161;
        QData/*63:0*/ __PVT___counter_T_311;
        QData/*63:0*/ __PVT__counter_162;
        QData/*63:0*/ __PVT___counter_T_313;
        QData/*63:0*/ __PVT__counter_163;
        QData/*63:0*/ __PVT___counter_T_315;
        QData/*63:0*/ __PVT__counter_164;
        QData/*63:0*/ __PVT___counter_T_317;
        QData/*63:0*/ __PVT__counter_165;
        QData/*63:0*/ __PVT___counter_T_319;
        QData/*63:0*/ __PVT__counter_166;
        QData/*63:0*/ __PVT___counter_T_321;
        QData/*63:0*/ __PVT__counter_167;
        QData/*63:0*/ __PVT___counter_T_323;
        QData/*63:0*/ __PVT__max_3;
        QData/*63:0*/ __PVT__next_max_3;
        VlUnpacked<CData/*2:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_channel;
        VlUnpacked<CData/*0:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_set;
        VlUnpacked<CData/*2:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_tag;
    };
    struct {
        VlUnpacked<CData/*0:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_off;
        VlUnpacked<CData/*1:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_alias;
        VlUnpacked<CData/*2:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_opcode;
        VlUnpacked<CData/*2:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_param;
        VlUnpacked<CData/*4:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_sourceId;
        VlUnpacked<CData/*0:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_needProbeAckData;
        VlUnpacked<CData/*0:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_mshrTask;
        VlUnpacked<CData/*7:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_mshrId;
        VlUnpacked<CData/*0:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_useProbeData;
        VlUnpacked<CData/*0:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_fromL2pft;
        VlUnpacked<CData/*0:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_needHint;
        VlUnpacked<CData/*0:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_way;
        VlUnpacked<CData/*0:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_meta_dirty;
        VlUnpacked<CData/*1:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_meta_state;
        VlUnpacked<CData/*0:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_meta_clients;
        VlUnpacked<CData/*1:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_meta_alias;
        VlUnpacked<CData/*0:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_meta_prefetch;
        VlUnpacked<CData/*2:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_meta_prefetchSrc;
        VlUnpacked<CData/*0:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_meta_accessed;
        VlUnpacked<CData/*0:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_metaWen;
        VlUnpacked<CData/*0:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_tagWen;
        VlUnpacked<CData/*0:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_dsWen;
        VlUnpacked<CData/*0:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_replTask;
        VlUnpacked<CData/*3:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_reqSource;
        VlUnpacked<CData/*0:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_mergeA;
        VlUnpacked<CData/*2:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_aMergeTask_opcode;
        VlUnpacked<CData/*4:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_aMergeTask_sourceId;
        VlUnpacked<CData/*0:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_aMergeTask_meta_dirty;
        VlUnpacked<CData/*1:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_aMergeTask_meta_state;
        VlUnpacked<CData/*0:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_aMergeTask_meta_clients;
        VlUnpacked<CData/*1:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_aMergeTask_meta_alias;
        VlUnpacked<CData/*0:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_aMergeTask_meta_prefetch;
        VlUnpacked<CData/*2:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_aMergeTask_meta_prefetchSrc;
        VlUnpacked<CData/*0:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_aMergeTask_meta_accessed;
        VlUnpacked<CData/*0:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_snpHitRelease;
        VlUnpacked<CData/*7:0*/, 1> __PVT__chosenQ__DOT__ram_bits_task_snpHitReleaseIdx;
        VlUnpacked<CData/*1:0*/, 1> __PVT__chosenQ__DOT__ram_id;
    };

    // INTERNAL VARIABLES
    VVerifyTop__Syms* const vlSymsp;

    // CONSTRUCTORS
    VVerifyTop_RequestBuffer(VVerifyTop__Syms* symsp, const char* v__name);
    ~VVerifyTop_RequestBuffer();
    VL_UNCOPYABLE(VVerifyTop_RequestBuffer);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
