// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See VVerifyTop.h for the primary calling header

#ifndef VERILATED_VVERIFYTOP_MAINPIPE_2_H_
#define VERILATED_VVERIFYTOP_MAINPIPE_2_H_  // guard

#include "verilated.h"


class VVerifyTop__Syms;

class alignas(VL_CACHE_LINE_BYTES) VVerifyTop_MainPipe_2 final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clock,0,0);
        VL_IN8(reset,0,0);
        VL_IN8(io_taskFromArb_s2_valid,0,0);
        VL_IN8(io_taskFromArb_s2_bits_channel,2,0);
        VL_IN8(io_taskFromArb_s2_bits_set,1,0);
        VL_IN8(io_taskFromArb_s2_bits_tag,1,0);
        VL_IN8(io_taskFromArb_s2_bits_off,0,0);
        VL_IN8(io_taskFromArb_s2_bits_alias,1,0);
        VL_IN8(io_taskFromArb_s2_bits_opcode,2,0);
        VL_IN8(io_taskFromArb_s2_bits_param,2,0);
        VL_IN8(io_taskFromArb_s2_bits_size,0,0);
        VL_IN8(io_taskFromArb_s2_bits_sourceId,7,0);
        VL_IN8(io_taskFromArb_s2_bits_needProbeAckData,0,0);
        VL_IN8(io_taskFromArb_s2_bits_mshrTask,0,0);
        VL_IN8(io_taskFromArb_s2_bits_mshrId,7,0);
        VL_IN8(io_taskFromArb_s2_bits_useProbeData,0,0);
        VL_IN8(io_taskFromArb_s2_bits_dirty,0,0);
        VL_IN8(io_taskFromArb_s2_bits_way,0,0);
        VL_IN8(io_taskFromArb_s2_bits_meta_dirty,0,0);
        VL_IN8(io_taskFromArb_s2_bits_meta_state,1,0);
        VL_IN8(io_taskFromArb_s2_bits_meta_clients,0,0);
        VL_IN8(io_taskFromArb_s2_bits_meta_alias,1,0);
        VL_IN8(io_taskFromArb_s2_bits_meta_accessed,0,0);
        VL_IN8(io_taskFromArb_s2_bits_metaWen,0,0);
        VL_IN8(io_taskFromArb_s2_bits_tagWen,0,0);
        VL_IN8(io_taskFromArb_s2_bits_dsWen,0,0);
        VL_IN8(io_taskFromArb_s2_bits_replTask,0,0);
        VL_IN8(io_taskFromArb_s2_bits_reqSource,3,0);
        VL_IN8(io_taskFromArb_s2_bits_mergeA,0,0);
        VL_IN8(io_taskFromArb_s2_bits_aMergeTask_opcode,2,0);
        VL_IN8(io_taskFromArb_s2_bits_aMergeTask_param,2,0);
        VL_IN8(io_taskFromArb_s2_bits_aMergeTask_sourceId,7,0);
        VL_IN8(io_taskFromArb_s2_bits_aMergeTask_meta_dirty,0,0);
        VL_IN8(io_taskFromArb_s2_bits_aMergeTask_meta_state,1,0);
        VL_IN8(io_taskFromArb_s2_bits_aMergeTask_meta_clients,0,0);
        VL_IN8(io_taskFromArb_s2_bits_aMergeTask_meta_alias,1,0);
        VL_IN8(io_taskFromArb_s2_bits_aMergeTask_meta_accessed,0,0);
        VL_IN8(io_fromReqArb_status_s1_tags_1,1,0);
        VL_IN8(io_fromReqArb_status_s1_sets_0,1,0);
        VL_IN8(io_fromReqArb_status_s1_sets_1,1,0);
        VL_IN8(io_fromReqArb_status_s1_sets_2,1,0);
        VL_IN8(io_fromReqArb_status_s1_sets_3,1,0);
        VL_OUT8(io_toReqArb_blockG_s1,0,0);
        VL_OUT8(io_toReqArb_blockB_s1,0,0);
        VL_OUT8(io_toReqArb_blockC_s1,0,0);
        VL_OUT8(io_toReqBuf_0,0,0);
        VL_OUT8(io_toReqBuf_1,0,0);
        VL_OUT8(io_status_vec_toD_0_valid,0,0);
        VL_OUT8(io_status_vec_toD_0_bits_channel,2,0);
        VL_OUT8(io_status_vec_toD_1_valid,0,0);
        VL_OUT8(io_status_vec_toD_1_bits_channel,2,0);
        VL_OUT8(io_status_vec_toD_2_valid,0,0);
        VL_OUT8(io_status_vec_toD_2_bits_channel,2,0);
        VL_OUT8(io_status_vec_toC_0_valid,0,0);
        VL_OUT8(io_status_vec_toC_0_bits_channel,2,0);
        VL_OUT8(io_status_vec_toC_1_valid,0,0);
        VL_OUT8(io_status_vec_toC_1_bits_channel,2,0);
        VL_OUT8(io_status_vec_toC_2_valid,0,0);
        VL_OUT8(io_status_vec_toC_2_bits_channel,2,0);
        VL_IN8(io_dirResp_s3_hit,0,0);
        VL_IN8(io_dirResp_s3_tag,1,0);
        VL_IN8(io_dirResp_s3_set,1,0);
        VL_IN8(io_dirResp_s3_way,0,0);
        VL_IN8(io_dirResp_s3_meta_dirty,0,0);
    };
    struct {
        VL_IN8(io_dirResp_s3_meta_state,1,0);
        VL_IN8(io_dirResp_s3_meta_clients,0,0);
        VL_IN8(io_dirResp_s3_meta_alias,1,0);
        VL_IN8(io_dirResp_s3_meta_accessed,0,0);
        VL_IN8(io_replResp_valid,0,0);
        VL_IN8(io_replResp_bits_way,0,0);
        VL_IN8(io_replResp_bits_meta_state,1,0);
        VL_IN8(io_replResp_bits_retry,0,0);
        VL_OUT8(io_toMSHRCtl_mshr_alloc_s3_valid,0,0);
        VL_OUT8(io_toMSHRCtl_mshr_alloc_s3_bits_dirResult_hit,0,0);
        VL_OUT8(io_toMSHRCtl_mshr_alloc_s3_bits_dirResult_tag,1,0);
        VL_OUT8(io_toMSHRCtl_mshr_alloc_s3_bits_dirResult_set,1,0);
        VL_OUT8(io_toMSHRCtl_mshr_alloc_s3_bits_dirResult_way,0,0);
        VL_OUT8(io_toMSHRCtl_mshr_alloc_s3_bits_dirResult_meta_dirty,0,0);
        VL_OUT8(io_toMSHRCtl_mshr_alloc_s3_bits_dirResult_meta_state,1,0);
        VL_OUT8(io_toMSHRCtl_mshr_alloc_s3_bits_dirResult_meta_clients,0,0);
        VL_OUT8(io_toMSHRCtl_mshr_alloc_s3_bits_dirResult_meta_alias,1,0);
        VL_OUT8(io_toMSHRCtl_mshr_alloc_s3_bits_dirResult_meta_accessed,0,0);
        VL_OUT8(io_toMSHRCtl_mshr_alloc_s3_bits_state_s_acquire,0,0);
        VL_OUT8(io_toMSHRCtl_mshr_alloc_s3_bits_state_s_rprobe,0,0);
        VL_OUT8(io_toMSHRCtl_mshr_alloc_s3_bits_state_s_pprobe,0,0);
        VL_OUT8(io_toMSHRCtl_mshr_alloc_s3_bits_state_s_probeack,0,0);
        VL_OUT8(io_toMSHRCtl_mshr_alloc_s3_bits_state_s_refill,0,0);
        VL_OUT8(io_toMSHRCtl_mshr_alloc_s3_bits_state_w_rprobeackfirst,0,0);
        VL_OUT8(io_toMSHRCtl_mshr_alloc_s3_bits_state_w_rprobeacklast,0,0);
        VL_OUT8(io_toMSHRCtl_mshr_alloc_s3_bits_state_w_pprobeackfirst,0,0);
        VL_OUT8(io_toMSHRCtl_mshr_alloc_s3_bits_state_w_pprobeacklast,0,0);
        VL_OUT8(io_toMSHRCtl_mshr_alloc_s3_bits_state_w_pprobeack,0,0);
        VL_OUT8(io_toMSHRCtl_mshr_alloc_s3_bits_state_w_grantfirst,0,0);
        VL_OUT8(io_toMSHRCtl_mshr_alloc_s3_bits_state_w_grantlast,0,0);
        VL_OUT8(io_toMSHRCtl_mshr_alloc_s3_bits_state_w_grant,0,0);
        VL_OUT8(io_toMSHRCtl_mshr_alloc_s3_bits_state_w_replResp,0,0);
        VL_OUT8(io_toMSHRCtl_mshr_alloc_s3_bits_task_channel,2,0);
        VL_OUT8(io_toMSHRCtl_mshr_alloc_s3_bits_task_set,1,0);
        VL_OUT8(io_toMSHRCtl_mshr_alloc_s3_bits_task_tag,1,0);
        VL_OUT8(io_toMSHRCtl_mshr_alloc_s3_bits_task_off,0,0);
        VL_OUT8(io_toMSHRCtl_mshr_alloc_s3_bits_task_alias,1,0);
        VL_OUT8(io_toMSHRCtl_mshr_alloc_s3_bits_task_opcode,2,0);
        VL_OUT8(io_toMSHRCtl_mshr_alloc_s3_bits_task_param,2,0);
        VL_OUT8(io_toMSHRCtl_mshr_alloc_s3_bits_task_size,0,0);
        VL_OUT8(io_toMSHRCtl_mshr_alloc_s3_bits_task_sourceId,7,0);
        VL_OUT8(io_toMSHRCtl_mshr_alloc_s3_bits_task_needProbeAckData,0,0);
        VL_OUT8(io_toMSHRCtl_mshr_alloc_s3_bits_task_aliasTask,0,0);
        VL_OUT8(io_toMSHRCtl_mshr_alloc_s3_bits_task_reqSource,3,0);
        VL_IN8(io_fromMSHRCtl_mshr_alloc_ptr,7,0);
        VL_IN8(io_bufResp_data_0,7,0);
        VL_IN8(io_bufResp_data_1,7,0);
        VL_IN8(io_releaseBufResp_s3_valid,0,0);
        VL_OUT8(io_toDS_req_s3_valid,0,0);
        VL_OUT8(io_toDS_req_s3_bits_way,0,0);
        VL_OUT8(io_toDS_req_s3_bits_set,1,0);
        VL_OUT8(io_toDS_req_s3_bits_wen,0,0);
        VL_IN8(io_toSourceC_ready,0,0);
        VL_OUT8(io_toSourceC_valid,0,0);
        VL_OUT8(io_toSourceC_bits_task_set,1,0);
        VL_OUT8(io_toSourceC_bits_task_tag,1,0);
        VL_OUT8(io_toSourceC_bits_task_off,0,0);
        VL_OUT8(io_toSourceC_bits_task_opcode,2,0);
        VL_OUT8(io_toSourceC_bits_task_param,2,0);
        VL_OUT8(io_toSourceC_bits_task_mshrId,7,0);
        VL_OUT8(io_toSourceC_bits_task_dirty,0,0);
        VL_OUT8(io_toSourceD_valid,0,0);
        VL_OUT8(io_toSourceD_bits_task_set,1,0);
        VL_OUT8(io_toSourceD_bits_task_tag,1,0);
    };
    struct {
        VL_OUT8(io_toSourceD_bits_task_opcode,2,0);
        VL_OUT8(io_toSourceD_bits_task_param,2,0);
        VL_OUT8(io_toSourceD_bits_task_sourceId,7,0);
        VL_OUT8(io_toSourceD_bits_task_mergeA,0,0);
        VL_OUT8(io_toSourceD_bits_task_aMergeTask_opcode,2,0);
        VL_OUT8(io_toSourceD_bits_task_aMergeTask_param,2,0);
        VL_OUT8(io_toSourceD_bits_task_aMergeTask_sourceId,7,0);
        VL_OUT8(io_metaWReq_valid,0,0);
        VL_OUT8(io_metaWReq_bits_set,1,0);
        VL_OUT8(io_metaWReq_bits_wayOH,1,0);
        VL_OUT8(io_metaWReq_bits_wmeta_dirty,0,0);
        VL_OUT8(io_metaWReq_bits_wmeta_state,1,0);
        VL_OUT8(io_metaWReq_bits_wmeta_clients,0,0);
        VL_OUT8(io_metaWReq_bits_wmeta_alias,1,0);
        VL_OUT8(io_metaWReq_bits_wmeta_accessed,0,0);
        VL_OUT8(io_tagWReq_valid,0,0);
        VL_OUT8(io_tagWReq_bits_set,1,0);
        VL_OUT8(io_tagWReq_bits_way,0,0);
        VL_OUT8(io_tagWReq_bits_wtag,1,0);
        VL_OUT8(io_releaseBufWrite_valid,0,0);
        VL_OUT8(io_releaseBufWrite_bits_id,7,0);
        VL_OUT8(io_nestedwb_set,1,0);
        VL_OUT8(io_nestedwb_tag,1,0);
        VL_OUT8(io_nestedwb_c_set_dirty,0,0);
        VL_IN8(io_l1Hint_ready,0,0);
        VL_OUT8(io_l1Hint_valid,0,0);
        VL_OUT8(io_l1Hint_bits_isKeyword,0,0);
        VL_IN8(io_taskInfo_s1_valid,0,0);
        VL_IN8(io_taskInfo_s1_bits_channel,2,0);
        VL_IN8(io_taskInfo_s1_bits_opcode,2,0);
        VL_IN8(io_taskInfo_s1_bits_sourceId,7,0);
        VL_IN8(io_taskInfo_s1_bits_mshrTask,0,0);
        VL_IN8(io_taskInfo_s1_bits_mergeA,0,0);
        VL_IN8(io_taskInfo_s1_bits_aMergeTask_opcode,2,0);
        VL_IN8(io_taskInfo_s1_bits_aMergeTask_sourceId,7,0);
        VL_OUT8(io_toMonitor_task_s3_valid,0,0);
        VL_OUT8(io_toMonitor_task_s3_bits_channel,2,0);
        VL_OUT8(io_toMonitor_task_s3_bits_mshrTask,0,0);
        VL_OUT8(io_toMonitor_dirResult_s3_hit,0,0);
        VL_OUT8(io_toMonitor_dirResult_s3_meta_state,1,0);
        VL_OUT8(io_toMonitor_dirResult_s3_meta_clients,0,0);
        CData/*0:0*/ __PVT__c_arb_io_in_1_valid;
        CData/*2:0*/ __PVT__c_arb_io_in_2_bits_task_param;
        CData/*0:0*/ __PVT__d_arb_io_in_1_valid;
        CData/*0:0*/ __PVT__helper_clean;
        CData/*0:0*/ __PVT__helper_dump;
        CData/*0:0*/ __PVT__helper_1_clean;
        CData/*0:0*/ __PVT__helper_1_dump;
        CData/*0:0*/ __PVT__helper_2_clean;
        CData/*0:0*/ __PVT__helper_2_dump;
        CData/*0:0*/ __PVT__helper_3_clean;
        CData/*0:0*/ __PVT__helper_3_dump;
        CData/*0:0*/ __PVT__helper_4_clean;
        CData/*0:0*/ __PVT__helper_4_dump;
        CData/*0:0*/ __PVT__helper_5_clean;
        CData/*0:0*/ __PVT__helper_5_dump;
        CData/*0:0*/ __PVT__helper_6_clean;
        CData/*0:0*/ __PVT__helper_6_dump;
        CData/*0:0*/ __PVT__helper_7_clean;
        CData/*0:0*/ __PVT__helper_7_dump;
        CData/*0:0*/ __PVT__helper_8_clean;
        CData/*0:0*/ __PVT__helper_8_dump;
        CData/*0:0*/ __PVT__helper_9_clean;
        CData/*0:0*/ __PVT__helper_9_dump;
    };
    struct {
        CData/*0:0*/ __PVT__helper_10_clean;
        CData/*0:0*/ __PVT__helper_10_dump;
        CData/*0:0*/ __PVT__helper_11_clean;
        CData/*0:0*/ __PVT__helper_11_dump;
        CData/*0:0*/ __PVT__helper_12_clean;
        CData/*0:0*/ __PVT__helper_12_dump;
        CData/*0:0*/ __PVT__helper_13_clean;
        CData/*0:0*/ __PVT__helper_13_dump;
        CData/*0:0*/ __PVT__helper_14_clean;
        CData/*0:0*/ __PVT__helper_14_dump;
        CData/*0:0*/ __PVT__helper_15_clean;
        CData/*0:0*/ __PVT__helper_15_dump;
        CData/*0:0*/ __PVT__helper_16_clean;
        CData/*0:0*/ __PVT__helper_16_dump;
        CData/*0:0*/ __PVT__helper_17_clean;
        CData/*0:0*/ __PVT__helper_17_dump;
        CData/*0:0*/ __PVT__helper_18_clean;
        CData/*0:0*/ __PVT__helper_18_dump;
        CData/*0:0*/ __PVT__helper_19_clean;
        CData/*0:0*/ __PVT__helper_19_dump;
        CData/*0:0*/ __PVT__helper_20_clean;
        CData/*0:0*/ __PVT__helper_20_dump;
        CData/*0:0*/ __PVT__helper_21_clean;
        CData/*0:0*/ __PVT__helper_21_dump;
        CData/*0:0*/ __PVT__resetFinish;
        CData/*1:0*/ __PVT__resetIdx;
        CData/*1:0*/ __PVT___resetIdx_T_1;
        CData/*0:0*/ __PVT___GEN_1;
        CData/*0:0*/ __PVT__task_s3_valid;
        CData/*2:0*/ __PVT__task_s3_bits_channel;
        CData/*1:0*/ __PVT__task_s3_bits_set;
        CData/*1:0*/ __PVT__task_s3_bits_tag;
        CData/*0:0*/ __PVT__task_s3_bits_off;
        CData/*1:0*/ __PVT__task_s3_bits_alias;
        CData/*2:0*/ __PVT__task_s3_bits_opcode;
        CData/*2:0*/ __PVT__task_s3_bits_param;
        CData/*7:0*/ __PVT__task_s3_bits_sourceId;
        CData/*0:0*/ __PVT__task_s3_bits_needProbeAckData;
        CData/*0:0*/ __PVT__task_s3_bits_mshrTask;
        CData/*7:0*/ __PVT__task_s3_bits_mshrId;
        CData/*0:0*/ __PVT__task_s3_bits_useProbeData;
        CData/*0:0*/ __PVT__task_s3_bits_dirty;
        CData/*0:0*/ __PVT__task_s3_bits_way;
        CData/*0:0*/ __PVT__task_s3_bits_meta_dirty;
        CData/*1:0*/ __PVT__task_s3_bits_meta_state;
        CData/*0:0*/ __PVT__task_s3_bits_meta_clients;
        CData/*1:0*/ __PVT__task_s3_bits_meta_alias;
        CData/*0:0*/ __PVT__task_s3_bits_meta_accessed;
        CData/*0:0*/ __PVT__task_s3_bits_metaWen;
        CData/*0:0*/ __PVT__task_s3_bits_tagWen;
        CData/*0:0*/ __PVT__task_s3_bits_dsWen;
        CData/*0:0*/ __PVT__task_s3_bits_replTask;
        CData/*3:0*/ __PVT__task_s3_bits_reqSource;
        CData/*0:0*/ __PVT__task_s3_bits_mergeA;
        CData/*2:0*/ __PVT__task_s3_bits_aMergeTask_opcode;
        CData/*2:0*/ __PVT__task_s3_bits_aMergeTask_param;
        CData/*7:0*/ __PVT__task_s3_bits_aMergeTask_sourceId;
        CData/*0:0*/ __PVT__task_s3_bits_aMergeTask_meta_dirty;
        CData/*1:0*/ __PVT__task_s3_bits_aMergeTask_meta_state;
        CData/*0:0*/ __PVT__task_s3_bits_aMergeTask_meta_clients;
        CData/*1:0*/ __PVT__task_s3_bits_aMergeTask_meta_alias;
        CData/*0:0*/ __PVT__task_s3_bits_aMergeTask_meta_accessed;
        CData/*0:0*/ __PVT___req_acquire_s3_T_2;
        CData/*0:0*/ __PVT__req_prefetch_s3;
    };
    struct {
        CData/*0:0*/ __PVT__req_get_s3;
        CData/*0:0*/ __PVT__mshr_release_s3;
        CData/*0:0*/ __PVT__req_needT_s3;
        CData/*0:0*/ __PVT__retry;
        CData/*0:0*/ __PVT__need_repl;
        CData/*0:0*/ __PVT___io_toMSHRCtl_mshr_alloc_s3_valid_T_1;
        CData/*0:0*/ __PVT__sink_resp_s3_valid;
        CData/*2:0*/ __PVT___GEN_53;
        CData/*1:0*/ __PVT___sink_resp_s3_bits_param_T_4;
        CData/*2:0*/ __PVT___GEN_54;
        CData/*2:0*/ __PVT___GEN_55;
        CData/*0:0*/ __PVT___wen_c_T_4;
        CData/*0:0*/ __PVT__wen_c;
        CData/*0:0*/ __PVT__need_write_releaseBuf;
        CData/*0:0*/ __PVT__metaW_valid_s3_a;
        CData/*0:0*/ __PVT__metaW_valid_s3_c;
        CData/*0:0*/ __PVT___io_metaWReq_valid_T_1;
        CData/*0:0*/ __PVT___isC_s3_T;
        CData/*0:0*/ __PVT___isC_s3_T_6;
        CData/*0:0*/ __PVT___isD_s3_T_1;
        CData/*0:0*/ __PVT___isD_s3_T_12;
        CData/*0:0*/ __PVT__chnl_fire_s3;
        CData/*0:0*/ __PVT___req_drop_s3_T_2;
        CData/*0:0*/ __PVT__req_drop_s3;
        CData/*0:0*/ __PVT__task_s4_valid;
        CData/*2:0*/ __PVT__task_s4_bits_channel;
        CData/*1:0*/ __PVT__task_s4_bits_set;
        CData/*1:0*/ __PVT__task_s4_bits_tag;
        CData/*0:0*/ __PVT__task_s4_bits_off;
        CData/*2:0*/ __PVT__task_s4_bits_opcode;
        CData/*2:0*/ __PVT__task_s4_bits_param;
        CData/*7:0*/ __PVT__task_s4_bits_sourceId;
        CData/*0:0*/ __PVT__task_s4_bits_mshrTask;
        CData/*7:0*/ __PVT__task_s4_bits_mshrId;
        CData/*0:0*/ __PVT__task_s4_bits_dirty;
        CData/*0:0*/ __PVT__task_s4_bits_mergeA;
        CData/*2:0*/ __PVT__task_s4_bits_aMergeTask_opcode;
        CData/*2:0*/ __PVT__task_s4_bits_aMergeTask_param;
        CData/*7:0*/ __PVT__task_s4_bits_aMergeTask_sourceId;
        CData/*0:0*/ __PVT__need_write_releaseBuf_s4;
        CData/*0:0*/ __PVT__isC_s4;
        CData/*0:0*/ __PVT__isD_s4;
        CData/*0:0*/ __PVT___task_s4_valid_T_1;
        CData/*0:0*/ __PVT__c_d_valid_s4_REG;
        CData/*0:0*/ __PVT__c_d_valid_s4;
        CData/*0:0*/ __PVT___chnl_fire_s4_T;
        CData/*0:0*/ __PVT___chnl_fire_s4_T_1;
        CData/*0:0*/ __PVT__chnl_fire_s4;
        CData/*0:0*/ __PVT__req_drop_s4;
        CData/*0:0*/ __PVT__task_s5_valid;
        CData/*2:0*/ __PVT__task_s5_bits_channel;
        CData/*1:0*/ __PVT__task_s5_bits_set;
        CData/*1:0*/ __PVT__task_s5_bits_tag;
        CData/*0:0*/ __PVT__task_s5_bits_off;
        CData/*2:0*/ __PVT__task_s5_bits_opcode;
        CData/*2:0*/ __PVT__task_s5_bits_param;
        CData/*7:0*/ __PVT__task_s5_bits_sourceId;
        CData/*0:0*/ __PVT__task_s5_bits_mshrTask;
        CData/*7:0*/ __PVT__task_s5_bits_mshrId;
        CData/*0:0*/ __PVT__task_s5_bits_dirty;
        CData/*0:0*/ __PVT__task_s5_bits_mergeA;
        CData/*2:0*/ __PVT__task_s5_bits_aMergeTask_opcode;
        CData/*2:0*/ __PVT__task_s5_bits_aMergeTask_param;
        CData/*7:0*/ __PVT__task_s5_bits_aMergeTask_sourceId;
    };
    struct {
        CData/*0:0*/ __PVT__need_write_releaseBuf_s5;
        CData/*0:0*/ __PVT__isC_s5;
        CData/*0:0*/ __PVT__isD_s5;
        CData/*0:0*/ __PVT__pendingC_s4;
        CData/*0:0*/ __PVT__pendingD_s4;
        CData/*0:0*/ __PVT___task_s5_valid_T_1;
        CData/*0:0*/ __PVT__c_d_valid_s5_REG;
        CData/*0:0*/ __PVT__c_d_valid_s5_REG_2;
        CData/*0:0*/ __PVT__c_d_valid_s5;
        CData/*0:0*/ __PVT__c_d_valid_s5_REG_1;
        CData/*0:0*/ __PVT___T_46;
        CData/*0:0*/ __PVT___T_70;
        CData/*0:0*/ __PVT___T_103;
        CData/*2:0*/ __PVT__sourceC_pipe_len;
        CData/*2:0*/ __PVT__sourceD_pipe_len;
        CData/*0:0*/ __PVT___T_128;
        CData/*0:0*/ __VdfgRegularize_hb02e9cef_0_7;
        CData/*0:0*/ __PVT__customL1Hint__DOT__hintQueue_io_enq_ready;
        CData/*0:0*/ __PVT__customL1Hint__DOT__hintQueue_io_deq_valid;
        CData/*7:0*/ __PVT__customL1Hint__DOT__hint_s1Queue_io_enq_bits_source;
        CData/*2:0*/ __PVT__customL1Hint__DOT__hint_s1Queue_io_enq_bits_opcode;
        CData/*0:0*/ __PVT__customL1Hint__DOT__hint_s1Queue_io_deq_ready;
        CData/*0:0*/ __PVT__customL1Hint__DOT__chn_Grant_s3;
        CData/*0:0*/ __PVT__customL1Hint__DOT__enqValid_s3;
        CData/*0:0*/ __PVT__customL1Hint__DOT__hintQueue__DOT__ram_source_MPORT_en;
        CData/*1:0*/ __PVT__customL1Hint__DOT__hintQueue__DOT__enq_ptr_value;
        CData/*1:0*/ __PVT__customL1Hint__DOT__hintQueue__DOT__deq_ptr_value;
        CData/*0:0*/ __PVT__customL1Hint__DOT__hintQueue__DOT__maybe_full;
        CData/*0:0*/ __PVT__customL1Hint__DOT__hintQueue__DOT__do_deq;
        CData/*1:0*/ __PVT__customL1Hint__DOT__hintQueue__DOT___value_T_1;
        CData/*1:0*/ __PVT__customL1Hint__DOT__hintQueue__DOT___value_T_3;
        CData/*0:0*/ __PVT__customL1Hint__DOT__hint_s1Queue__DOT__ram_source_MPORT_en;
        CData/*1:0*/ __PVT__customL1Hint__DOT__hint_s1Queue__DOT__enq_ptr_value;
        CData/*1:0*/ __PVT__customL1Hint__DOT__hint_s1Queue__DOT__deq_ptr_value;
        CData/*0:0*/ __PVT__customL1Hint__DOT__hint_s1Queue__DOT__maybe_full;
        CData/*0:0*/ __PVT__customL1Hint__DOT__hint_s1Queue__DOT__ptr_match;
        CData/*0:0*/ __PVT__customL1Hint__DOT__hint_s1Queue__DOT__empty;
        CData/*0:0*/ __PVT__customL1Hint__DOT__hint_s1Queue__DOT___do_enq_T;
        CData/*1:0*/ __PVT__customL1Hint__DOT__hint_s1Queue__DOT___value_T_1;
        CData/*1:0*/ __PVT__customL1Hint__DOT__hint_s1Queue__DOT___value_T_3;
        CData/*0:0*/ __PVT__customL1Hint__DOT__hint_s1Queue__DOT__do_deq;
        CData/*0:0*/ c_arb__DOT____VdfgRegularize_hbadb2dd2_0_0;
        CData/*0:0*/ d_arb__DOT____VdfgRegularize_hbadb2dd2_0_0;
        VL_IN16(io_refillBufResp_s3_bits_data,15,0);
        VL_IN16(io_releaseBufResp_s3_bits_data,15,0);
        VL_IN16(io_toDS_rdata_s5_data,15,0);
        VL_OUT16(io_toDS_wdata_s3_data,15,0);
        VL_OUT16(io_toSourceC_bits_data_data,15,0);
        VL_OUT16(io_toSourceD_bits_data_data,15,0);
        VL_OUT16(io_releaseBufWrite_bits_data_data,15,0);
        VL_OUT16(io_nestedwbData_data,15,0);
        SData/*15:0*/ __PVT__c_arb_io_in_0_bits_data_data;
        SData/*15:0*/ __PVT__c_arb_io_in_2_bits_data_data;
        SData/*15:0*/ __PVT__data_s4;
        SData/*15:0*/ __PVT__data_s5;
        VL_OUT(io_l1Hint_bits_sourceId,31,0);
        QData/*63:0*/ __PVT__helper_timer;
        QData/*63:0*/ __PVT__helper_1_timer;
        QData/*63:0*/ __PVT__helper_2_timer;
        QData/*63:0*/ __PVT__helper_3_timer;
        QData/*63:0*/ __PVT__helper_4_timer;
        QData/*63:0*/ __PVT__helper_5_timer;
        QData/*63:0*/ __PVT__helper_6_timer;
        QData/*63:0*/ __PVT__helper_7_timer;
    };
    struct {
        QData/*63:0*/ __PVT__helper_8_timer;
        QData/*63:0*/ __PVT__helper_9_timer;
        QData/*63:0*/ __PVT__helper_10_timer;
        QData/*63:0*/ __PVT__helper_11_timer;
        QData/*63:0*/ __PVT__helper_12_timer;
        QData/*63:0*/ __PVT__helper_13_timer;
        QData/*63:0*/ __PVT__helper_14_timer;
        QData/*63:0*/ __PVT__helper_15_timer;
        QData/*63:0*/ __PVT__helper_16_timer;
        QData/*63:0*/ __PVT__helper_17_timer;
        QData/*63:0*/ __PVT__helper_18_timer;
        QData/*63:0*/ __PVT__helper_19_timer;
        QData/*63:0*/ __PVT__helper_20_timer;
        QData/*63:0*/ __PVT__helper_21_timer;
        QData/*63:0*/ __PVT__counter;
        QData/*63:0*/ __PVT__next_counter;
        QData/*63:0*/ __PVT__counter_1;
        QData/*63:0*/ __PVT__next_counter_1;
        QData/*63:0*/ __PVT__counter_2;
        QData/*63:0*/ __PVT__next_counter_2;
        QData/*63:0*/ __PVT__counter_3;
        QData/*63:0*/ __PVT__next_counter_3;
        QData/*63:0*/ __PVT__counter_4;
        QData/*63:0*/ __PVT__next_counter_4;
        QData/*63:0*/ __PVT__counter_5;
        QData/*63:0*/ __PVT__next_counter_5;
        QData/*63:0*/ __PVT__counter_6;
        QData/*63:0*/ __PVT__next_counter_6;
        QData/*63:0*/ __PVT__counter_7;
        QData/*63:0*/ __PVT__next_counter_7;
        QData/*63:0*/ __PVT__counter_8;
        QData/*63:0*/ __PVT__next_counter_8;
        QData/*63:0*/ __PVT__counter_9;
        QData/*63:0*/ __PVT__next_counter_9;
        QData/*63:0*/ __PVT__counter_10;
        QData/*63:0*/ __PVT__next_counter_10;
        QData/*63:0*/ __PVT__counter_11;
        QData/*63:0*/ __PVT__next_counter_11;
        QData/*63:0*/ __PVT__counter_12;
        QData/*63:0*/ __PVT__next_counter_12;
        QData/*63:0*/ __PVT__counter_13;
        QData/*63:0*/ __PVT__next_counter_13;
        QData/*63:0*/ __PVT__counter_14;
        QData/*63:0*/ __PVT__next_counter_14;
        QData/*63:0*/ __PVT__counter_15;
        QData/*63:0*/ __PVT__next_counter_15;
        QData/*63:0*/ __PVT__counter_16;
        QData/*63:0*/ __PVT___counter_T_17;
        QData/*63:0*/ __PVT__counter_17;
        QData/*63:0*/ __PVT___counter_T_19;
        QData/*63:0*/ __PVT__counter_18;
        QData/*63:0*/ __PVT___counter_T_21;
        QData/*63:0*/ __PVT__counter_19;
        QData/*63:0*/ __PVT___counter_T_23;
        QData/*63:0*/ __PVT__counter_20;
        QData/*63:0*/ __PVT___counter_T_25;
        QData/*63:0*/ __PVT__counter_21;
        QData/*63:0*/ __PVT___counter_T_27;
        QData/*63:0*/ __PVT__counter_22;
        QData/*63:0*/ __PVT___counter_T_29;
        QData/*63:0*/ __PVT__counter_23;
        QData/*63:0*/ __PVT___counter_T_31;
        QData/*63:0*/ __PVT__counter_24;
        QData/*63:0*/ __PVT___counter_T_33;
    };
    struct {
        QData/*63:0*/ __PVT__counter_25;
        QData/*63:0*/ __PVT___counter_T_35;
        QData/*63:0*/ __PVT__counter_26;
        QData/*63:0*/ __PVT___counter_T_37;
        QData/*63:0*/ __PVT__counter_27;
        QData/*63:0*/ __PVT___counter_T_39;
        QData/*63:0*/ __PVT__counter_28;
        VlUnpacked<CData/*7:0*/, 4> __PVT__customL1Hint__DOT__hintQueue__DOT__ram_source;
        VlUnpacked<CData/*2:0*/, 4> __PVT__customL1Hint__DOT__hintQueue__DOT__ram_opcode;
        VlUnpacked<CData/*7:0*/, 4> __PVT__customL1Hint__DOT__hint_s1Queue__DOT__ram_source;
        VlUnpacked<CData/*2:0*/, 4> __PVT__customL1Hint__DOT__hint_s1Queue__DOT__ram_opcode;
        VlUnpacked<CData/*0:0*/, 4> __PVT__customL1Hint__DOT__hint_s1Queue__DOT__ram_isKeyword;
    };

    // INTERNAL VARIABLES
    VVerifyTop__Syms* const vlSymsp;

    // CONSTRUCTORS
    VVerifyTop_MainPipe_2(VVerifyTop__Syms* symsp, const char* v__name);
    ~VVerifyTop_MainPipe_2();
    VL_UNCOPYABLE(VVerifyTop_MainPipe_2);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
