// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design implementation internals
// See VVerifyTop.h for the primary calling header

#include "VVerifyTop__pch.h"
#include "VVerifyTop_RequestBuffer_2.h"

VL_ATTR_COLD void VVerifyTop_RequestBuffer_2___ctor_var_reset(VVerifyTop_RequestBuffer_2* vlSelf) {
    (void)vlSelf;  // Prevent unused variable warning
    VVerifyTop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+            VVerifyTop_RequestBuffer_2___ctor_var_reset\n"); );
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    vlSelf->clock = VL_RAND_RESET_I(1);
    vlSelf->reset = VL_RAND_RESET_I(1);
    vlSelf->io_in_ready = VL_RAND_RESET_I(1);
    vlSelf->io_in_valid = VL_RAND_RESET_I(1);
    vlSelf->io_in_bits_set = VL_RAND_RESET_I(2);
    vlSelf->io_in_bits_tag = VL_RAND_RESET_I(2);
    vlSelf->io_in_bits_off = VL_RAND_RESET_I(1);
    vlSelf->io_in_bits_opcode = VL_RAND_RESET_I(3);
    vlSelf->io_in_bits_param = VL_RAND_RESET_I(3);
    vlSelf->io_in_bits_size = VL_RAND_RESET_I(1);
    vlSelf->io_in_bits_sourceId = VL_RAND_RESET_I(8);
    vlSelf->io_out_ready = VL_RAND_RESET_I(1);
    vlSelf->io_out_valid = VL_RAND_RESET_I(1);
    vlSelf->io_out_bits_channel = VL_RAND_RESET_I(3);
    vlSelf->io_out_bits_txChannel = VL_RAND_RESET_I(3);
    vlSelf->io_out_bits_set = VL_RAND_RESET_I(2);
    vlSelf->io_out_bits_tag = VL_RAND_RESET_I(2);
    vlSelf->io_out_bits_off = VL_RAND_RESET_I(1);
    vlSelf->io_out_bits_alias = VL_RAND_RESET_I(2);
    vlSelf->io_out_bits_opcode = VL_RAND_RESET_I(3);
    vlSelf->io_out_bits_param = VL_RAND_RESET_I(3);
    vlSelf->io_out_bits_size = VL_RAND_RESET_I(1);
    vlSelf->io_out_bits_sourceId = VL_RAND_RESET_I(8);
    vlSelf->io_out_bits_bufIdx = VL_RAND_RESET_I(2);
    vlSelf->io_out_bits_needProbeAckData = VL_RAND_RESET_I(1);
    vlSelf->io_out_bits_mshrTask = VL_RAND_RESET_I(1);
    vlSelf->io_out_bits_mshrId = VL_RAND_RESET_I(8);
    vlSelf->io_out_bits_aliasTask = VL_RAND_RESET_I(1);
    vlSelf->io_out_bits_useProbeData = VL_RAND_RESET_I(1);
    vlSelf->io_out_bits_mshrRetry = VL_RAND_RESET_I(1);
    vlSelf->io_out_bits_dirty = VL_RAND_RESET_I(1);
    vlSelf->io_out_bits_way = VL_RAND_RESET_I(1);
    vlSelf->io_out_bits_meta_dirty = VL_RAND_RESET_I(1);
    vlSelf->io_out_bits_meta_state = VL_RAND_RESET_I(2);
    vlSelf->io_out_bits_meta_clients = VL_RAND_RESET_I(1);
    vlSelf->io_out_bits_meta_alias = VL_RAND_RESET_I(2);
    vlSelf->io_out_bits_meta_accessed = VL_RAND_RESET_I(1);
    vlSelf->io_out_bits_metaWen = VL_RAND_RESET_I(1);
    vlSelf->io_out_bits_tagWen = VL_RAND_RESET_I(1);
    vlSelf->io_out_bits_dsWen = VL_RAND_RESET_I(1);
    vlSelf->io_out_bits_replTask = VL_RAND_RESET_I(1);
    vlSelf->io_out_bits_reqSource = VL_RAND_RESET_I(4);
    vlSelf->io_out_bits_mergeA = VL_RAND_RESET_I(1);
    vlSelf->io_out_bits_aMergeTask_off = VL_RAND_RESET_I(1);
    vlSelf->io_out_bits_aMergeTask_alias = VL_RAND_RESET_I(2);
    vlSelf->io_out_bits_aMergeTask_opcode = VL_RAND_RESET_I(3);
    vlSelf->io_out_bits_aMergeTask_param = VL_RAND_RESET_I(3);
    vlSelf->io_out_bits_aMergeTask_sourceId = VL_RAND_RESET_I(8);
    vlSelf->io_out_bits_aMergeTask_meta_dirty = VL_RAND_RESET_I(1);
    vlSelf->io_out_bits_aMergeTask_meta_state = VL_RAND_RESET_I(2);
    vlSelf->io_out_bits_aMergeTask_meta_clients = VL_RAND_RESET_I(1);
    vlSelf->io_out_bits_aMergeTask_meta_alias = VL_RAND_RESET_I(2);
    vlSelf->io_out_bits_aMergeTask_meta_accessed = VL_RAND_RESET_I(1);
    vlSelf->io_out_bits_snpHitRelease = VL_RAND_RESET_I(1);
    vlSelf->io_out_bits_snpHitReleaseWithData = VL_RAND_RESET_I(1);
    vlSelf->io_out_bits_snpHitReleaseIdx = VL_RAND_RESET_I(8);
    vlSelf->io_mshrInfo_0_valid = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_0_bits_set = VL_RAND_RESET_I(2);
    vlSelf->io_mshrInfo_0_bits_reqTag = VL_RAND_RESET_I(2);
    vlSelf->io_mshrInfo_0_bits_willFree = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_0_bits_needRelease = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_0_bits_metaTag = VL_RAND_RESET_I(2);
    vlSelf->io_mshrInfo_0_bits_dirHit = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_0_bits_isAcqOrPrefetch = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_0_bits_isPrefetch = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_0_bits_param = VL_RAND_RESET_I(3);
    vlSelf->io_mshrInfo_0_bits_mergeA = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_0_bits_s_refill = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_1_valid = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_1_bits_set = VL_RAND_RESET_I(2);
    vlSelf->io_mshrInfo_1_bits_reqTag = VL_RAND_RESET_I(2);
    vlSelf->io_mshrInfo_1_bits_willFree = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_1_bits_needRelease = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_1_bits_metaTag = VL_RAND_RESET_I(2);
    vlSelf->io_mshrInfo_1_bits_dirHit = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_1_bits_isAcqOrPrefetch = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_1_bits_isPrefetch = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_1_bits_param = VL_RAND_RESET_I(3);
    vlSelf->io_mshrInfo_1_bits_mergeA = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_1_bits_s_refill = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_2_valid = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_2_bits_set = VL_RAND_RESET_I(2);
    vlSelf->io_mshrInfo_2_bits_reqTag = VL_RAND_RESET_I(2);
    vlSelf->io_mshrInfo_2_bits_willFree = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_2_bits_needRelease = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_2_bits_metaTag = VL_RAND_RESET_I(2);
    vlSelf->io_mshrInfo_2_bits_dirHit = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_2_bits_isAcqOrPrefetch = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_2_bits_isPrefetch = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_2_bits_param = VL_RAND_RESET_I(3);
    vlSelf->io_mshrInfo_2_bits_mergeA = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_2_bits_s_refill = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_3_valid = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_3_bits_set = VL_RAND_RESET_I(2);
    vlSelf->io_mshrInfo_3_bits_reqTag = VL_RAND_RESET_I(2);
    vlSelf->io_mshrInfo_3_bits_willFree = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_3_bits_needRelease = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_3_bits_metaTag = VL_RAND_RESET_I(2);
    vlSelf->io_mshrInfo_3_bits_dirHit = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_3_bits_isAcqOrPrefetch = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_3_bits_isPrefetch = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_3_bits_param = VL_RAND_RESET_I(3);
    vlSelf->io_mshrInfo_3_bits_mergeA = VL_RAND_RESET_I(1);
    vlSelf->io_mshrInfo_3_bits_s_refill = VL_RAND_RESET_I(1);
    vlSelf->io_aMergeTask_valid = VL_RAND_RESET_I(1);
    vlSelf->io_aMergeTask_bits_id = VL_RAND_RESET_I(8);
    vlSelf->io_aMergeTask_bits_task_off = VL_RAND_RESET_I(1);
    vlSelf->io_aMergeTask_bits_task_opcode = VL_RAND_RESET_I(3);
    vlSelf->io_aMergeTask_bits_task_param = VL_RAND_RESET_I(3);
    vlSelf->io_aMergeTask_bits_task_sourceId = VL_RAND_RESET_I(8);
    vlSelf->io_mainPipeBlock_0 = VL_RAND_RESET_I(1);
    vlSelf->io_mainPipeBlock_1 = VL_RAND_RESET_I(1);
    vlSelf->io_ATag = VL_RAND_RESET_I(2);
    vlSelf->io_ASet = VL_RAND_RESET_I(2);
    vlSelf->io_s1Entrance_valid = VL_RAND_RESET_I(1);
    vlSelf->io_s1Entrance_bits_set = VL_RAND_RESET_I(2);
    vlSelf->io_hasLatePF = VL_RAND_RESET_I(1);
    vlSelf->io_hasMergeA = VL_RAND_RESET_I(1);
    vlSelf->__PVT__issueArb_io_in_0_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__issueArb_io_in_1_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__issueArb_io_in_2_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__issueArb_io_in_3_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__issueArb_io_chosen = VL_RAND_RESET_I(2);
    vlSelf->__PVT__helper_timer = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__helper_clean = VL_RAND_RESET_I(1);
    vlSelf->__PVT__helper_dump = VL_RAND_RESET_I(1);
    vlSelf->__PVT__helper_1_timer = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__helper_1_clean = VL_RAND_RESET_I(1);
    vlSelf->__PVT__helper_1_dump = VL_RAND_RESET_I(1);
    vlSelf->__PVT__helper_2_timer = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__helper_2_clean = VL_RAND_RESET_I(1);
    vlSelf->__PVT__helper_2_dump = VL_RAND_RESET_I(1);
    vlSelf->__PVT__helper_3_timer = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__helper_3_clean = VL_RAND_RESET_I(1);
    vlSelf->__PVT__helper_3_dump = VL_RAND_RESET_I(1);
    vlSelf->__PVT__helper_4_timer = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__helper_4_clean = VL_RAND_RESET_I(1);
    vlSelf->__PVT__helper_4_dump = VL_RAND_RESET_I(1);
    vlSelf->__PVT__helper_5_timer = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__helper_5_clean = VL_RAND_RESET_I(1);
    vlSelf->__PVT__helper_5_dump = VL_RAND_RESET_I(1);
    vlSelf->__PVT__helper_6_timer = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__helper_6_clean = VL_RAND_RESET_I(1);
    vlSelf->__PVT__helper_6_dump = VL_RAND_RESET_I(1);
    vlSelf->__PVT__helper_7_timer = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__helper_7_clean = VL_RAND_RESET_I(1);
    vlSelf->__PVT__helper_7_dump = VL_RAND_RESET_I(1);
    vlSelf->__PVT__helper_8_timer = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__helper_8_clean = VL_RAND_RESET_I(1);
    vlSelf->__PVT__helper_8_dump = VL_RAND_RESET_I(1);
    vlSelf->__PVT__helper_9_timer = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__helper_9_clean = VL_RAND_RESET_I(1);
    vlSelf->__PVT__helper_9_dump = VL_RAND_RESET_I(1);
    vlSelf->__PVT__helper_10_timer = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__helper_10_clean = VL_RAND_RESET_I(1);
    vlSelf->__PVT__helper_10_dump = VL_RAND_RESET_I(1);
    vlSelf->__PVT__helper_11_timer = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__helper_11_clean = VL_RAND_RESET_I(1);
    vlSelf->__PVT__helper_11_dump = VL_RAND_RESET_I(1);
    vlSelf->__PVT__helper_12_timer = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__helper_12_clean = VL_RAND_RESET_I(1);
    vlSelf->__PVT__helper_12_dump = VL_RAND_RESET_I(1);
    vlSelf->__PVT__helper_13_timer = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__helper_13_clean = VL_RAND_RESET_I(1);
    vlSelf->__PVT__helper_13_dump = VL_RAND_RESET_I(1);
    vlSelf->__PVT__helper_14_timer = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__helper_14_clean = VL_RAND_RESET_I(1);
    vlSelf->__PVT__helper_14_dump = VL_RAND_RESET_I(1);
    vlSelf->__PVT__helper_15_timer = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__helper_15_clean = VL_RAND_RESET_I(1);
    vlSelf->__PVT__helper_15_dump = VL_RAND_RESET_I(1);
    vlSelf->__PVT__helper_16_timer = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__helper_16_clean = VL_RAND_RESET_I(1);
    vlSelf->__PVT__helper_16_dump = VL_RAND_RESET_I(1);
    vlSelf->__PVT__helper_17_timer = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__helper_17_clean = VL_RAND_RESET_I(1);
    vlSelf->__PVT__helper_17_dump = VL_RAND_RESET_I(1);
    vlSelf->__PVT__helper_18_timer = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__helper_18_clean = VL_RAND_RESET_I(1);
    vlSelf->__PVT__helper_18_dump = VL_RAND_RESET_I(1);
    vlSelf->__PVT__helper_19_timer = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__helper_19_clean = VL_RAND_RESET_I(1);
    vlSelf->__PVT__helper_19_dump = VL_RAND_RESET_I(1);
    vlSelf->__PVT__helper_20_timer = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__helper_20_clean = VL_RAND_RESET_I(1);
    vlSelf->__PVT__helper_20_dump = VL_RAND_RESET_I(1);
    vlSelf->__PVT__helper_21_timer = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__helper_21_clean = VL_RAND_RESET_I(1);
    vlSelf->__PVT__helper_21_dump = VL_RAND_RESET_I(1);
    vlSelf->__PVT__helper_22_timer = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__helper_22_clean = VL_RAND_RESET_I(1);
    vlSelf->__PVT__helper_22_dump = VL_RAND_RESET_I(1);
    vlSelf->__PVT__helper_23_timer = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__helper_23_clean = VL_RAND_RESET_I(1);
    vlSelf->__PVT__helper_23_dump = VL_RAND_RESET_I(1);
    vlSelf->__PVT__buffer_0_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__buffer_0_rdy = VL_RAND_RESET_I(1);
    vlSelf->__PVT__buffer_0_task_channel = VL_RAND_RESET_I(3);
    vlSelf->__PVT__buffer_0_task_set = VL_RAND_RESET_I(2);
    vlSelf->__PVT__buffer_0_task_tag = VL_RAND_RESET_I(2);
    vlSelf->__PVT__buffer_0_task_off = VL_RAND_RESET_I(1);
    vlSelf->__PVT__buffer_0_task_opcode = VL_RAND_RESET_I(3);
    vlSelf->__PVT__buffer_0_task_param = VL_RAND_RESET_I(3);
    vlSelf->__PVT__buffer_0_task_size = VL_RAND_RESET_I(1);
    vlSelf->__PVT__buffer_0_task_sourceId = VL_RAND_RESET_I(8);
    vlSelf->__PVT__buffer_0_waitMP = VL_RAND_RESET_I(4);
    vlSelf->__PVT__buffer_0_waitMS = VL_RAND_RESET_I(4);
    vlSelf->__PVT__buffer_1_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__buffer_1_rdy = VL_RAND_RESET_I(1);
    vlSelf->__PVT__buffer_1_task_channel = VL_RAND_RESET_I(3);
    vlSelf->__PVT__buffer_1_task_set = VL_RAND_RESET_I(2);
    vlSelf->__PVT__buffer_1_task_tag = VL_RAND_RESET_I(2);
    vlSelf->__PVT__buffer_1_task_off = VL_RAND_RESET_I(1);
    vlSelf->__PVT__buffer_1_task_opcode = VL_RAND_RESET_I(3);
    vlSelf->__PVT__buffer_1_task_param = VL_RAND_RESET_I(3);
    vlSelf->__PVT__buffer_1_task_size = VL_RAND_RESET_I(1);
    vlSelf->__PVT__buffer_1_task_sourceId = VL_RAND_RESET_I(8);
    vlSelf->__PVT__buffer_1_waitMP = VL_RAND_RESET_I(4);
    vlSelf->__PVT__buffer_1_waitMS = VL_RAND_RESET_I(4);
    vlSelf->__PVT__buffer_2_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__buffer_2_rdy = VL_RAND_RESET_I(1);
    vlSelf->__PVT__buffer_2_task_channel = VL_RAND_RESET_I(3);
    vlSelf->__PVT__buffer_2_task_set = VL_RAND_RESET_I(2);
    vlSelf->__PVT__buffer_2_task_tag = VL_RAND_RESET_I(2);
    vlSelf->__PVT__buffer_2_task_off = VL_RAND_RESET_I(1);
    vlSelf->__PVT__buffer_2_task_opcode = VL_RAND_RESET_I(3);
    vlSelf->__PVT__buffer_2_task_param = VL_RAND_RESET_I(3);
    vlSelf->__PVT__buffer_2_task_size = VL_RAND_RESET_I(1);
    vlSelf->__PVT__buffer_2_task_sourceId = VL_RAND_RESET_I(8);
    vlSelf->__PVT__buffer_2_waitMP = VL_RAND_RESET_I(4);
    vlSelf->__PVT__buffer_2_waitMS = VL_RAND_RESET_I(4);
    vlSelf->__PVT__buffer_3_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__buffer_3_rdy = VL_RAND_RESET_I(1);
    vlSelf->__PVT__buffer_3_task_channel = VL_RAND_RESET_I(3);
    vlSelf->__PVT__buffer_3_task_set = VL_RAND_RESET_I(2);
    vlSelf->__PVT__buffer_3_task_tag = VL_RAND_RESET_I(2);
    vlSelf->__PVT__buffer_3_task_off = VL_RAND_RESET_I(1);
    vlSelf->__PVT__buffer_3_task_opcode = VL_RAND_RESET_I(3);
    vlSelf->__PVT__buffer_3_task_param = VL_RAND_RESET_I(3);
    vlSelf->__PVT__buffer_3_task_size = VL_RAND_RESET_I(1);
    vlSelf->__PVT__buffer_3_task_sourceId = VL_RAND_RESET_I(8);
    vlSelf->__PVT__buffer_3_waitMP = VL_RAND_RESET_I(4);
    vlSelf->__PVT__buffer_3_waitMS = VL_RAND_RESET_I(4);
    vlSelf->__PVT__full = VL_RAND_RESET_I(1);
    vlSelf->__PVT___mergeAMask_T_1 = VL_RAND_RESET_I(4);
    vlSelf->__PVT___mergeAMask_T_3 = VL_RAND_RESET_I(1);
    vlSelf->__PVT___mergeAMask_T_6 = VL_RAND_RESET_I(1);
    vlSelf->__PVT___mergeAMask_T_16 = VL_RAND_RESET_I(1);
    vlSelf->__PVT___mergeAMask_T_28 = VL_RAND_RESET_I(1);
    vlSelf->__PVT___mergeAMask_T_31 = VL_RAND_RESET_I(1);
    vlSelf->__PVT___mergeAMask_T_53 = VL_RAND_RESET_I(1);
    vlSelf->__PVT___mergeAMask_T_56 = VL_RAND_RESET_I(1);
    vlSelf->__PVT___mergeAMask_T_78 = VL_RAND_RESET_I(1);
    vlSelf->__PVT___mergeAMask_T_81 = VL_RAND_RESET_I(1);
    vlSelf->__PVT__mergeA = VL_RAND_RESET_I(1);
    vlSelf->__PVT___canFlow_T_10 = VL_RAND_RESET_I(1);
    vlSelf->__PVT___canFlow_T_28 = VL_RAND_RESET_I(1);
    vlSelf->__PVT___canFlow_T_37 = VL_RAND_RESET_I(1);
    vlSelf->__PVT___canFlow_T_38 = VL_RAND_RESET_I(4);
    vlSelf->__PVT___canFlow_T_46 = VL_RAND_RESET_I(1);
    vlSelf->__PVT__canFlow = VL_RAND_RESET_I(1);
    vlSelf->__PVT__io_hasLatePF_REG_set = VL_RAND_RESET_I(2);
    vlSelf->__PVT__io_hasLatePF_REG_tag = VL_RAND_RESET_I(2);
    vlSelf->__PVT__io_hasMergeA_REG_set = VL_RAND_RESET_I(2);
    vlSelf->__PVT__io_hasMergeA_REG_tag = VL_RAND_RESET_I(2);
    vlSelf->__PVT__dup = VL_RAND_RESET_I(1);
    vlSelf->__PVT__insertIdx = VL_RAND_RESET_I(2);
    vlSelf->__PVT__alloc = VL_RAND_RESET_I(1);
    vlSelf->__PVT__s1Block = VL_RAND_RESET_I(1);
    vlSelf->__PVT___buffer_waitMP_T = VL_RAND_RESET_I(4);
    vlSelf->__PVT___GEN_192 = VL_RAND_RESET_I(1);
    vlSelf->__PVT___GEN_193 = VL_RAND_RESET_I(1);
    vlSelf->__PVT___GEN_194 = VL_RAND_RESET_I(1);
    vlSelf->__PVT___GEN_195 = VL_RAND_RESET_I(1);
    vlSelf->__PVT___pipeBlockOut_T_2 = VL_RAND_RESET_I(1);
    vlSelf->__PVT___pipeBlockOut_T_3 = VL_RAND_RESET_I(1);
    vlSelf->__PVT___pipeBlockOut_T_4 = VL_RAND_RESET_I(1);
    vlSelf->__PVT___pipeBlockOut_T_5 = VL_RAND_RESET_I(1);
    vlSelf->__PVT___waitMSUpdate_T_1 = VL_RAND_RESET_I(4);
    vlSelf->__PVT___waitMSUpdate_T_38 = VL_RAND_RESET_I(4);
    vlSelf->__PVT__waitMSUpdate = VL_RAND_RESET_I(4);
    vlSelf->__PVT__s1_Block = VL_RAND_RESET_I(1);
    vlSelf->__PVT___GEN_385 = VL_RAND_RESET_I(3);
    vlSelf->__PVT___waitMSUpdate_T_40 = VL_RAND_RESET_I(4);
    vlSelf->__PVT___waitMSUpdate_T_77 = VL_RAND_RESET_I(4);
    vlSelf->__PVT__waitMSUpdate_1 = VL_RAND_RESET_I(4);
    vlSelf->__PVT__s1_Block_1 = VL_RAND_RESET_I(1);
    vlSelf->__PVT___GEN_390 = VL_RAND_RESET_I(3);
    vlSelf->__PVT___waitMSUpdate_T_79 = VL_RAND_RESET_I(4);
    vlSelf->__PVT___waitMSUpdate_T_116 = VL_RAND_RESET_I(4);
    vlSelf->__PVT__waitMSUpdate_2 = VL_RAND_RESET_I(4);
    vlSelf->__PVT__s1_Block_2 = VL_RAND_RESET_I(1);
    vlSelf->__PVT___GEN_395 = VL_RAND_RESET_I(3);
    vlSelf->__PVT___waitMSUpdate_T_118 = VL_RAND_RESET_I(4);
    vlSelf->__PVT___waitMSUpdate_T_155 = VL_RAND_RESET_I(4);
    vlSelf->__PVT__waitMSUpdate_3 = VL_RAND_RESET_I(4);
    vlSelf->__PVT__s1_Block_3 = VL_RAND_RESET_I(1);
    vlSelf->__PVT___GEN_400 = VL_RAND_RESET_I(3);
    vlSelf->__PVT___io_out_valid_T = VL_RAND_RESET_I(1);
    vlSelf->__PVT__counter = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__next_counter = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_1 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__next_counter_1 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_2 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__next_counter_2 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_3 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__next_counter_3 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_4 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__next_counter_4 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_5 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__next_counter_5 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_6 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__next_counter_6 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_7 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__next_counter_7 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_8 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__next_counter_8 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_9 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__next_counter_9 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_10 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__next_counter_10 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_11 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__next_counter_11 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__bufferTimer_0 = VL_RAND_RESET_I(16);
    vlSelf->__PVT__bufferTimer_1 = VL_RAND_RESET_I(16);
    vlSelf->__PVT__bufferTimer_2 = VL_RAND_RESET_I(16);
    vlSelf->__PVT__bufferTimer_3 = VL_RAND_RESET_I(16);
    vlSelf->__PVT___bufferTimer_0_T_1 = VL_RAND_RESET_I(16);
    vlSelf->__PVT__REG = VL_RAND_RESET_I(1);
    vlSelf->__PVT__REG_1 = VL_RAND_RESET_I(1);
    vlSelf->__PVT__enable_REG = VL_RAND_RESET_I(1);
    vlSelf->__PVT__enable = VL_RAND_RESET_I(1);
    vlSelf->__PVT__counter_12 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_13 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_13 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_15 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_14 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_17 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_15 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_19 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_16 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_21 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_17 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_23 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_18 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_25 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_19 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_27 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_20 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_29 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_21 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_31 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_22 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_33 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_23 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_35 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_24 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_37 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_25 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_39 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_26 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_41 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_27 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_43 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_28 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_45 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_29 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_47 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_30 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_49 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_31 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_51 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_32 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_53 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_33 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_55 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_34 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_57 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_35 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_59 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_36 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_61 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_37 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_63 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_38 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_65 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_39 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_67 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_40 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_69 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_41 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_71 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_42 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_73 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_43 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_75 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_44 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_77 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_45 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_79 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_46 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_81 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_47 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_83 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_48 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_85 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_49 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_87 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_50 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_89 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__max = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__next_max = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___bufferTimer_1_T_1 = VL_RAND_RESET_I(16);
    vlSelf->__PVT__REG_2 = VL_RAND_RESET_I(1);
    vlSelf->__PVT__REG_3 = VL_RAND_RESET_I(1);
    vlSelf->__PVT__enable_REG_1 = VL_RAND_RESET_I(1);
    vlSelf->__PVT__enable_1 = VL_RAND_RESET_I(1);
    vlSelf->__PVT__counter_51 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_91 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_52 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_93 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_53 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_95 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_54 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_97 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_55 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_99 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_56 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_101 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_57 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_103 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_58 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_105 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_59 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_107 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_60 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_109 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_61 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_111 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_62 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_113 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_63 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_115 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_64 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_117 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_65 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_119 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_66 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_121 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_67 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_123 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_68 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_125 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_69 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_127 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_70 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_129 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_71 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_131 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_72 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_133 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_73 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_135 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_74 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_137 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_75 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_139 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_76 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_141 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_77 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_143 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_78 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_145 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_79 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_147 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_80 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_149 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_81 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_151 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_82 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_153 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_83 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_155 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_84 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_157 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_85 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_159 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_86 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_161 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_87 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_163 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_88 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_165 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_89 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_167 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__max_1 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__next_max_1 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___bufferTimer_2_T_1 = VL_RAND_RESET_I(16);
    vlSelf->__PVT__REG_4 = VL_RAND_RESET_I(1);
    vlSelf->__PVT__REG_5 = VL_RAND_RESET_I(1);
    vlSelf->__PVT__enable_REG_2 = VL_RAND_RESET_I(1);
    vlSelf->__PVT__enable_2 = VL_RAND_RESET_I(1);
    vlSelf->__PVT__counter_90 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_169 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_91 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_171 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_92 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_173 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_93 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_175 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_94 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_177 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_95 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_179 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_96 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_181 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_97 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_183 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_98 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_185 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_99 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_187 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_100 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_189 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_101 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_191 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_102 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_193 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_103 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_195 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_104 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_197 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_105 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_199 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_106 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_201 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_107 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_203 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_108 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_205 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_109 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_207 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_110 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_209 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_111 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_211 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_112 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_213 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_113 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_215 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_114 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_217 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_115 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_219 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_116 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_221 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_117 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_223 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_118 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_225 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_119 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_227 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_120 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_229 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_121 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_231 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_122 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_233 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_123 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_235 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_124 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_237 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_125 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_239 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_126 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_241 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_127 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_243 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_128 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_245 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__max_2 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__next_max_2 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___bufferTimer_3_T_1 = VL_RAND_RESET_I(16);
    vlSelf->__PVT__REG_6 = VL_RAND_RESET_I(1);
    vlSelf->__PVT__REG_7 = VL_RAND_RESET_I(1);
    vlSelf->__PVT__enable_REG_3 = VL_RAND_RESET_I(1);
    vlSelf->__PVT__enable_3 = VL_RAND_RESET_I(1);
    vlSelf->__PVT__counter_129 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_247 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_130 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_249 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_131 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_251 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_132 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_253 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_133 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_255 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_134 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_257 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_135 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_259 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_136 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_261 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_137 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_263 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_138 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_265 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_139 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_267 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_140 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_269 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_141 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_271 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_142 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_273 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_143 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_275 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_144 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_277 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_145 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_279 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_146 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_281 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_147 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_283 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_148 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_285 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_149 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_287 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_150 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_289 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_151 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_291 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_152 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_293 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_153 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_295 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_154 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_297 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_155 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_299 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_156 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_301 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_157 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_303 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_158 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_305 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_159 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_307 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_160 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_309 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_161 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_311 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_162 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_313 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_163 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_315 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_164 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_317 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_165 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_319 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_166 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_321 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__counter_167 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___counter_T_323 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__max_3 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__next_max_3 = VL_RAND_RESET_Q(64);
    vlSelf->__VdfgRegularize_h0f5bbeb4_2_6 = VL_RAND_RESET_I(2);
    vlSelf->__PVT__issueArb__DOT___ctrl_validMask_grantMask_lastGrant_T = VL_RAND_RESET_I(1);
    vlSelf->__PVT__issueArb__DOT__ctrl_validMask_grantMask_lastGrant = VL_RAND_RESET_I(2);
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_channel[__Vi0] = VL_RAND_RESET_I(3);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_set[__Vi0] = VL_RAND_RESET_I(2);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_tag[__Vi0] = VL_RAND_RESET_I(2);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_off[__Vi0] = VL_RAND_RESET_I(1);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_alias[__Vi0] = VL_RAND_RESET_I(2);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_opcode[__Vi0] = VL_RAND_RESET_I(3);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_param[__Vi0] = VL_RAND_RESET_I(3);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_sourceId[__Vi0] = VL_RAND_RESET_I(8);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_needProbeAckData[__Vi0] = VL_RAND_RESET_I(1);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_mshrTask[__Vi0] = VL_RAND_RESET_I(1);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_mshrId[__Vi0] = VL_RAND_RESET_I(8);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_useProbeData[__Vi0] = VL_RAND_RESET_I(1);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_dirty[__Vi0] = VL_RAND_RESET_I(1);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_way[__Vi0] = VL_RAND_RESET_I(1);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_meta_dirty[__Vi0] = VL_RAND_RESET_I(1);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_meta_state[__Vi0] = VL_RAND_RESET_I(2);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_meta_clients[__Vi0] = VL_RAND_RESET_I(1);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_meta_alias[__Vi0] = VL_RAND_RESET_I(2);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_meta_accessed[__Vi0] = VL_RAND_RESET_I(1);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_metaWen[__Vi0] = VL_RAND_RESET_I(1);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_tagWen[__Vi0] = VL_RAND_RESET_I(1);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_dsWen[__Vi0] = VL_RAND_RESET_I(1);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_replTask[__Vi0] = VL_RAND_RESET_I(1);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_reqSource[__Vi0] = VL_RAND_RESET_I(4);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_mergeA[__Vi0] = VL_RAND_RESET_I(1);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_aMergeTask_opcode[__Vi0] = VL_RAND_RESET_I(3);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_aMergeTask_param[__Vi0] = VL_RAND_RESET_I(3);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_aMergeTask_sourceId[__Vi0] = VL_RAND_RESET_I(8);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_aMergeTask_meta_dirty[__Vi0] = VL_RAND_RESET_I(1);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_aMergeTask_meta_state[__Vi0] = VL_RAND_RESET_I(2);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_aMergeTask_meta_clients[__Vi0] = VL_RAND_RESET_I(1);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_aMergeTask_meta_alias[__Vi0] = VL_RAND_RESET_I(2);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_aMergeTask_meta_accessed[__Vi0] = VL_RAND_RESET_I(1);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_snpHitRelease[__Vi0] = VL_RAND_RESET_I(1);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_bits_task_snpHitReleaseIdx[__Vi0] = VL_RAND_RESET_I(8);
    }
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        vlSelf->__PVT__chosenQ__DOT__ram_id[__Vi0] = VL_RAND_RESET_I(2);
    }
    vlSelf->__PVT__chosenQ__DOT__maybe_full = VL_RAND_RESET_I(1);
    vlSelf->__PVT__chosenQ__DOT__do_deq = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__chosenQ__DOT__ram_bits_task_meta_alias__v0 = 0;
    vlSelf->__VdlySet__chosenQ__DOT__ram_bits_task_meta_state__v0 = 0;
    vlSelf->__VdlySet__chosenQ__DOT__ram_bits_task_dirty__v0 = 0;
    vlSelf->__VdlySet__chosenQ__DOT__ram_bits_task_useProbeData__v0 = 0;
    vlSelf->__VdlySet__chosenQ__DOT__ram_bits_task_aMergeTask_meta_accessed__v0 = 0;
    vlSelf->__VdlySet__chosenQ__DOT__ram_bits_task_aMergeTask_meta_alias__v0 = 0;
    vlSelf->__VdlySet__chosenQ__DOT__ram_bits_task_aMergeTask_meta_clients__v0 = 0;
    vlSelf->__VdlySet__chosenQ__DOT__ram_bits_task_meta_dirty__v0 = 0;
    vlSelf->__VdlySet__chosenQ__DOT__ram_bits_task_needProbeAckData__v0 = 0;
    vlSelf->__VdlySet__chosenQ__DOT__ram_bits_task_snpHitReleaseIdx__v0 = 0;
    vlSelf->__VdlySet__chosenQ__DOT__ram_bits_task_meta_clients__v0 = 0;
    vlSelf->__VdlyVal__chosenQ__DOT__ram_bits_task_off__v0 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__chosenQ__DOT__ram_bits_task_off__v0 = 0;
    vlSelf->__VdlySet__chosenQ__DOT__ram_bits_task_replTask__v0 = 0;
    vlSelf->__VdlySet__chosenQ__DOT__ram_bits_task_aMergeTask_meta_state__v0 = 0;
    vlSelf->__VdlySet__chosenQ__DOT__ram_bits_task_aMergeTask_meta_dirty__v0 = 0;
    vlSelf->__VdlySet__chosenQ__DOT__ram_bits_task_snpHitRelease__v0 = 0;
    vlSelf->__VdlySet__chosenQ__DOT__ram_bits_task_alias__v0 = 0;
    vlSelf->__VdlySet__chosenQ__DOT__ram_bits_task_way__v0 = 0;
    vlSelf->__VdlyVal__chosenQ__DOT__ram_bits_task_param__v0 = VL_RAND_RESET_I(3);
    vlSelf->__VdlySet__chosenQ__DOT__ram_bits_task_param__v0 = 0;
    vlSelf->__VdlySet__chosenQ__DOT__ram_bits_task_aMergeTask_param__v0 = 0;
    vlSelf->__VdlySet__chosenQ__DOT__ram_bits_task_meta_accessed__v0 = 0;
    vlSelf->__VdlySet__chosenQ__DOT__ram_bits_task_metaWen__v0 = 0;
    vlSelf->__VdlySet__chosenQ__DOT__ram_bits_task_tagWen__v0 = 0;
    vlSelf->__VdlySet__chosenQ__DOT__ram_bits_task_dsWen__v0 = 0;
}
