// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See VVerifyTop.h for the primary calling header

#ifndef VERILATED_VVERIFYTOP_REQUESTARB_2_H_
#define VERILATED_VVERIFYTOP_REQUESTARB_2_H_  // guard

#include "verilated.h"


class VVerifyTop__Syms;

class alignas(VL_CACHE_LINE_BYTES) VVerifyTop_RequestArb_2 final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clock,0,0);
        VL_IN8(reset,0,0);
        VL_OUT8(io_sinkA_ready,0,0);
        VL_IN8(io_sinkA_valid,0,0);
        VL_IN8(io_sinkA_bits_channel,2,0);
        VL_IN8(io_sinkA_bits_txChannel,2,0);
        VL_IN8(io_sinkA_bits_set,1,0);
        VL_IN8(io_sinkA_bits_tag,1,0);
        VL_IN8(io_sinkA_bits_off,0,0);
        VL_IN8(io_sinkA_bits_alias,1,0);
        VL_IN8(io_sinkA_bits_opcode,2,0);
        VL_IN8(io_sinkA_bits_param,2,0);
        VL_IN8(io_sinkA_bits_size,0,0);
        VL_IN8(io_sinkA_bits_sourceId,7,0);
        VL_IN8(io_sinkA_bits_bufIdx,1,0);
        VL_IN8(io_sinkA_bits_needProbeAckData,0,0);
        VL_IN8(io_sinkA_bits_mshrTask,0,0);
        VL_IN8(io_sinkA_bits_mshrId,7,0);
        VL_IN8(io_sinkA_bits_aliasTask,0,0);
        VL_IN8(io_sinkA_bits_useProbeData,0,0);
        VL_IN8(io_sinkA_bits_mshrRetry,0,0);
        VL_IN8(io_sinkA_bits_dirty,0,0);
        VL_IN8(io_sinkA_bits_way,0,0);
        VL_IN8(io_sinkA_bits_meta_dirty,0,0);
        VL_IN8(io_sinkA_bits_meta_state,1,0);
        VL_IN8(io_sinkA_bits_meta_clients,0,0);
        VL_IN8(io_sinkA_bits_meta_alias,1,0);
        VL_IN8(io_sinkA_bits_meta_accessed,0,0);
        VL_IN8(io_sinkA_bits_metaWen,0,0);
        VL_IN8(io_sinkA_bits_tagWen,0,0);
        VL_IN8(io_sinkA_bits_dsWen,0,0);
        VL_IN8(io_sinkA_bits_wayMask,1,0);
        VL_IN8(io_sinkA_bits_replTask,0,0);
        VL_IN8(io_sinkA_bits_reqSource,3,0);
        VL_IN8(io_sinkA_bits_mergeA,0,0);
        VL_IN8(io_sinkA_bits_aMergeTask_off,0,0);
        VL_IN8(io_sinkA_bits_aMergeTask_alias,1,0);
        VL_IN8(io_sinkA_bits_aMergeTask_opcode,2,0);
        VL_IN8(io_sinkA_bits_aMergeTask_param,2,0);
        VL_IN8(io_sinkA_bits_aMergeTask_sourceId,7,0);
        VL_IN8(io_sinkA_bits_aMergeTask_meta_dirty,0,0);
        VL_IN8(io_sinkA_bits_aMergeTask_meta_state,1,0);
        VL_IN8(io_sinkA_bits_aMergeTask_meta_clients,0,0);
        VL_IN8(io_sinkA_bits_aMergeTask_meta_alias,1,0);
        VL_IN8(io_sinkA_bits_aMergeTask_meta_accessed,0,0);
        VL_IN8(io_sinkA_bits_snpHitRelease,0,0);
        VL_IN8(io_sinkA_bits_snpHitReleaseWithData,0,0);
        VL_IN8(io_sinkA_bits_snpHitReleaseIdx,7,0);
        VL_IN8(io_ATag,1,0);
        VL_IN8(io_ASet,1,0);
        VL_OUT8(io_s1Entrance_valid,0,0);
        VL_OUT8(io_s1Entrance_bits_set,1,0);
        VL_OUT8(io_sinkB_ready,0,0);
        VL_IN8(io_sinkB_valid,0,0);
        VL_IN8(io_sinkB_bits_channel,2,0);
        VL_IN8(io_sinkB_bits_txChannel,2,0);
        VL_IN8(io_sinkB_bits_set,1,0);
        VL_IN8(io_sinkB_bits_tag,1,0);
        VL_IN8(io_sinkB_bits_off,0,0);
        VL_IN8(io_sinkB_bits_alias,1,0);
        VL_IN8(io_sinkB_bits_opcode,2,0);
        VL_IN8(io_sinkB_bits_param,2,0);
        VL_IN8(io_sinkB_bits_size,0,0);
        VL_IN8(io_sinkB_bits_sourceId,7,0);
    };
    struct {
        VL_IN8(io_sinkB_bits_bufIdx,1,0);
        VL_IN8(io_sinkB_bits_needProbeAckData,0,0);
        VL_IN8(io_sinkB_bits_mshrTask,0,0);
        VL_IN8(io_sinkB_bits_mshrId,7,0);
        VL_IN8(io_sinkB_bits_aliasTask,0,0);
        VL_IN8(io_sinkB_bits_useProbeData,0,0);
        VL_IN8(io_sinkB_bits_mshrRetry,0,0);
        VL_IN8(io_sinkB_bits_dirty,0,0);
        VL_IN8(io_sinkB_bits_way,0,0);
        VL_IN8(io_sinkB_bits_meta_dirty,0,0);
        VL_IN8(io_sinkB_bits_meta_state,1,0);
        VL_IN8(io_sinkB_bits_meta_clients,0,0);
        VL_IN8(io_sinkB_bits_meta_alias,1,0);
        VL_IN8(io_sinkB_bits_meta_accessed,0,0);
        VL_IN8(io_sinkB_bits_metaWen,0,0);
        VL_IN8(io_sinkB_bits_tagWen,0,0);
        VL_IN8(io_sinkB_bits_dsWen,0,0);
        VL_IN8(io_sinkB_bits_wayMask,1,0);
        VL_IN8(io_sinkB_bits_replTask,0,0);
        VL_IN8(io_sinkB_bits_reqSource,3,0);
        VL_IN8(io_sinkB_bits_mergeA,0,0);
        VL_IN8(io_sinkB_bits_aMergeTask_off,0,0);
        VL_IN8(io_sinkB_bits_aMergeTask_alias,1,0);
        VL_IN8(io_sinkB_bits_aMergeTask_opcode,2,0);
        VL_IN8(io_sinkB_bits_aMergeTask_param,2,0);
        VL_IN8(io_sinkB_bits_aMergeTask_sourceId,7,0);
        VL_IN8(io_sinkB_bits_aMergeTask_meta_dirty,0,0);
        VL_IN8(io_sinkB_bits_aMergeTask_meta_state,1,0);
        VL_IN8(io_sinkB_bits_aMergeTask_meta_clients,0,0);
        VL_IN8(io_sinkB_bits_aMergeTask_meta_alias,1,0);
        VL_IN8(io_sinkB_bits_aMergeTask_meta_accessed,0,0);
        VL_IN8(io_sinkB_bits_snpHitRelease,0,0);
        VL_IN8(io_sinkB_bits_snpHitReleaseWithData,0,0);
        VL_IN8(io_sinkB_bits_snpHitReleaseIdx,7,0);
        VL_OUT8(io_sinkC_ready,0,0);
        VL_IN8(io_sinkC_valid,0,0);
        VL_IN8(io_sinkC_bits_channel,2,0);
        VL_IN8(io_sinkC_bits_txChannel,2,0);
        VL_IN8(io_sinkC_bits_set,1,0);
        VL_IN8(io_sinkC_bits_tag,1,0);
        VL_IN8(io_sinkC_bits_off,0,0);
        VL_IN8(io_sinkC_bits_alias,1,0);
        VL_IN8(io_sinkC_bits_opcode,2,0);
        VL_IN8(io_sinkC_bits_param,2,0);
        VL_IN8(io_sinkC_bits_size,0,0);
        VL_IN8(io_sinkC_bits_sourceId,7,0);
        VL_IN8(io_sinkC_bits_bufIdx,1,0);
        VL_IN8(io_sinkC_bits_needProbeAckData,0,0);
        VL_IN8(io_sinkC_bits_mshrTask,0,0);
        VL_IN8(io_sinkC_bits_mshrId,7,0);
        VL_IN8(io_sinkC_bits_aliasTask,0,0);
        VL_IN8(io_sinkC_bits_useProbeData,0,0);
        VL_IN8(io_sinkC_bits_mshrRetry,0,0);
        VL_IN8(io_sinkC_bits_dirty,0,0);
        VL_IN8(io_sinkC_bits_way,0,0);
        VL_IN8(io_sinkC_bits_meta_dirty,0,0);
        VL_IN8(io_sinkC_bits_meta_state,1,0);
        VL_IN8(io_sinkC_bits_meta_clients,0,0);
        VL_IN8(io_sinkC_bits_meta_alias,1,0);
        VL_IN8(io_sinkC_bits_meta_accessed,0,0);
        VL_IN8(io_sinkC_bits_metaWen,0,0);
        VL_IN8(io_sinkC_bits_tagWen,0,0);
        VL_IN8(io_sinkC_bits_dsWen,0,0);
        VL_IN8(io_sinkC_bits_wayMask,1,0);
    };
    struct {
        VL_IN8(io_sinkC_bits_replTask,0,0);
        VL_IN8(io_sinkC_bits_reqSource,3,0);
        VL_IN8(io_sinkC_bits_mergeA,0,0);
        VL_IN8(io_sinkC_bits_aMergeTask_off,0,0);
        VL_IN8(io_sinkC_bits_aMergeTask_alias,1,0);
        VL_IN8(io_sinkC_bits_aMergeTask_opcode,2,0);
        VL_IN8(io_sinkC_bits_aMergeTask_param,2,0);
        VL_IN8(io_sinkC_bits_aMergeTask_sourceId,7,0);
        VL_IN8(io_sinkC_bits_aMergeTask_meta_dirty,0,0);
        VL_IN8(io_sinkC_bits_aMergeTask_meta_state,1,0);
        VL_IN8(io_sinkC_bits_aMergeTask_meta_clients,0,0);
        VL_IN8(io_sinkC_bits_aMergeTask_meta_alias,1,0);
        VL_IN8(io_sinkC_bits_aMergeTask_meta_accessed,0,0);
        VL_IN8(io_sinkC_bits_snpHitRelease,0,0);
        VL_IN8(io_sinkC_bits_snpHitReleaseWithData,0,0);
        VL_IN8(io_sinkC_bits_snpHitReleaseIdx,7,0);
        VL_OUT8(io_mshrTask_ready,0,0);
        VL_IN8(io_mshrTask_valid,0,0);
        VL_IN8(io_mshrTask_bits_channel,2,0);
        VL_IN8(io_mshrTask_bits_txChannel,2,0);
        VL_IN8(io_mshrTask_bits_set,1,0);
        VL_IN8(io_mshrTask_bits_tag,1,0);
        VL_IN8(io_mshrTask_bits_off,0,0);
        VL_IN8(io_mshrTask_bits_alias,1,0);
        VL_IN8(io_mshrTask_bits_opcode,2,0);
        VL_IN8(io_mshrTask_bits_param,2,0);
        VL_IN8(io_mshrTask_bits_size,0,0);
        VL_IN8(io_mshrTask_bits_sourceId,7,0);
        VL_IN8(io_mshrTask_bits_bufIdx,1,0);
        VL_IN8(io_mshrTask_bits_needProbeAckData,0,0);
        VL_IN8(io_mshrTask_bits_mshrTask,0,0);
        VL_IN8(io_mshrTask_bits_mshrId,7,0);
        VL_IN8(io_mshrTask_bits_aliasTask,0,0);
        VL_IN8(io_mshrTask_bits_useProbeData,0,0);
        VL_IN8(io_mshrTask_bits_mshrRetry,0,0);
        VL_IN8(io_mshrTask_bits_dirty,0,0);
        VL_IN8(io_mshrTask_bits_way,0,0);
        VL_IN8(io_mshrTask_bits_meta_dirty,0,0);
        VL_IN8(io_mshrTask_bits_meta_state,1,0);
        VL_IN8(io_mshrTask_bits_meta_clients,0,0);
        VL_IN8(io_mshrTask_bits_meta_alias,1,0);
        VL_IN8(io_mshrTask_bits_meta_accessed,0,0);
        VL_IN8(io_mshrTask_bits_metaWen,0,0);
        VL_IN8(io_mshrTask_bits_tagWen,0,0);
        VL_IN8(io_mshrTask_bits_dsWen,0,0);
        VL_IN8(io_mshrTask_bits_wayMask,1,0);
        VL_IN8(io_mshrTask_bits_replTask,0,0);
        VL_IN8(io_mshrTask_bits_reqSource,3,0);
        VL_IN8(io_mshrTask_bits_mergeA,0,0);
        VL_IN8(io_mshrTask_bits_aMergeTask_off,0,0);
        VL_IN8(io_mshrTask_bits_aMergeTask_alias,1,0);
        VL_IN8(io_mshrTask_bits_aMergeTask_opcode,2,0);
        VL_IN8(io_mshrTask_bits_aMergeTask_param,2,0);
        VL_IN8(io_mshrTask_bits_aMergeTask_sourceId,7,0);
        VL_IN8(io_mshrTask_bits_aMergeTask_meta_dirty,0,0);
        VL_IN8(io_mshrTask_bits_aMergeTask_meta_state,1,0);
        VL_IN8(io_mshrTask_bits_aMergeTask_meta_clients,0,0);
        VL_IN8(io_mshrTask_bits_aMergeTask_meta_alias,1,0);
        VL_IN8(io_mshrTask_bits_aMergeTask_meta_accessed,0,0);
        VL_IN8(io_mshrTask_bits_snpHitRelease,0,0);
        VL_IN8(io_mshrTask_bits_snpHitReleaseWithData,0,0);
        VL_IN8(io_mshrTask_bits_snpHitReleaseIdx,7,0);
        VL_IN8(io_dirRead_s1_ready,0,0);
        VL_OUT8(io_dirRead_s1_valid,0,0);
    };
    struct {
        VL_OUT8(io_dirRead_s1_bits_tag,1,0);
        VL_OUT8(io_dirRead_s1_bits_set,1,0);
        VL_OUT8(io_dirRead_s1_bits_wayMask,1,0);
        VL_OUT8(io_dirRead_s1_bits_replacerInfo_channel,2,0);
        VL_OUT8(io_dirRead_s1_bits_replacerInfo_opcode,2,0);
        VL_OUT8(io_dirRead_s1_bits_replacerInfo_reqSource,3,0);
        VL_OUT8(io_dirRead_s1_bits_replacerInfo_refill_prefetch,0,0);
        VL_OUT8(io_dirRead_s1_bits_refill,0,0);
        VL_OUT8(io_dirRead_s1_bits_mshrId,7,0);
        VL_OUT8(io_taskToPipe_s2_valid,0,0);
        VL_OUT8(io_taskToPipe_s2_bits_channel,2,0);
        VL_OUT8(io_taskToPipe_s2_bits_txChannel,2,0);
        VL_OUT8(io_taskToPipe_s2_bits_set,1,0);
        VL_OUT8(io_taskToPipe_s2_bits_tag,1,0);
        VL_OUT8(io_taskToPipe_s2_bits_off,0,0);
        VL_OUT8(io_taskToPipe_s2_bits_alias,1,0);
        VL_OUT8(io_taskToPipe_s2_bits_opcode,2,0);
        VL_OUT8(io_taskToPipe_s2_bits_param,2,0);
        VL_OUT8(io_taskToPipe_s2_bits_size,0,0);
        VL_OUT8(io_taskToPipe_s2_bits_sourceId,7,0);
        VL_OUT8(io_taskToPipe_s2_bits_bufIdx,1,0);
        VL_OUT8(io_taskToPipe_s2_bits_needProbeAckData,0,0);
        VL_OUT8(io_taskToPipe_s2_bits_mshrTask,0,0);
        VL_OUT8(io_taskToPipe_s2_bits_mshrId,7,0);
        VL_OUT8(io_taskToPipe_s2_bits_aliasTask,0,0);
        VL_OUT8(io_taskToPipe_s2_bits_useProbeData,0,0);
        VL_OUT8(io_taskToPipe_s2_bits_mshrRetry,0,0);
        VL_OUT8(io_taskToPipe_s2_bits_dirty,0,0);
        VL_OUT8(io_taskToPipe_s2_bits_way,0,0);
        VL_OUT8(io_taskToPipe_s2_bits_meta_dirty,0,0);
        VL_OUT8(io_taskToPipe_s2_bits_meta_state,1,0);
        VL_OUT8(io_taskToPipe_s2_bits_meta_clients,0,0);
        VL_OUT8(io_taskToPipe_s2_bits_meta_alias,1,0);
        VL_OUT8(io_taskToPipe_s2_bits_meta_accessed,0,0);
        VL_OUT8(io_taskToPipe_s2_bits_metaWen,0,0);
        VL_OUT8(io_taskToPipe_s2_bits_tagWen,0,0);
        VL_OUT8(io_taskToPipe_s2_bits_dsWen,0,0);
        VL_OUT8(io_taskToPipe_s2_bits_wayMask,1,0);
        VL_OUT8(io_taskToPipe_s2_bits_replTask,0,0);
        VL_OUT8(io_taskToPipe_s2_bits_reqSource,3,0);
        VL_OUT8(io_taskToPipe_s2_bits_mergeA,0,0);
        VL_OUT8(io_taskToPipe_s2_bits_aMergeTask_off,0,0);
        VL_OUT8(io_taskToPipe_s2_bits_aMergeTask_alias,1,0);
        VL_OUT8(io_taskToPipe_s2_bits_aMergeTask_opcode,2,0);
        VL_OUT8(io_taskToPipe_s2_bits_aMergeTask_param,2,0);
        VL_OUT8(io_taskToPipe_s2_bits_aMergeTask_sourceId,7,0);
        VL_OUT8(io_taskToPipe_s2_bits_aMergeTask_meta_dirty,0,0);
        VL_OUT8(io_taskToPipe_s2_bits_aMergeTask_meta_state,1,0);
        VL_OUT8(io_taskToPipe_s2_bits_aMergeTask_meta_clients,0,0);
        VL_OUT8(io_taskToPipe_s2_bits_aMergeTask_meta_alias,1,0);
        VL_OUT8(io_taskToPipe_s2_bits_aMergeTask_meta_accessed,0,0);
        VL_OUT8(io_taskToPipe_s2_bits_snpHitRelease,0,0);
        VL_OUT8(io_taskToPipe_s2_bits_snpHitReleaseWithData,0,0);
        VL_OUT8(io_taskToPipe_s2_bits_snpHitReleaseIdx,7,0);
        VL_OUT8(io_taskInfo_s1_valid,0,0);
        VL_OUT8(io_taskInfo_s1_bits_channel,2,0);
        VL_OUT8(io_taskInfo_s1_bits_txChannel,2,0);
        VL_OUT8(io_taskInfo_s1_bits_set,1,0);
        VL_OUT8(io_taskInfo_s1_bits_tag,1,0);
        VL_OUT8(io_taskInfo_s1_bits_off,0,0);
        VL_OUT8(io_taskInfo_s1_bits_alias,1,0);
        VL_OUT8(io_taskInfo_s1_bits_opcode,2,0);
        VL_OUT8(io_taskInfo_s1_bits_param,2,0);
        VL_OUT8(io_taskInfo_s1_bits_size,0,0);
    };
    struct {
        VL_OUT8(io_taskInfo_s1_bits_sourceId,7,0);
        VL_OUT8(io_taskInfo_s1_bits_bufIdx,1,0);
        VL_OUT8(io_taskInfo_s1_bits_needProbeAckData,0,0);
        VL_OUT8(io_taskInfo_s1_bits_mshrTask,0,0);
        VL_OUT8(io_taskInfo_s1_bits_mshrId,7,0);
        VL_OUT8(io_taskInfo_s1_bits_aliasTask,0,0);
        VL_OUT8(io_taskInfo_s1_bits_useProbeData,0,0);
        VL_OUT8(io_taskInfo_s1_bits_mshrRetry,0,0);
        VL_OUT8(io_taskInfo_s1_bits_dirty,0,0);
        VL_OUT8(io_taskInfo_s1_bits_way,0,0);
        VL_OUT8(io_taskInfo_s1_bits_meta_dirty,0,0);
        VL_OUT8(io_taskInfo_s1_bits_meta_state,1,0);
        VL_OUT8(io_taskInfo_s1_bits_meta_clients,0,0);
        VL_OUT8(io_taskInfo_s1_bits_meta_alias,1,0);
        VL_OUT8(io_taskInfo_s1_bits_meta_accessed,0,0);
        VL_OUT8(io_taskInfo_s1_bits_metaWen,0,0);
        VL_OUT8(io_taskInfo_s1_bits_tagWen,0,0);
        VL_OUT8(io_taskInfo_s1_bits_dsWen,0,0);
        VL_OUT8(io_taskInfo_s1_bits_wayMask,1,0);
        VL_OUT8(io_taskInfo_s1_bits_replTask,0,0);
        VL_OUT8(io_taskInfo_s1_bits_reqSource,3,0);
        VL_OUT8(io_taskInfo_s1_bits_mergeA,0,0);
        VL_OUT8(io_taskInfo_s1_bits_aMergeTask_off,0,0);
        VL_OUT8(io_taskInfo_s1_bits_aMergeTask_alias,1,0);
        VL_OUT8(io_taskInfo_s1_bits_aMergeTask_opcode,2,0);
        VL_OUT8(io_taskInfo_s1_bits_aMergeTask_param,2,0);
        VL_OUT8(io_taskInfo_s1_bits_aMergeTask_sourceId,7,0);
        VL_OUT8(io_taskInfo_s1_bits_aMergeTask_meta_dirty,0,0);
        VL_OUT8(io_taskInfo_s1_bits_aMergeTask_meta_state,1,0);
        VL_OUT8(io_taskInfo_s1_bits_aMergeTask_meta_clients,0,0);
        VL_OUT8(io_taskInfo_s1_bits_aMergeTask_meta_alias,1,0);
        VL_OUT8(io_taskInfo_s1_bits_aMergeTask_meta_accessed,0,0);
        VL_OUT8(io_taskInfo_s1_bits_snpHitRelease,0,0);
        VL_OUT8(io_taskInfo_s1_bits_snpHitReleaseWithData,0,0);
        VL_OUT8(io_taskInfo_s1_bits_snpHitReleaseIdx,7,0);
        VL_OUT8(io_refillBufRead_s2_valid,0,0);
        VL_OUT8(io_refillBufRead_s2_bits_id,7,0);
        VL_OUT8(io_releaseBufRead_s2_valid,0,0);
        VL_OUT8(io_releaseBufRead_s2_bits_id,7,0);
        VL_OUT8(io_status_s1_tags_0,1,0);
        VL_OUT8(io_status_s1_tags_1,1,0);
        VL_OUT8(io_status_s1_tags_2,1,0);
        VL_OUT8(io_status_s1_tags_3,1,0);
        VL_OUT8(io_status_s1_sets_0,1,0);
        VL_OUT8(io_status_s1_sets_1,1,0);
        VL_OUT8(io_status_s1_sets_2,1,0);
        VL_OUT8(io_status_s1_sets_3,1,0);
        VL_OUT8(io_status_vec_0_valid,0,0);
        VL_OUT8(io_status_vec_0_bits_channel,2,0);
        VL_OUT8(io_status_vec_1_valid,0,0);
        VL_OUT8(io_status_vec_1_bits_channel,2,0);
        VL_IN8(io_fromMSHRCtl_blockG_s1,0,0);
        VL_IN8(io_fromMSHRCtl_blockA_s1,0,0);
        VL_IN8(io_fromMSHRCtl_blockB_s1,0,0);
        VL_IN8(io_fromMSHRCtl_blockC_s1,0,0);
        VL_IN8(io_fromMainPipe_blockG_s1,0,0);
        VL_IN8(io_fromMainPipe_blockA_s1,0,0);
        VL_IN8(io_fromMainPipe_blockB_s1,0,0);
        VL_IN8(io_fromMainPipe_blockC_s1,0,0);
        VL_IN8(io_fromGrantBuffer_blockSinkReqEntrance_blockG_s1,0,0);
        VL_IN8(io_fromGrantBuffer_blockSinkReqEntrance_blockA_s1,0,0);
        VL_IN8(io_fromGrantBuffer_blockSinkReqEntrance_blockB_s1,0,0);
        VL_IN8(io_fromGrantBuffer_blockSinkReqEntrance_blockC_s1,0,0);
        VL_IN8(io_fromGrantBuffer_blockMSHRReqEntrance,0,0);
    };
    struct {
        VL_IN8(io_fromSourceC_blockSinkBReqEntrance,0,0);
        VL_IN8(io_fromSourceC_blockMSHRReqEntrance,0,0);
        VL_IN8(io_msInfo_0_valid,0,0);
        VL_IN8(io_msInfo_0_bits_channel,2,0);
        VL_IN8(io_msInfo_0_bits_set,1,0);
        VL_IN8(io_msInfo_0_bits_way,0,0);
        VL_IN8(io_msInfo_0_bits_reqTag,1,0);
        VL_IN8(io_msInfo_0_bits_willFree,0,0);
        VL_IN8(io_msInfo_0_bits_aliasTask,0,0);
        VL_IN8(io_msInfo_0_bits_needRelease,0,0);
        VL_IN8(io_msInfo_0_bits_blockRefill,0,0);
        VL_IN8(io_msInfo_0_bits_metaTag,1,0);
        VL_IN8(io_msInfo_0_bits_metaState,1,0);
        VL_IN8(io_msInfo_0_bits_dirHit,0,0);
        VL_IN8(io_msInfo_0_bits_isAcqOrPrefetch,0,0);
        VL_IN8(io_msInfo_0_bits_isPrefetch,0,0);
        VL_IN8(io_msInfo_0_bits_param,2,0);
        VL_IN8(io_msInfo_0_bits_mergeA,0,0);
        VL_IN8(io_msInfo_0_bits_w_grantfirst,0,0);
        VL_IN8(io_msInfo_0_bits_s_refill,0,0);
        VL_IN8(io_msInfo_0_bits_w_releaseack,0,0);
        VL_IN8(io_msInfo_0_bits_w_replResp,0,0);
        VL_IN8(io_msInfo_0_bits_w_rprobeacklast,0,0);
        VL_IN8(io_msInfo_0_bits_replaceData,0,0);
        VL_IN8(io_msInfo_1_valid,0,0);
        VL_IN8(io_msInfo_1_bits_channel,2,0);
        VL_IN8(io_msInfo_1_bits_set,1,0);
        VL_IN8(io_msInfo_1_bits_way,0,0);
        VL_IN8(io_msInfo_1_bits_reqTag,1,0);
        VL_IN8(io_msInfo_1_bits_willFree,0,0);
        VL_IN8(io_msInfo_1_bits_aliasTask,0,0);
        VL_IN8(io_msInfo_1_bits_needRelease,0,0);
        VL_IN8(io_msInfo_1_bits_blockRefill,0,0);
        VL_IN8(io_msInfo_1_bits_metaTag,1,0);
        VL_IN8(io_msInfo_1_bits_metaState,1,0);
        VL_IN8(io_msInfo_1_bits_dirHit,0,0);
        VL_IN8(io_msInfo_1_bits_isAcqOrPrefetch,0,0);
        VL_IN8(io_msInfo_1_bits_isPrefetch,0,0);
        VL_IN8(io_msInfo_1_bits_param,2,0);
        VL_IN8(io_msInfo_1_bits_mergeA,0,0);
        VL_IN8(io_msInfo_1_bits_w_grantfirst,0,0);
        VL_IN8(io_msInfo_1_bits_s_refill,0,0);
        VL_IN8(io_msInfo_1_bits_w_releaseack,0,0);
        VL_IN8(io_msInfo_1_bits_w_replResp,0,0);
        VL_IN8(io_msInfo_1_bits_w_rprobeacklast,0,0);
        VL_IN8(io_msInfo_1_bits_replaceData,0,0);
        VL_IN8(io_msInfo_2_valid,0,0);
        VL_IN8(io_msInfo_2_bits_channel,2,0);
        VL_IN8(io_msInfo_2_bits_set,1,0);
        VL_IN8(io_msInfo_2_bits_way,0,0);
        VL_IN8(io_msInfo_2_bits_reqTag,1,0);
        VL_IN8(io_msInfo_2_bits_willFree,0,0);
        VL_IN8(io_msInfo_2_bits_aliasTask,0,0);
        VL_IN8(io_msInfo_2_bits_needRelease,0,0);
        VL_IN8(io_msInfo_2_bits_blockRefill,0,0);
        VL_IN8(io_msInfo_2_bits_metaTag,1,0);
        VL_IN8(io_msInfo_2_bits_metaState,1,0);
        VL_IN8(io_msInfo_2_bits_dirHit,0,0);
        VL_IN8(io_msInfo_2_bits_isAcqOrPrefetch,0,0);
        VL_IN8(io_msInfo_2_bits_isPrefetch,0,0);
        VL_IN8(io_msInfo_2_bits_param,2,0);
        VL_IN8(io_msInfo_2_bits_mergeA,0,0);
        VL_IN8(io_msInfo_2_bits_w_grantfirst,0,0);
        VL_IN8(io_msInfo_2_bits_s_refill,0,0);
    };
    struct {
        VL_IN8(io_msInfo_2_bits_w_releaseack,0,0);
        VL_IN8(io_msInfo_2_bits_w_replResp,0,0);
        VL_IN8(io_msInfo_2_bits_w_rprobeacklast,0,0);
        VL_IN8(io_msInfo_2_bits_replaceData,0,0);
        VL_IN8(io_msInfo_3_valid,0,0);
        VL_IN8(io_msInfo_3_bits_channel,2,0);
        VL_IN8(io_msInfo_3_bits_set,1,0);
        VL_IN8(io_msInfo_3_bits_way,0,0);
        VL_IN8(io_msInfo_3_bits_reqTag,1,0);
        VL_IN8(io_msInfo_3_bits_willFree,0,0);
        VL_IN8(io_msInfo_3_bits_aliasTask,0,0);
        VL_IN8(io_msInfo_3_bits_needRelease,0,0);
        VL_IN8(io_msInfo_3_bits_blockRefill,0,0);
        VL_IN8(io_msInfo_3_bits_metaTag,1,0);
        VL_IN8(io_msInfo_3_bits_metaState,1,0);
        VL_IN8(io_msInfo_3_bits_dirHit,0,0);
        VL_IN8(io_msInfo_3_bits_isAcqOrPrefetch,0,0);
        VL_IN8(io_msInfo_3_bits_isPrefetch,0,0);
        VL_IN8(io_msInfo_3_bits_param,2,0);
        VL_IN8(io_msInfo_3_bits_mergeA,0,0);
        VL_IN8(io_msInfo_3_bits_w_grantfirst,0,0);
        VL_IN8(io_msInfo_3_bits_s_refill,0,0);
        VL_IN8(io_msInfo_3_bits_w_releaseack,0,0);
        VL_IN8(io_msInfo_3_bits_w_replResp,0,0);
        VL_IN8(io_msInfo_3_bits_w_rprobeacklast,0,0);
        VL_IN8(io_msInfo_3_bits_replaceData,0,0);
        CData/*0:0*/ __PVT__helper_clean;
        CData/*0:0*/ __PVT__helper_dump;
        CData/*0:0*/ __PVT__helper_1_clean;
        CData/*0:0*/ __PVT__helper_1_dump;
        CData/*0:0*/ __PVT__helper_2_clean;
        CData/*0:0*/ __PVT__helper_2_dump;
        CData/*0:0*/ __PVT__helper_3_clean;
        CData/*0:0*/ __PVT__helper_3_dump;
        CData/*0:0*/ __PVT__helper_4_clean;
        CData/*0:0*/ __PVT__helper_4_dump;
        CData/*0:0*/ __PVT__helper_5_clean;
        CData/*0:0*/ __PVT__helper_5_dump;
        CData/*0:0*/ __PVT__helper_6_clean;
        CData/*0:0*/ __PVT__helper_6_dump;
        CData/*0:0*/ __PVT__helper_7_clean;
        CData/*0:0*/ __PVT__helper_7_dump;
        CData/*0:0*/ __PVT__helper_8_clean;
        CData/*0:0*/ __PVT__helper_8_dump;
        CData/*0:0*/ __PVT__helper_9_clean;
        CData/*0:0*/ __PVT__helper_9_dump;
        CData/*0:0*/ __PVT__helper_10_clean;
        CData/*0:0*/ __PVT__helper_10_dump;
        CData/*0:0*/ __PVT__helper_11_clean;
        CData/*0:0*/ __PVT__helper_11_dump;
        CData/*0:0*/ __PVT__helper_12_clean;
        CData/*0:0*/ __PVT__helper_12_dump;
        CData/*0:0*/ __PVT__helper_13_clean;
        CData/*0:0*/ __PVT__helper_13_dump;
        CData/*0:0*/ __PVT__helper_14_clean;
        CData/*0:0*/ __PVT__helper_14_dump;
        CData/*0:0*/ __PVT__helper_15_clean;
        CData/*0:0*/ __PVT__helper_15_dump;
        CData/*0:0*/ __PVT__helper_16_clean;
        CData/*0:0*/ __PVT__helper_16_dump;
        CData/*0:0*/ __PVT__helper_17_clean;
        CData/*0:0*/ __PVT__helper_17_dump;
        CData/*0:0*/ __PVT__helper_18_clean;
        CData/*0:0*/ __PVT__helper_18_dump;
    };
    struct {
        CData/*0:0*/ __PVT__helper_19_clean;
        CData/*0:0*/ __PVT__helper_19_dump;
        CData/*0:0*/ __PVT__helper_20_clean;
        CData/*0:0*/ __PVT__helper_20_dump;
        CData/*0:0*/ __PVT__helper_21_clean;
        CData/*0:0*/ __PVT__helper_21_dump;
        CData/*0:0*/ __PVT__helper_22_clean;
        CData/*0:0*/ __PVT__helper_22_dump;
        CData/*0:0*/ __PVT__helper_23_clean;
        CData/*0:0*/ __PVT__helper_23_dump;
        CData/*0:0*/ __PVT__helper_24_clean;
        CData/*0:0*/ __PVT__helper_24_dump;
        CData/*0:0*/ __PVT__resetFinish;
        CData/*1:0*/ __PVT__resetIdx;
        CData/*1:0*/ __PVT___resetIdx_T_1;
        CData/*0:0*/ __PVT___GEN_1;
        CData/*0:0*/ __PVT__mshr_task_s1_valid;
        CData/*2:0*/ __PVT__mshr_task_s1_bits_channel;
        CData/*1:0*/ __PVT__mshr_task_s1_bits_set;
        CData/*1:0*/ __PVT__mshr_task_s1_bits_tag;
        CData/*0:0*/ __PVT__mshr_task_s1_bits_off;
        CData/*1:0*/ __PVT__mshr_task_s1_bits_alias;
        CData/*2:0*/ __PVT__mshr_task_s1_bits_opcode;
        CData/*2:0*/ __PVT__mshr_task_s1_bits_param;
        CData/*7:0*/ __PVT__mshr_task_s1_bits_sourceId;
        CData/*0:0*/ __PVT__mshr_task_s1_bits_needProbeAckData;
        CData/*0:0*/ __PVT__mshr_task_s1_bits_mshrTask;
        CData/*7:0*/ __PVT__mshr_task_s1_bits_mshrId;
        CData/*0:0*/ __PVT__mshr_task_s1_bits_useProbeData;
        CData/*0:0*/ __PVT__mshr_task_s1_bits_mshrRetry;
        CData/*0:0*/ __PVT__mshr_task_s1_bits_dirty;
        CData/*0:0*/ __PVT__mshr_task_s1_bits_way;
        CData/*0:0*/ __PVT__mshr_task_s1_bits_meta_dirty;
        CData/*1:0*/ __PVT__mshr_task_s1_bits_meta_state;
        CData/*0:0*/ __PVT__mshr_task_s1_bits_meta_clients;
        CData/*1:0*/ __PVT__mshr_task_s1_bits_meta_alias;
        CData/*0:0*/ __PVT__mshr_task_s1_bits_meta_accessed;
        CData/*0:0*/ __PVT__mshr_task_s1_bits_metaWen;
        CData/*0:0*/ __PVT__mshr_task_s1_bits_tagWen;
        CData/*0:0*/ __PVT__mshr_task_s1_bits_dsWen;
        CData/*0:0*/ __PVT__mshr_task_s1_bits_replTask;
        CData/*3:0*/ __PVT__mshr_task_s1_bits_reqSource;
        CData/*0:0*/ __PVT__mshr_task_s1_bits_mergeA;
        CData/*2:0*/ __PVT__mshr_task_s1_bits_aMergeTask_opcode;
        CData/*2:0*/ __PVT__mshr_task_s1_bits_aMergeTask_param;
        CData/*7:0*/ __PVT__mshr_task_s1_bits_aMergeTask_sourceId;
        CData/*0:0*/ __PVT__mshr_task_s1_bits_aMergeTask_meta_dirty;
        CData/*1:0*/ __PVT__mshr_task_s1_bits_aMergeTask_meta_state;
        CData/*0:0*/ __PVT__mshr_task_s1_bits_aMergeTask_meta_clients;
        CData/*1:0*/ __PVT__mshr_task_s1_bits_aMergeTask_meta_alias;
        CData/*0:0*/ __PVT__mshr_task_s1_bits_aMergeTask_meta_accessed;
        CData/*0:0*/ __PVT__mshr_task_s1_bits_snpHitRelease;
        CData/*7:0*/ __PVT__mshr_task_s1_bits_snpHitReleaseIdx;
        CData/*0:0*/ __PVT___s1_needs_replRead_T_9;
        CData/*0:0*/ __PVT__ds_mcp2_stall;
        CData/*0:0*/ __PVT__s0_fire;
        CData/*0:0*/ __PVT___sinkValids_T_4;
        CData/*0:0*/ __PVT___sinkValids_T_5;
        CData/*0:0*/ __PVT__sameSet_s3_REG;
        CData/*1:0*/ __PVT__sameSet_s3_r;
        CData/*0:0*/ __PVT__task_s2_valid;
        CData/*2:0*/ __PVT__task_s2_bits_channel;
        CData/*0:0*/ __PVT___sameSet_s2_T_2;
        CData/*0:0*/ __PVT__task_s2_bits_mshrTask;
    };
    struct {
        CData/*1:0*/ __PVT__task_s2_bits_set;
        CData/*0:0*/ __PVT___sinkValids_T_2;
        CData/*0:0*/ __PVT___sinkValids_T_3;
        CData/*0:0*/ __PVT___sinkValids_T_1;
        CData/*2:0*/ __PVT__sinkValids;
        CData/*0:0*/ __PVT__chnl_task_s1_valid;
        CData/*0:0*/ __PVT__sink_ready_basic;
        CData/*2:0*/ __PVT___chnl_task_s1_bits_T_4_channel;
        CData/*1:0*/ __PVT___chnl_task_s1_bits_T_4_set;
        CData/*1:0*/ __PVT___chnl_task_s1_bits_T_4_tag;
        CData/*2:0*/ __PVT___chnl_task_s1_bits_T_4_opcode;
        CData/*7:0*/ __PVT___chnl_task_s1_bits_T_4_sourceId;
        CData/*0:0*/ __PVT___chnl_task_s1_bits_T_4_mshrTask;
        CData/*7:0*/ __PVT___chnl_task_s1_bits_T_4_mshrId;
        CData/*3:0*/ __PVT___chnl_task_s1_bits_T_4_reqSource;
        CData/*0:0*/ __PVT___chnl_task_s1_bits_T_4_mergeA;
        CData/*2:0*/ __PVT___chnl_task_s1_bits_T_4_aMergeTask_opcode;
        CData/*7:0*/ __PVT___chnl_task_s1_bits_T_4_aMergeTask_sourceId;
        CData/*0:0*/ __PVT___io_s1Entrance_valid_T_2;
        CData/*0:0*/ __PVT___io_s1Entrance_valid_T_4;
        CData/*0:0*/ __PVT___s1_AHint_fire_T;
        CData/*1:0*/ __PVT__task_s2_bits_tag;
        CData/*0:0*/ __PVT__task_s2_bits_off;
        CData/*1:0*/ __PVT__task_s2_bits_alias;
        CData/*2:0*/ __PVT__task_s2_bits_opcode;
        CData/*2:0*/ __PVT__task_s2_bits_param;
        CData/*7:0*/ __PVT__task_s2_bits_sourceId;
        CData/*0:0*/ __PVT__task_s2_bits_needProbeAckData;
        CData/*7:0*/ __PVT__task_s2_bits_mshrId;
        CData/*0:0*/ __PVT__task_s2_bits_useProbeData;
        CData/*0:0*/ __PVT__task_s2_bits_dirty;
        CData/*0:0*/ __PVT__task_s2_bits_way;
        CData/*0:0*/ __PVT__task_s2_bits_meta_dirty;
        CData/*1:0*/ __PVT__task_s2_bits_meta_state;
        CData/*0:0*/ __PVT__task_s2_bits_meta_clients;
        CData/*1:0*/ __PVT__task_s2_bits_meta_alias;
        CData/*0:0*/ __PVT__task_s2_bits_meta_accessed;
        CData/*0:0*/ __PVT__task_s2_bits_metaWen;
        CData/*0:0*/ __PVT__task_s2_bits_tagWen;
        CData/*0:0*/ __PVT__task_s2_bits_dsWen;
        CData/*0:0*/ __PVT__task_s2_bits_replTask;
        CData/*3:0*/ __PVT__task_s2_bits_reqSource;
        CData/*0:0*/ __PVT__task_s2_bits_mergeA;
        CData/*2:0*/ __PVT__task_s2_bits_aMergeTask_opcode;
        CData/*2:0*/ __PVT__task_s2_bits_aMergeTask_param;
        CData/*7:0*/ __PVT__task_s2_bits_aMergeTask_sourceId;
        CData/*0:0*/ __PVT__task_s2_bits_aMergeTask_meta_dirty;
        CData/*1:0*/ __PVT__task_s2_bits_aMergeTask_meta_state;
        CData/*0:0*/ __PVT__task_s2_bits_aMergeTask_meta_clients;
        CData/*1:0*/ __PVT__task_s2_bits_aMergeTask_meta_alias;
        CData/*0:0*/ __PVT__task_s2_bits_aMergeTask_meta_accessed;
        CData/*0:0*/ __PVT__task_s2_bits_snpHitRelease;
        CData/*7:0*/ __PVT__task_s2_bits_snpHitReleaseIdx;
        CData/*0:0*/ __PVT__mshrTask_s2;
        CData/*0:0*/ __PVT__mshrTask_s2_a_upwards;
        CData/*0:0*/ __PVT___T_77;
        CData/*0:0*/ __Vdly__mshr_task_s1_bits_meta_clients;
        CData/*0:0*/ __Vdly__mshr_task_s1_bits_dirty;
        CData/*2:0*/ __Vdly__task_s2_bits_channel;
        CData/*0:0*/ __Vdly__task_s2_bits_off;
        CData/*7:0*/ __Vdly__task_s2_bits_sourceId;
        CData/*3:0*/ __Vdly__task_s2_bits_reqSource;
        CData/*2:0*/ __Vdly__mshr_task_s1_bits_param;
        CData/*2:0*/ __Vdly__mshr_task_s1_bits_opcode;
    };
    struct {
        CData/*1:0*/ __Vdly__mshr_task_s1_bits_tag;
        CData/*0:0*/ __Vdly__mshr_task_s1_bits_useProbeData;
        CData/*1:0*/ __Vdly__mshr_task_s1_bits_meta_state;
        CData/*1:0*/ __Vdly__mshr_task_s1_bits_meta_alias;
        CData/*0:0*/ __Vdly__mshr_task_s1_bits_meta_accessed;
        CData/*0:0*/ __Vdly__mshr_task_s1_bits_dsWen;
        CData/*1:0*/ __Vdly__mshr_task_s1_bits_set;
        QData/*63:0*/ __PVT__helper_timer;
        QData/*63:0*/ __PVT__helper_1_timer;
        QData/*63:0*/ __PVT__helper_2_timer;
        QData/*63:0*/ __PVT__helper_3_timer;
        QData/*63:0*/ __PVT__helper_4_timer;
        QData/*63:0*/ __PVT__helper_5_timer;
        QData/*63:0*/ __PVT__helper_6_timer;
        QData/*63:0*/ __PVT__helper_7_timer;
        QData/*63:0*/ __PVT__helper_8_timer;
        QData/*63:0*/ __PVT__helper_9_timer;
        QData/*63:0*/ __PVT__helper_10_timer;
        QData/*63:0*/ __PVT__helper_11_timer;
        QData/*63:0*/ __PVT__helper_12_timer;
        QData/*63:0*/ __PVT__helper_13_timer;
        QData/*63:0*/ __PVT__helper_14_timer;
        QData/*63:0*/ __PVT__helper_15_timer;
        QData/*63:0*/ __PVT__helper_16_timer;
        QData/*63:0*/ __PVT__helper_17_timer;
        QData/*63:0*/ __PVT__helper_18_timer;
        QData/*63:0*/ __PVT__helper_19_timer;
        QData/*63:0*/ __PVT__helper_20_timer;
        QData/*63:0*/ __PVT__helper_21_timer;
        QData/*63:0*/ __PVT__helper_22_timer;
        QData/*63:0*/ __PVT__helper_23_timer;
        QData/*63:0*/ __PVT__helper_24_timer;
        QData/*63:0*/ __PVT__counter;
        QData/*63:0*/ __PVT__next_counter;
        QData/*63:0*/ __PVT__counter_1;
        QData/*63:0*/ __PVT__next_counter_1;
        QData/*63:0*/ __PVT__counter_2;
        QData/*63:0*/ __PVT__next_counter_2;
        QData/*63:0*/ __PVT__counter_3;
        QData/*63:0*/ __PVT__next_counter_3;
        QData/*63:0*/ __PVT__counter_4;
        QData/*63:0*/ __PVT__next_counter_4;
        QData/*63:0*/ __PVT__counter_5;
        QData/*63:0*/ __PVT__next_counter_5;
        QData/*63:0*/ __PVT__counter_6;
        QData/*63:0*/ __PVT__next_counter_6;
        QData/*63:0*/ __PVT__counter_7;
        QData/*63:0*/ __PVT__next_counter_7;
        QData/*63:0*/ __PVT__counter_8;
        QData/*63:0*/ __PVT__next_counter_8;
        QData/*63:0*/ __PVT__counter_9;
        QData/*63:0*/ __PVT__next_counter_9;
        QData/*63:0*/ __PVT__counter_10;
        QData/*63:0*/ __PVT__next_counter_10;
        QData/*63:0*/ __PVT__counter_11;
        QData/*63:0*/ __PVT__next_counter_11;
        QData/*63:0*/ __PVT__counter_12;
        QData/*63:0*/ __PVT__next_counter_12;
        QData/*63:0*/ __PVT__counter_13;
        QData/*63:0*/ __PVT__next_counter_13;
        QData/*63:0*/ __PVT__counter_14;
        QData/*63:0*/ __PVT__next_counter_14;
        QData/*63:0*/ __PVT__counter_15;
        QData/*63:0*/ __PVT__next_counter_15;
    };
    struct {
        QData/*63:0*/ __PVT__counter_16;
        QData/*63:0*/ __PVT__next_counter_16;
        QData/*63:0*/ __PVT__counter_17;
        QData/*63:0*/ __PVT__next_counter_17;
        QData/*63:0*/ __PVT__counter_18;
        QData/*63:0*/ __PVT__next_counter_18;
        QData/*63:0*/ __PVT__counter_19;
        QData/*63:0*/ __PVT__next_counter_19;
        QData/*63:0*/ __PVT__counter_20;
        QData/*63:0*/ __PVT__next_counter_20;
        QData/*63:0*/ __PVT__counter_21;
        QData/*63:0*/ __PVT__next_counter_21;
        QData/*63:0*/ __PVT__counter_22;
        QData/*63:0*/ __PVT__next_counter_22;
        QData/*63:0*/ __PVT__counter_23;
        QData/*63:0*/ __PVT__next_counter_23;
        QData/*63:0*/ __PVT__counter_24;
        QData/*63:0*/ __PVT__next_counter_24;
    };

    // INTERNAL VARIABLES
    VVerifyTop__Syms* const vlSymsp;

    // CONSTRUCTORS
    VVerifyTop_RequestArb_2(VVerifyTop__Syms* symsp, const char* v__name);
    ~VVerifyTop_RequestArb_2();
    VL_UNCOPYABLE(VVerifyTop_RequestArb_2);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
